package com.sun3d.why.model;

public class UserIntegral {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral.INTEGRAL_ID
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    private String integralId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral.USER_ID
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral.INTEGRAL_NOW
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    private Integer integralNow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral.INTEGRAL_HIS
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    private Integer integralHis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral.INTEGRAL_ID
     *
     * @return the value of sys_user_integral.INTEGRAL_ID
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    public String getIntegralId() {
        return integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral.INTEGRAL_ID
     *
     * @param integralId the value for sys_user_integral.INTEGRAL_ID
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    public void setIntegralId(String integralId) {
        this.integralId = integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral.USER_ID
     *
     * @return the value of sys_user_integral.USER_ID
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral.USER_ID
     *
     * @param userId the value for sys_user_integral.USER_ID
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral.INTEGRAL_NOW
     *
     * @return the value of sys_user_integral.INTEGRAL_NOW
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    public Integer getIntegralNow() {
        return integralNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral.INTEGRAL_NOW
     *
     * @param integralNow the value for sys_user_integral.INTEGRAL_NOW
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    public void setIntegralNow(Integer integralNow) {
        this.integralNow = integralNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral.INTEGRAL_HIS
     *
     * @return the value of sys_user_integral.INTEGRAL_HIS
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    public Integer getIntegralHis() {
        return integralHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral.INTEGRAL_HIS
     *
     * @param integralHis the value for sys_user_integral.INTEGRAL_HIS
     *
     * @mbggenerated Wed Jun 01 15:47:01 CST 2016
     */
    public void setIntegralHis(Integer integralHis) {
        this.integralHis = integralHis;
    }
}