package com.culturecloud.model.bean.drama;

import java.util.Date;

public class CcpDrama {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_drama.DRAMA_ID
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    private String dramaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_drama.DRAMA_NAME
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    private String dramaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_drama.DRAMA_IMG
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    private String dramaImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_drama.DRAMA_TAG
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    private String dramaTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_drama.DRAMA_TIME
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    private String dramaTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_drama.DRAMA_ADDRESS
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    private String dramaAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_drama.DRAMA_INTRO
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    private String dramaIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_drama.CREATE_TIME
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_drama.DRAMA_ID
     *
     * @return the value of ccp_drama.DRAMA_ID
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public String getDramaId() {
        return dramaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_drama.DRAMA_ID
     *
     * @param dramaId the value for ccp_drama.DRAMA_ID
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public void setDramaId(String dramaId) {
        this.dramaId = dramaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_drama.DRAMA_NAME
     *
     * @return the value of ccp_drama.DRAMA_NAME
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public String getDramaName() {
        return dramaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_drama.DRAMA_NAME
     *
     * @param dramaName the value for ccp_drama.DRAMA_NAME
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public void setDramaName(String dramaName) {
        this.dramaName = dramaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_drama.DRAMA_IMG
     *
     * @return the value of ccp_drama.DRAMA_IMG
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public String getDramaImg() {
        return dramaImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_drama.DRAMA_IMG
     *
     * @param dramaImg the value for ccp_drama.DRAMA_IMG
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public void setDramaImg(String dramaImg) {
        this.dramaImg = dramaImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_drama.DRAMA_TAG
     *
     * @return the value of ccp_drama.DRAMA_TAG
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public String getDramaTag() {
        return dramaTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_drama.DRAMA_TAG
     *
     * @param dramaTag the value for ccp_drama.DRAMA_TAG
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public void setDramaTag(String dramaTag) {
        this.dramaTag = dramaTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_drama.DRAMA_TIME
     *
     * @return the value of ccp_drama.DRAMA_TIME
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public String getDramaTime() {
        return dramaTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_drama.DRAMA_TIME
     *
     * @param dramaTime the value for ccp_drama.DRAMA_TIME
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public void setDramaTime(String dramaTime) {
        this.dramaTime = dramaTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_drama.DRAMA_ADDRESS
     *
     * @return the value of ccp_drama.DRAMA_ADDRESS
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public String getDramaAddress() {
        return dramaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_drama.DRAMA_ADDRESS
     *
     * @param dramaAddress the value for ccp_drama.DRAMA_ADDRESS
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public void setDramaAddress(String dramaAddress) {
        this.dramaAddress = dramaAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_drama.DRAMA_INTRO
     *
     * @return the value of ccp_drama.DRAMA_INTRO
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public String getDramaIntro() {
        return dramaIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_drama.DRAMA_INTRO
     *
     * @param dramaIntro the value for ccp_drama.DRAMA_INTRO
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public void setDramaIntro(String dramaIntro) {
        this.dramaIntro = dramaIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_drama.CREATE_TIME
     *
     * @return the value of ccp_drama.CREATE_TIME
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_drama.CREATE_TIME
     *
     * @param createTime the value for ccp_drama.CREATE_TIME
     *
     * @mbggenerated Thu Oct 27 10:55:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}