package com.culturecloud.model.bean.special;

import java.util.Date;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table(value="ccp_special_enter")
public class CcpSpecialEnter implements BaseEntity{

	private static final long serialVersionUID = 2040269343224396502L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_special_enter.enter_id
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	@Id
	@Column(name="enter_id")
	private String enterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_special_enter.enter_name
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	@Column(name="enter_name")
	private String enterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_special_enter.enter_logo_image_url
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	@Column(name="enter_logo_image_url")
	private String enterLogoImageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_special_enter.enter_parame_path
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	@Column(name="enter_parame_path")
	private String enterParamePath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_special_enter.enter_is_del
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	@Column(name="enter_is_del")
	private Integer enterIsDel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_special_enter.project_id
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	@Column(name="project_id")
	private String projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_special_enter.enter_create_time
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	@Column(name="enter_create_time")
	private Date enterCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_special_enter.enter_create_user
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	@Column(name="enter_create_user")
	private String enterCreateUser;
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_special_enter.enter_id
	 * @return  the value of ccp_special_enter.enter_id
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public String getEnterId() {
		return enterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_special_enter.enter_id
	 * @param enterId  the value for ccp_special_enter.enter_id
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public void setEnterId(String enterId) {
		this.enterId = enterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_special_enter.enter_name
	 * @return  the value of ccp_special_enter.enter_name
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public String getEnterName() {
		return enterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_special_enter.enter_name
	 * @param enterName  the value for ccp_special_enter.enter_name
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public void setEnterName(String enterName) {
		this.enterName = enterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_special_enter.enter_logo_image_url
	 * @return  the value of ccp_special_enter.enter_logo_image_url
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public String getEnterLogoImageUrl() {
		return enterLogoImageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_special_enter.enter_logo_image_url
	 * @param enterLogoImageUrl  the value for ccp_special_enter.enter_logo_image_url
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public void setEnterLogoImageUrl(String enterLogoImageUrl) {
		this.enterLogoImageUrl = enterLogoImageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_special_enter.enter_parame_path
	 * @return  the value of ccp_special_enter.enter_parame_path
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public String getEnterParamePath() {
		return enterParamePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_special_enter.enter_parame_path
	 * @param enterParamePath  the value for ccp_special_enter.enter_parame_path
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public void setEnterParamePath(String enterParamePath) {
		this.enterParamePath = enterParamePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_special_enter.enter_is_del
	 * @return  the value of ccp_special_enter.enter_is_del
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public Integer getEnterIsDel() {
		return enterIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_special_enter.enter_is_del
	 * @param enterIsDel  the value for ccp_special_enter.enter_is_del
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public void setEnterIsDel(Integer enterIsDel) {
		this.enterIsDel = enterIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_special_enter.project_id
	 * @return  the value of ccp_special_enter.project_id
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public String getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_special_enter.project_id
	 * @param projectId  the value for ccp_special_enter.project_id
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_special_enter.enter_create_time
	 * @return  the value of ccp_special_enter.enter_create_time
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public Date getEnterCreateTime() {
		return enterCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_special_enter.enter_create_time
	 * @param enterCreateTime  the value for ccp_special_enter.enter_create_time
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public void setEnterCreateTime(Date enterCreateTime) {
		this.enterCreateTime = enterCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_special_enter.enter_create_user
	 * @return  the value of ccp_special_enter.enter_create_user
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public String getEnterCreateUser() {
		return enterCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_special_enter.enter_create_user
	 * @param enterCreateUser  the value for ccp_special_enter.enter_create_user
	 * @mbggenerated  Fri Sep 23 14:42:29 CST 2016
	 */
	public void setEnterCreateUser(String enterCreateUser) {
		this.enterCreateUser = enterCreateUser;
	}

	
	
}