package com.culturecloud.dao.contest;

import java.util.List;

import com.culturecloud.dao.dto.contest.CcpContestTopicQuestionDto;
import com.culturecloud.model.bean.contest.CcpContestTopicQuestion;
import com.culturecloud.model.bean.contest.CcpContestTopicQuestionKey;

public interface CcpContestTopicQuestionMapper {
	
	/**
	 * 查询主题试题总数
	 * 
	 * @param topicId
	 * @return
	 */
	List<CcpContestTopicQuestionDto> queryTopicQuestion(String topicId);
	
	List<CcpContestTopicQuestionDto> queryTopicAllQuestion(String topicId);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_topic_question
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    int deleteByPrimaryKey(CcpContestTopicQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_topic_question
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    int insert(CcpContestTopicQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_topic_question
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    int insertSelective(CcpContestTopicQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_topic_question
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    CcpContestTopicQuestion selectByPrimaryKey(CcpContestTopicQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_topic_question
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    int updateByPrimaryKeySelective(CcpContestTopicQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_topic_question
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    int updateByPrimaryKey(CcpContestTopicQuestion record);
}