package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.contest.CcpContestTopic;
import com.sun3d.why.dao.dto.CcpContestTopicDto;

public interface CcpContestTopicMapper {
	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_contest_topic
	 * @mbggenerated  Thu Jul 07 17:16:03 CST 2016
	 */
	int deleteByPrimaryKey(String topicId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_contest_topic
	 * @mbggenerated  Thu Jul 07 17:16:03 CST 2016
	 */
	int insert(CcpContestTopic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_contest_topic
	 * @mbggenerated  Thu Jul 07 17:16:03 CST 2016
	 */
	int insertSelective(CcpContestTopic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_contest_topic
	 * @mbggenerated  Thu Jul 07 17:16:03 CST 2016
	 */
	CcpContestTopic selectByPrimaryKey(String topicId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_contest_topic
	 * @mbggenerated  Thu Jul 07 17:16:03 CST 2016
	 */
	int updateByPrimaryKeySelective(CcpContestTopic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_contest_topic
	 * @mbggenerated  Thu Jul 07 17:16:03 CST 2016
	 */
	int updateByPrimaryKey(CcpContestTopic record);

	int queryContestTopicCountByCondition(Map<String, Object> map);
	
	List<CcpContestTopicDto> queryCcpContestTopicByCondition(Map<String, Object> map);
	
}