package com.sun3d.why.dao;

import java.util.List;

import com.culturecloud.model.bean.contest.CcpContestAnswer;

public interface CcpContestAnswerMapper {
	
	List<CcpContestAnswer> queryQuestionAnswers(String questionId);
	
	int deleteByQuestionId(String questionId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_answer
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    int deleteByPrimaryKey(String answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_answer
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    int insert(CcpContestAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_answer
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    int insertSelective(CcpContestAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_answer
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    CcpContestAnswer selectByPrimaryKey(String answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_answer
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    int updateByPrimaryKeySelective(CcpContestAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_answer
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    int updateByPrimaryKey(CcpContestAnswer record);
}