package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.drama.CcpDramaComment;
import com.sun3d.why.dao.dto.CcpDramaCommentDto;

public interface CcpDramaCommentMapper {
	
	
	
	int queryDramaCommentCountByCondition(Map<String,Object> map);
	
	List<CcpDramaCommentDto>queryDramaCommentByCondition(Map<String,Object> map);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_drama_comment
     *
     * @mbggenerated Tue Oct 25 23:34:46 CST 2016
     */
    int deleteByPrimaryKey(String dramaCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_drama_comment
     *
     * @mbggenerated Tue Oct 25 23:34:46 CST 2016
     */
    int insert(CcpDramaComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_drama_comment
     *
     * @mbggenerated Tue Oct 25 23:34:46 CST 2016
     */
    int insertSelective(CcpDramaComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_drama_comment
     *
     * @mbggenerated Tue Oct 25 23:34:46 CST 2016
     */
    CcpDramaComment selectByPrimaryKey(String dramaCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_drama_comment
     *
     * @mbggenerated Tue Oct 25 23:34:46 CST 2016
     */
    int updateByPrimaryKeySelective(CcpDramaComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_drama_comment
     *
     * @mbggenerated Tue Oct 25 23:34:46 CST 2016
     */
    int updateByPrimaryKey(CcpDramaComment record);
}