package com.sun3d.why.dao;

import com.culturecloud.model.bean.common.CcpInformationDetail;

import java.util.List;
import java.util.Map;

public interface CcpInformationDetailMapper {
	
	int queryInformationDetailByConditionCount(Map<String, Object> map);

	List<CcpInformationDetail>queryInformationDetailByCondition(Map<String, Object> map);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_detail
     *
     * @mbggenerated Thu Aug 03 14:13:03 CST 2017
     */
    int deleteByPrimaryKey(String informationDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_detail
     *
     * @mbggenerated Thu Aug 03 14:13:03 CST 2017
     */
    int insert(CcpInformationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_detail
     *
     * @mbggenerated Thu Aug 03 14:13:03 CST 2017
     */
    int insertSelective(CcpInformationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_detail
     *
     * @mbggenerated Thu Aug 03 14:13:03 CST 2017
     */
    CcpInformationDetail selectByPrimaryKey(String informationDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_detail
     *
     * @mbggenerated Thu Aug 03 14:13:03 CST 2017
     */
    int updateByPrimaryKeySelective(CcpInformationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_detail
     *
     * @mbggenerated Thu Aug 03 14:13:03 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CcpInformationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_detail
     *
     * @mbggenerated Thu Aug 03 14:13:03 CST 2017
     */
    int updateByPrimaryKey(CcpInformationDetail record);
}