package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.live.CcpLiveMessage;
import com.sun3d.why.dao.dto.CcpLiveMessageDto;

public interface CcpLiveMessageMapper {
	
	int queryLiveMessageCountByCondition(Map<String,Object> map);
	
	List<CcpLiveMessageDto>queryLiveMessageByCondition(Map<String,Object> map);
	
	int setMessageTop(Map<String,Object> map);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_live_message
     *
     * @mbggenerated Wed Oct 19 13:29:59 CST 2016
     */
    int deleteByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_live_message
     *
     * @mbggenerated Wed Oct 19 13:29:59 CST 2016
     */
    int insert(CcpLiveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_live_message
     *
     * @mbggenerated Wed Oct 19 13:29:59 CST 2016
     */
    int insertSelective(CcpLiveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_live_message
     *
     * @mbggenerated Wed Oct 19 13:29:59 CST 2016
     */
    CcpLiveMessage selectByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_live_message
     *
     * @mbggenerated Wed Oct 19 13:29:59 CST 2016
     */
    int updateByPrimaryKeySelective(CcpLiveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_live_message
     *
     * @mbggenerated Wed Oct 19 13:29:59 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(CcpLiveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_live_message
     *
     * @mbggenerated Wed Oct 19 13:29:59 CST 2016
     */
    int updateByPrimaryKey(CcpLiveMessage record);
}