package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.special.CcpSpecialYcode;
import com.sun3d.why.dao.dto.CcpSpecialYcodeDto;

public interface CcpSpecialYcodeMapper {
	
	int queryCodeCountByCondition(Map<String,Object> map );
	
	List<CcpSpecialYcodeDto>queryCodeByCondition(Map<String,Object> map );
	
	int queryCodeCountByYcode(String ycode);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_ycode
     *
     * @mbggenerated Tue Sep 27 23:47:17 CST 2016
     */
    int deleteByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_ycode
     *
     * @mbggenerated Tue Sep 27 23:47:17 CST 2016
     */
    int insert(CcpSpecialYcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_ycode
     *
     * @mbggenerated Tue Sep 27 23:47:17 CST 2016
     */
    int insertSelective(CcpSpecialYcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_ycode
     *
     * @mbggenerated Tue Sep 27 23:47:17 CST 2016
     */
    CcpSpecialYcode selectByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_ycode
     *
     * @mbggenerated Tue Sep 27 23:47:17 CST 2016
     */
    int updateByPrimaryKeySelective(CcpSpecialYcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_ycode
     *
     * @mbggenerated Tue Sep 27 23:47:17 CST 2016
     */
    int updateByPrimaryKey(CcpSpecialYcode record);
}