package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.special.CcpSpecialProject;

public interface CcpSpecialProjectMapper {
	
	
	
	int queryProjectCountByCondition(Map<String,Object> map );
	
	List<CcpSpecialProject>queryProjectByCondition(Map<String,Object> map );
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_project
     *
     * @mbggenerated Wed Sep 21 18:40:37 CST 2016
     */
    int deleteByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_project
     *
     * @mbggenerated Wed Sep 21 18:40:37 CST 2016
     */
    int insert(CcpSpecialProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_project
     *
     * @mbggenerated Wed Sep 21 18:40:37 CST 2016
     */
    int insertSelective(CcpSpecialProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_project
     *
     * @mbggenerated Wed Sep 21 18:40:37 CST 2016
     */
    CcpSpecialProject selectByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_project
     *
     * @mbggenerated Wed Sep 21 18:40:37 CST 2016
     */
    int updateByPrimaryKeySelective(CcpSpecialProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_project
     *
     * @mbggenerated Wed Sep 21 18:40:37 CST 2016
     */
    int updateByPrimaryKey(CcpSpecialProject record);
}