package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.special.CcpSpecialEnter;
import com.sun3d.why.dao.dto.CcpSpecialEnterDto;

public interface CcpSpecialEnterMapper {
	

	int queryEnterCountByCondition(Map<String,Object> map );
	
	List<CcpSpecialEnterDto>queryEnterByCondition(Map<String,Object> map );
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_enter
     *
     * @mbggenerated Fri Sep 23 11:16:07 CST 2016
     */
    int deleteByPrimaryKey(String enterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_enter
     *
     * @mbggenerated Fri Sep 23 11:16:07 CST 2016
     */
    int insert(CcpSpecialEnter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_enter
     *
     * @mbggenerated Fri Sep 23 11:16:07 CST 2016
     */
    int insertSelective(CcpSpecialEnter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_enter
     *
     * @mbggenerated Fri Sep 23 11:16:07 CST 2016
     */
    CcpSpecialEnter selectByPrimaryKey(String enterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_enter
     *
     * @mbggenerated Fri Sep 23 11:16:07 CST 2016
     */
    int updateByPrimaryKeySelective(CcpSpecialEnter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_special_enter
     *
     * @mbggenerated Fri Sep 23 11:16:07 CST 2016
     */
    int updateByPrimaryKey(CcpSpecialEnter record);
}