package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.volunteer.CcpVolunteerRecruit;

public interface CcpVolunteerRecruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_recruit
     *
     * @mbggenerated Thu Aug 25 16:20:40 CST 2016
     */
    int deleteByPrimaryKey(String recruitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_recruit
     *
     * @mbggenerated Thu Aug 25 16:20:40 CST 2016
     */
    int insert(CcpVolunteerRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_recruit
     *
     * @mbggenerated Thu Aug 25 16:20:40 CST 2016
     */
    int insertSelective(CcpVolunteerRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_recruit
     *
     * @mbggenerated Thu Aug 25 16:20:40 CST 2016
     */
    CcpVolunteerRecruit selectByPrimaryKey(String recruitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_recruit
     *
     * @mbggenerated Thu Aug 25 16:20:40 CST 2016
     */
    int updateByPrimaryKeySelective(CcpVolunteerRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_recruit
     *
     * @mbggenerated Thu Aug 25 16:20:40 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(CcpVolunteerRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_recruit
     *
     * @mbggenerated Thu Aug 25 16:20:40 CST 2016
     */
    int updateByPrimaryKey(CcpVolunteerRecruit record);

	int queryVolunteerRecruitByCondition(Map<String, Object> map);

	List<CcpVolunteerRecruit> queryVolunteerRecruitByList(
			Map<String, Object> map);
}