package com.sun3d.why.dao;

import com.culturecloud.model.bean.volunteer.CcpVolunteerApplyPic;

public interface CcpVolunteerApplyPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply_pic
     *
     * @mbggenerated Thu Aug 25 16:22:50 CST 2016
     */
    int deleteByPrimaryKey(String volunteerApplyPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply_pic
     *
     * @mbggenerated Thu Aug 25 16:22:50 CST 2016
     */
    int insert(CcpVolunteerApplyPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply_pic
     *
     * @mbggenerated Thu Aug 25 16:22:50 CST 2016
     */
    int insertSelective(CcpVolunteerApplyPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply_pic
     *
     * @mbggenerated Thu Aug 25 16:22:50 CST 2016
     */
    CcpVolunteerApplyPic selectByPrimaryKey(String volunteerApplyPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply_pic
     *
     * @mbggenerated Thu Aug 25 16:22:50 CST 2016
     */
    int updateByPrimaryKeySelective(CcpVolunteerApplyPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply_pic
     *
     * @mbggenerated Thu Aug 25 16:22:50 CST 2016
     */
    int updateByPrimaryKey(CcpVolunteerApplyPic record);
}