package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.volunteer.CcpVolunteerApply;
import com.sun3d.why.dao.dto.CcpVolunteerApplyDto;

public interface CcpVolunteerApplyMapper {
	
	List<CcpVolunteerApplyDto> queryCcpVolunteerApplyByMap(Map<String,Object>data);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply
     *
     * @mbggenerated Thu Aug 25 16:22:11 CST 2016
     */
    int deleteByPrimaryKey(String volunteerApplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply
     *
     * @mbggenerated Thu Aug 25 16:22:11 CST 2016
     */
    int insert(CcpVolunteerApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply
     *
     * @mbggenerated Thu Aug 25 16:22:11 CST 2016
     */
    int insertSelective(CcpVolunteerApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply
     *
     * @mbggenerated Thu Aug 25 16:22:11 CST 2016
     */
    CcpVolunteerApply selectByPrimaryKey(String volunteerApplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply
     *
     * @mbggenerated Thu Aug 25 16:22:11 CST 2016
     */
    int updateByPrimaryKeySelective(CcpVolunteerApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_volunteer_apply
     *
     * @mbggenerated Thu Aug 25 16:22:11 CST 2016
     */
    int updateByPrimaryKey(CcpVolunteerApply record);
}