package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.ticketmachine.TicketMachineHeart;
import com.sun3d.why.dao.dto.TicketMachineHeartDto;

public interface TicketMachineHeartMapper {
	
	int searchTicketMachineHeartCount(Map<String,Object>map);
	
	List<TicketMachineHeartDto> searchTicketMachineHeartList(Map<String,Object>map);
	
	List<TicketMachineHeartDto> getAllTicketMachine();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_heart
	 * @mbggenerated  Sun Oct 09 14:22:32 CST 2016
	 */
	int deleteByPrimaryKey(String machineId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_heart
	 * @mbggenerated  Sun Oct 09 14:22:32 CST 2016
	 */
	int insert(TicketMachineHeart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_heart
	 * @mbggenerated  Sun Oct 09 14:22:32 CST 2016
	 */
	int insertSelective(TicketMachineHeart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_heart
	 * @mbggenerated  Sun Oct 09 14:22:32 CST 2016
	 */
	TicketMachineHeart selectByPrimaryKey(String machineId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_heart
	 * @mbggenerated  Sun Oct 09 14:22:32 CST 2016
	 */
	int updateByPrimaryKeySelective(TicketMachineHeart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_heart
	 * @mbggenerated  Sun Oct 09 14:22:32 CST 2016
	 */
	int updateByPrimaryKey(TicketMachineHeart record);
}