package com.sun3d.why.dao.ccp;

import com.culturecloud.model.bean.musicessay.CcpMusicessayLike;
import org.apache.ibatis.annotations.Param;
import java.util.Date;

public interface CcpMusicessayLikeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_musicessay_like
	 * @mbggenerated  Sat Apr 29 10:31:33 CST 2017
	 */
	int deleteByPrimaryKey(@Param("articleId") String articleId, @Param("createDate") Date createDate,
			@Param("userId") String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_musicessay_like
	 * @mbggenerated  Sat Apr 29 10:31:33 CST 2017
	 */
	int insert(CcpMusicessayLike record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_musicessay_like
	 * @mbggenerated  Sat Apr 29 10:31:33 CST 2017
	 */
	int insertSelective(CcpMusicessayLike record);
}