package com.culturecloud.model.bean.room;

import java.util.Date;

public class CmsRoomOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order_detail.ORDER_DETAIL_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    private String orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order_detail.ROOM_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    private String roomOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order_detail.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    private String venueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order_detail.ROOM_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    private String roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order_detail.BOOK_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order_detail.BOOK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    private Integer bookStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order_detail.BOOK_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    private Date bookUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order_detail.BOOK_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    private String bookUpdateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order_detail.ORDER_DETAIL_ID
     *
     * @return the value of cms_room_order_detail.ORDER_DETAIL_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public String getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order_detail.ORDER_DETAIL_ID
     *
     * @param orderDetailId the value for cms_room_order_detail.ORDER_DETAIL_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public void setOrderDetailId(String orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order_detail.ROOM_ORDER_ID
     *
     * @return the value of cms_room_order_detail.ROOM_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public String getRoomOrderId() {
        return roomOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order_detail.ROOM_ORDER_ID
     *
     * @param roomOrderId the value for cms_room_order_detail.ROOM_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public void setRoomOrderId(String roomOrderId) {
        this.roomOrderId = roomOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order_detail.VENUE_ID
     *
     * @return the value of cms_room_order_detail.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public String getVenueId() {
        return venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order_detail.VENUE_ID
     *
     * @param venueId the value for cms_room_order_detail.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public void setVenueId(String venueId) {
        this.venueId = venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order_detail.ROOM_ID
     *
     * @return the value of cms_room_order_detail.ROOM_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order_detail.ROOM_ID
     *
     * @param roomId the value for cms_room_order_detail.ROOM_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order_detail.BOOK_ID
     *
     * @return the value of cms_room_order_detail.BOOK_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order_detail.BOOK_ID
     *
     * @param bookId the value for cms_room_order_detail.BOOK_ID
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order_detail.BOOK_STATUS
     *
     * @return the value of cms_room_order_detail.BOOK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public Integer getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order_detail.BOOK_STATUS
     *
     * @param bookStatus the value for cms_room_order_detail.BOOK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public void setBookStatus(Integer bookStatus) {
        this.bookStatus = bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order_detail.BOOK_UPDATE_TIME
     *
     * @return the value of cms_room_order_detail.BOOK_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public Date getBookUpdateTime() {
        return bookUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order_detail.BOOK_UPDATE_TIME
     *
     * @param bookUpdateTime the value for cms_room_order_detail.BOOK_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public void setBookUpdateTime(Date bookUpdateTime) {
        this.bookUpdateTime = bookUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order_detail.BOOK_UPDATE_USER
     *
     * @return the value of cms_room_order_detail.BOOK_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public String getBookUpdateUser() {
        return bookUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order_detail.BOOK_UPDATE_USER
     *
     * @param bookUpdateUser the value for cms_room_order_detail.BOOK_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:28:24 CST 2016
     */
    public void setBookUpdateUser(String bookUpdateUser) {
        this.bookUpdateUser = bookUpdateUser;
    }
}