package com.culturecloud.model.bean.room;

import java.util.Date;

public class CmsRoomOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.ROOM_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String roomOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.USER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.USER_NAME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.USER_TEL
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.TUSER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String tuserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.ORDER_NO
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String venueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.ROOM_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.BOOK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private Integer bookStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.BOOK_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.VALID_CODE
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String validCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.ORDER_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private Date orderCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.ORDER_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private Date orderUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.ORDER_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String orderUpdateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.SYS_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.SYS_NO
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String sysNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.PRINT_TICKET_TIMES
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private Integer printTicketTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.SYS_USER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.PURPOSE
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.CHECK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private Integer checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_order.TUSER_NAME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    private String tuserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.ROOM_ORDER_ID
     *
     * @return the value of cms_room_order.ROOM_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getRoomOrderId() {
        return roomOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.ROOM_ORDER_ID
     *
     * @param roomOrderId the value for cms_room_order.ROOM_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setRoomOrderId(String roomOrderId) {
        this.roomOrderId = roomOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.USER_ID
     *
     * @return the value of cms_room_order.USER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.USER_ID
     *
     * @param userId the value for cms_room_order.USER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.USER_NAME
     *
     * @return the value of cms_room_order.USER_NAME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.USER_NAME
     *
     * @param userName the value for cms_room_order.USER_NAME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.USER_TEL
     *
     * @return the value of cms_room_order.USER_TEL
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.USER_TEL
     *
     * @param userTel the value for cms_room_order.USER_TEL
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.TUSER_ID
     *
     * @return the value of cms_room_order.TUSER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getTuserId() {
        return tuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.TUSER_ID
     *
     * @param tuserId the value for cms_room_order.TUSER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setTuserId(String tuserId) {
        this.tuserId = tuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.ORDER_NO
     *
     * @return the value of cms_room_order.ORDER_NO
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.ORDER_NO
     *
     * @param orderNo the value for cms_room_order.ORDER_NO
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.VENUE_ID
     *
     * @return the value of cms_room_order.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getVenueId() {
        return venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.VENUE_ID
     *
     * @param venueId the value for cms_room_order.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setVenueId(String venueId) {
        this.venueId = venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.ROOM_ID
     *
     * @return the value of cms_room_order.ROOM_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.ROOM_ID
     *
     * @param roomId the value for cms_room_order.ROOM_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.BOOK_STATUS
     *
     * @return the value of cms_room_order.BOOK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public Integer getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.BOOK_STATUS
     *
     * @param bookStatus the value for cms_room_order.BOOK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setBookStatus(Integer bookStatus) {
        this.bookStatus = bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.BOOK_ID
     *
     * @return the value of cms_room_order.BOOK_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.BOOK_ID
     *
     * @param bookId the value for cms_room_order.BOOK_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.VALID_CODE
     *
     * @return the value of cms_room_order.VALID_CODE
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getValidCode() {
        return validCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.VALID_CODE
     *
     * @param validCode the value for cms_room_order.VALID_CODE
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setValidCode(String validCode) {
        this.validCode = validCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.ORDER_CREATE_TIME
     *
     * @return the value of cms_room_order.ORDER_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public Date getOrderCreateTime() {
        return orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.ORDER_CREATE_TIME
     *
     * @param orderCreateTime the value for cms_room_order.ORDER_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setOrderCreateTime(Date orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.ORDER_UPDATE_TIME
     *
     * @return the value of cms_room_order.ORDER_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public Date getOrderUpdateTime() {
        return orderUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.ORDER_UPDATE_TIME
     *
     * @param orderUpdateTime the value for cms_room_order.ORDER_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setOrderUpdateTime(Date orderUpdateTime) {
        this.orderUpdateTime = orderUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.ORDER_UPDATE_USER
     *
     * @return the value of cms_room_order.ORDER_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getOrderUpdateUser() {
        return orderUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.ORDER_UPDATE_USER
     *
     * @param orderUpdateUser the value for cms_room_order.ORDER_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setOrderUpdateUser(String orderUpdateUser) {
        this.orderUpdateUser = orderUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.SYS_ID
     *
     * @return the value of cms_room_order.SYS_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.SYS_ID
     *
     * @param sysId the value for cms_room_order.SYS_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.SYS_NO
     *
     * @return the value of cms_room_order.SYS_NO
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getSysNo() {
        return sysNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.SYS_NO
     *
     * @param sysNo the value for cms_room_order.SYS_NO
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setSysNo(String sysNo) {
        this.sysNo = sysNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.PRINT_TICKET_TIMES
     *
     * @return the value of cms_room_order.PRINT_TICKET_TIMES
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public Integer getPrintTicketTimes() {
        return printTicketTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.PRINT_TICKET_TIMES
     *
     * @param printTicketTimes the value for cms_room_order.PRINT_TICKET_TIMES
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setPrintTicketTimes(Integer printTicketTimes) {
        this.printTicketTimes = printTicketTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.SYS_USER_ID
     *
     * @return the value of cms_room_order.SYS_USER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.SYS_USER_ID
     *
     * @param sysUserId the value for cms_room_order.SYS_USER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.PURPOSE
     *
     * @return the value of cms_room_order.PURPOSE
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.PURPOSE
     *
     * @param purpose the value for cms_room_order.PURPOSE
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.CHECK_STATUS
     *
     * @return the value of cms_room_order.CHECK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public Integer getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.CHECK_STATUS
     *
     * @param checkStatus the value for cms_room_order.CHECK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_order.TUSER_NAME
     *
     * @return the value of cms_room_order.TUSER_NAME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public String getTuserName() {
        return tuserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_order.TUSER_NAME
     *
     * @param tuserName the value for cms_room_order.TUSER_NAME
     *
     * @mbggenerated Mon Jul 25 16:26:42 CST 2016
     */
    public void setTuserName(String tuserName) {
        this.tuserName = tuserName;
    }
}