package com.culturecloud.model.bean.room;

import java.util.Date;

public class CmsRoomBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.BOOK_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private String bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.CUR_DATE
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private Date curDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.OPEN_PERIOD
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private String openPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.TIME_SORT
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private Integer timeSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.DAY_OF_WEEK
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private Integer dayOfWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.BOOK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private Integer bookStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.TUSER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private String tuserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.USER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.USER_NAME
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.USER_TEL
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.ROOM_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private String roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.SYS_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private String sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_room_book.SYS_NO
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    private String sysNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.BOOK_ID
     *
     * @return the value of cms_room_book.BOOK_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.BOOK_ID
     *
     * @param bookId the value for cms_room_book.BOOK_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.CUR_DATE
     *
     * @return the value of cms_room_book.CUR_DATE
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public Date getCurDate() {
        return curDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.CUR_DATE
     *
     * @param curDate the value for cms_room_book.CUR_DATE
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setCurDate(Date curDate) {
        this.curDate = curDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.OPEN_PERIOD
     *
     * @return the value of cms_room_book.OPEN_PERIOD
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public String getOpenPeriod() {
        return openPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.OPEN_PERIOD
     *
     * @param openPeriod the value for cms_room_book.OPEN_PERIOD
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setOpenPeriod(String openPeriod) {
        this.openPeriod = openPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.TIME_SORT
     *
     * @return the value of cms_room_book.TIME_SORT
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public Integer getTimeSort() {
        return timeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.TIME_SORT
     *
     * @param timeSort the value for cms_room_book.TIME_SORT
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setTimeSort(Integer timeSort) {
        this.timeSort = timeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.DAY_OF_WEEK
     *
     * @return the value of cms_room_book.DAY_OF_WEEK
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public Integer getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.DAY_OF_WEEK
     *
     * @param dayOfWeek the value for cms_room_book.DAY_OF_WEEK
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setDayOfWeek(Integer dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.BOOK_STATUS
     *
     * @return the value of cms_room_book.BOOK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public Integer getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.BOOK_STATUS
     *
     * @param bookStatus the value for cms_room_book.BOOK_STATUS
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setBookStatus(Integer bookStatus) {
        this.bookStatus = bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.TUSER_ID
     *
     * @return the value of cms_room_book.TUSER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public String getTuserId() {
        return tuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.TUSER_ID
     *
     * @param tuserId the value for cms_room_book.TUSER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setTuserId(String tuserId) {
        this.tuserId = tuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.USER_ID
     *
     * @return the value of cms_room_book.USER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.USER_ID
     *
     * @param userId the value for cms_room_book.USER_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.USER_NAME
     *
     * @return the value of cms_room_book.USER_NAME
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.USER_NAME
     *
     * @param userName the value for cms_room_book.USER_NAME
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.USER_TEL
     *
     * @return the value of cms_room_book.USER_TEL
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.USER_TEL
     *
     * @param userTel the value for cms_room_book.USER_TEL
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.CREATE_TIME
     *
     * @return the value of cms_room_book.CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.CREATE_TIME
     *
     * @param createTime the value for cms_room_book.CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.UPDATE_TIME
     *
     * @return the value of cms_room_book.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.UPDATE_TIME
     *
     * @param updateTime the value for cms_room_book.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.ROOM_ID
     *
     * @return the value of cms_room_book.ROOM_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.ROOM_ID
     *
     * @param roomId the value for cms_room_book.ROOM_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.SYS_ID
     *
     * @return the value of cms_room_book.SYS_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.SYS_ID
     *
     * @param sysId the value for cms_room_book.SYS_ID
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_room_book.SYS_NO
     *
     * @return the value of cms_room_book.SYS_NO
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public String getSysNo() {
        return sysNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_room_book.SYS_NO
     *
     * @param sysNo the value for cms_room_book.SYS_NO
     *
     * @mbggenerated Mon Jul 25 16:26:19 CST 2016
     */
    public void setSysNo(String sysNo) {
        this.sysNo = sysNo;
    }
}