package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.contest.CcpContestTemplate;
import com.sun3d.why.dao.dto.CcpContestTemplateDto;

public interface CcpContestTemplateMapper {
	
	// 选择模板
	List<CcpContestTemplateDto> selectTemplate(Map<String,Object> map);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_template
     *
     * @mbggenerated Fri Oct 28 14:31:08 CST 2016
     */
    int deleteByPrimaryKey(String templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_template
     *
     * @mbggenerated Fri Oct 28 14:31:08 CST 2016
     */
    int insert(CcpContestTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_template
     *
     * @mbggenerated Fri Oct 28 14:31:08 CST 2016
     */
    int insertSelective(CcpContestTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_template
     *
     * @mbggenerated Fri Oct 28 14:31:08 CST 2016
     */
    CcpContestTemplate selectByPrimaryKey(String templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_template
     *
     * @mbggenerated Fri Oct 28 14:31:08 CST 2016
     */
    int updateByPrimaryKeySelective(CcpContestTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_contest_template
     *
     * @mbggenerated Fri Oct 28 14:31:08 CST 2016
     */
    int updateByPrimaryKey(CcpContestTemplate record);
}