package com.sun3d.why.dao;

import com.culturecloud.model.bean.culture.CcpCultureContestOption;

public interface CcpCultureContestOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_option
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    int deleteByPrimaryKey(String cultureOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_option
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    int insert(CcpCultureContestOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_option
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    int insertSelective(CcpCultureContestOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_option
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    CcpCultureContestOption selectByPrimaryKey(String cultureOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_option
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    int updateByPrimaryKeySelective(CcpCultureContestOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_option
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    int updateByPrimaryKey(CcpCultureContestOption record);
}