package com.sun3d.why.dao;

import java.util.List;

import com.culturecloud.model.bean.culture.CcpCultureContestQuestion;
import com.sun3d.why.dao.dto.CcpCultureContestQuestionDto;

public interface CcpCultureContestQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_question
     *
     * @mbggenerated Wed May 17 16:23:35 CST 2017
     */
    int deleteByPrimaryKey(Integer cultureQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_question
     *
     * @mbggenerated Wed May 17 16:23:35 CST 2017
     */
    int insert(CcpCultureContestQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_question
     *
     * @mbggenerated Wed May 17 16:23:35 CST 2017
     */
    int insertSelective(CcpCultureContestQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_question
     *
     * @mbggenerated Wed May 17 16:23:35 CST 2017
     */
    CcpCultureContestQuestion selectByPrimaryKey(Integer cultureQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_question
     *
     * @mbggenerated Wed May 17 16:23:35 CST 2017
     */
    int updateByPrimaryKeySelective(CcpCultureContestQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_culture_contest_question
     *
     * @mbggenerated Wed May 17 16:23:35 CST 2017
     */
    int updateByPrimaryKey(CcpCultureContestQuestion record);
    
    List<CcpCultureContestQuestionDto> queryStageQuestion(Integer stageNumber);
    
}