package com.sun3d.why.dao;

import com.culturecloud.model.bean.common.CcpInformationType;

import java.util.List;
import java.util.Map;

public interface CcpInformationTypeMapper {
	
	List<CcpInformationType> queryInformationTypeByCondition(Map<String, Object> map);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_type
     *
     * @mbggenerated Thu Aug 03 20:16:24 CST 2017
     */
    int deleteByPrimaryKey(String informationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_type
     *
     * @mbggenerated Thu Aug 03 20:16:24 CST 2017
     */
    int insert(CcpInformationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_type
     *
     * @mbggenerated Thu Aug 03 20:16:24 CST 2017
     */
    int insertSelective(CcpInformationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_type
     *
     * @mbggenerated Thu Aug 03 20:16:24 CST 2017
     */
    CcpInformationType selectByPrimaryKey(String informationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_type
     *
     * @mbggenerated Thu Aug 03 20:16:24 CST 2017
     */
    int updateByPrimaryKeySelective(CcpInformationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_information_type
     *
     * @mbggenerated Thu Aug 03 20:16:24 CST 2017
     */
    int updateByPrimaryKey(CcpInformationType record);
}