package com.sun3d.why.dao;

import com.culturecloud.model.bean.common.CcpInformation;
import com.sun3d.why.dao.dto.CcpInformationDto;
import com.sun3d.why.dao.dto.CcpInformationDto1;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CcpInformationMapper {
	
	List<CcpInformationDto1> queryInformationByCondition(Map<String, Object> map);

	CcpInformationDto queryInformationDetail(@Param("informationId") String informationId, @Param("userId") String userId);

	CcpInformationDto queryInformationUserInfo(@Param("informationId") String informationId, @Param("userId") String userId);

	List<String> queryInformationByConditionCount(Map<String, Object> map);

	CcpInformationDto queryInformationByConditionWithDetail(Map<String, Object> map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_information
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	int deleteByPrimaryKey(String informationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_information
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	int insert(CcpInformation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_information
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	int insertSelective(CcpInformation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_information
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	CcpInformation selectByPrimaryKey(String informationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_information
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	int updateByPrimaryKeySelective(CcpInformation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_information
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(CcpInformation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_information
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	int updateByPrimaryKey(CcpInformation record);

    CcpInformation queryInformationById(String advertUrl);

	List<CcpInformation> pcnewInfo(Map map);

    List<CcpInformationDto> queryExsitingInformationList(CcpInformation information1);
}