package com.sun3d.why.dao;

import com.sun3d.why.model.CmsTagSubRelevance;

public interface CmsTagSubRelevanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag_sub_relevance
     *
     * @mbggenerated Wed Aug 03 16:22:02 CST 2016
     */
    int insert(CmsTagSubRelevance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag_sub_relevance
     *
     * @mbggenerated Wed Aug 03 16:22:02 CST 2016
     */
    int insertSelective(CmsTagSubRelevance record);
    
    int deleteSelective(CmsTagSubRelevance record);
    
    int deleteCommonTag(Integer type);
}