package com.culturecloud.dao.ticketmachine;

import com.culturecloud.model.bean.ticketmachine.TicketMachineVenue;
import org.apache.ibatis.annotations.Param;

public interface TicketMachineVenueMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_venue
	 * @mbggenerated  Mon Jan 09 16:36:10 CST 2017
	 */
	int deleteByPrimaryKey(@Param("machineCode") String machineCode, @Param("venueId") String venueId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_venue
	 * @mbggenerated  Mon Jan 09 16:36:10 CST 2017
	 */
	int insert(TicketMachineVenue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_venue
	 * @mbggenerated  Mon Jan 09 16:36:10 CST 2017
	 */
	int insertSelective(TicketMachineVenue record);
}