package com.culturecloud.model.bean.live;

import java.util.Date;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table(value = "ccp_live_message")
public class CcpLiveMessage implements BaseEntity {
	
	private static final long serialVersionUID = -4126248963230864788L;

	@Id
	@Column(name = "message_id")
	private String messageId;

	@Column(name = "message_content")
	private String messageContent;

	@Column(name = "message_create_user")
	private String messageCreateUser;

	@Column(name = "message_create_time")
	private Date messageCreateTime;

	@Column(name = "message_update_time")
	private Date messageUpdateTime;

	@Column(name = "message_activity")
	private String messageActivity;

	/**
	 * 直播信息是否置顶0.不置顶 1.置顶
	 */
	@Column(name = "message_is_top")
	private Integer messageIsTop;

	/**
	 * 是否删除 1：未删除2：删除
	 */
	@Column(name = "message_is_del")
	private Integer messageIsDel;

	@Column(name = "message_video")
	private String messageVideo;

	@Column(name = "message_img")
	private String messageImg;

	/**
	 * 是否是互动直播信息 0.否 1.是
	 */
	@Column(name = "message_is_interaction")
	private Integer messageIsInteraction;

	/**
	 * 互动信息是否推荐 0.否 1.是
	 */
	@Column(name = "message_is_recommend")
	private Integer messageIsRecommend;

	@Column(name = "message_recommend_time")
	private Date messageRecommendTime;

	@Column(name = "sort_time")
	private Long sortTime;

	@Column(name = "message_video_img")
	private String messageVideoImg;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_id
	 * @return  the value of ccp_live_message.message_id
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public String getMessageId() {
		return messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_id
	 * @param messageId  the value for ccp_live_message.message_id
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_content
	 * @return  the value of ccp_live_message.message_content
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public String getMessageContent() {
		return messageContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_content
	 * @param messageContent  the value for ccp_live_message.message_content
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_create_user
	 * @return  the value of ccp_live_message.message_create_user
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public String getMessageCreateUser() {
		return messageCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_create_user
	 * @param messageCreateUser  the value for ccp_live_message.message_create_user
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageCreateUser(String messageCreateUser) {
		this.messageCreateUser = messageCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_create_time
	 * @return  the value of ccp_live_message.message_create_time
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public Date getMessageCreateTime() {
		return messageCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_create_time
	 * @param messageCreateTime  the value for ccp_live_message.message_create_time
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageCreateTime(Date messageCreateTime) {
		this.messageCreateTime = messageCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_update_time
	 * @return  the value of ccp_live_message.message_update_time
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public Date getMessageUpdateTime() {
		return messageUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_update_time
	 * @param messageUpdateTime  the value for ccp_live_message.message_update_time
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageUpdateTime(Date messageUpdateTime) {
		this.messageUpdateTime = messageUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_activity
	 * @return  the value of ccp_live_message.message_activity
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public String getMessageActivity() {
		return messageActivity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_activity
	 * @param messageActivity  the value for ccp_live_message.message_activity
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageActivity(String messageActivity) {
		this.messageActivity = messageActivity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_is_top
	 * @return  the value of ccp_live_message.message_is_top
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public Integer getMessageIsTop() {
		return messageIsTop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_is_top
	 * @param messageIsTop  the value for ccp_live_message.message_is_top
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageIsTop(Integer messageIsTop) {
		this.messageIsTop = messageIsTop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_is_del
	 * @return  the value of ccp_live_message.message_is_del
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public Integer getMessageIsDel() {
		return messageIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_is_del
	 * @param messageIsDel  the value for ccp_live_message.message_is_del
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageIsDel(Integer messageIsDel) {
		this.messageIsDel = messageIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_is_interaction
	 * @return  the value of ccp_live_message.message_is_interaction
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public Integer getMessageIsInteraction() {
		return messageIsInteraction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_is_interaction
	 * @param messageIsInteraction  the value for ccp_live_message.message_is_interaction
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageIsInteraction(Integer messageIsInteraction) {
		this.messageIsInteraction = messageIsInteraction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_is_recommend
	 * @return  the value of ccp_live_message.message_is_recommend
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public Integer getMessageIsRecommend() {
		return messageIsRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_is_recommend
	 * @param messageIsRecommend  the value for ccp_live_message.message_is_recommend
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageIsRecommend(Integer messageIsRecommend) {
		this.messageIsRecommend = messageIsRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_recommend_time
	 * @return  the value of ccp_live_message.message_recommend_time
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public Date getMessageRecommendTime() {
		return messageRecommendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_recommend_time
	 * @param messageRecommendTime  the value for ccp_live_message.message_recommend_time
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageRecommendTime(Date messageRecommendTime) {
		this.messageRecommendTime = messageRecommendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.sort_time
	 * @return  the value of ccp_live_message.sort_time
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public Long getSortTime() {
		return sortTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.sort_time
	 * @param sortTime  the value for ccp_live_message.sort_time
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setSortTime(Long sortTime) {
		this.sortTime = sortTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_img
	 * @return  the value of ccp_live_message.message_img
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public String getMessageImg() {
		return messageImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_img
	 * @param messageImg  the value for ccp_live_message.message_img
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageImg(String messageImg) {
		this.messageImg = messageImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_message.message_video
	 * @return  the value of ccp_live_message.message_video
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public String getMessageVideo() {
		return messageVideo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_message.message_video
	 * @param messageVideo  the value for ccp_live_message.message_video
	 * @mbggenerated  Mon Jan 16 21:23:20 CST 2017
	 */
	public void setMessageVideo(String messageVideo) {
		this.messageVideo = messageVideo;
	}

	public String getMessageVideoImg() {
		return messageVideoImg;
	}

	public void setMessageVideoImg(String messageVideoImg) {
		this.messageVideoImg = messageVideoImg;
	}

	
}