package com.culturecloud.model.bean.live;

import java.util.Date;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table(value = "ccp_live_activity")
public class CcpLiveActivity implements BaseEntity {


	private static final long serialVersionUID = -2357019864088755228L;

	@Column(name = "live_activity_id")
	@Id
	private String liveActivityId;

	@Column(name = "live_title")
	private String liveTitle;

	@Column(name = "live_cover_img")
	private String liveCoverImg;

	@Column(name = "live_start_time")
	private Date liveStartTime;

	@Column(name = "live_create_time")
	private Date liveCreateTime;

	@Column(name = "live_create_user")
	private String liveCreateUser;

	@Column(name = "live_status")
	private Integer liveStatus;

	@Column(name = "live_top_text")
	private String liveTopText;

	@Column(name="live_is_del")
	private Integer liveIsDel;

	@Column(name="live_end_time")
	private Date liveEndTime;
	
	@Column(name="live_type")
	private Integer liveType;
	
	@Column(name="live_check")
	private Integer liveCheck;
	
	@Column(name="live_check_time")
	private Date liveCheckTime;

	@Column(name="live_watermark_text")
	private String liveWatermarkText;

	@Column(name="live_watermark_img")
	private String liveWatermarkImg;

	@Column(name="live_watermark_img_position")
	private Integer liveWatermarkImgPosition;

	@Column(name="live_backgroud_music")
	private String liveBackgroudMusic;
	
	@Column(name="live_backgroud_cover")
	private String liveBackgroudCover;

	@Column(name="live_hot")
	private Integer liveHot;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_activity_id
	 * @return  the value of ccp_live_activity.live_activity_id
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public String getLiveActivityId() {
		return liveActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_activity_id
	 * @param liveActivityId  the value for ccp_live_activity.live_activity_id
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveActivityId(String liveActivityId) {
		this.liveActivityId = liveActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_title
	 * @return  the value of ccp_live_activity.live_title
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public String getLiveTitle() {
		return liveTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_title
	 * @param liveTitle  the value for ccp_live_activity.live_title
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveTitle(String liveTitle) {
		this.liveTitle = liveTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_top_text
	 * @return  the value of ccp_live_activity.live_top_text
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public String getLiveTopText() {
		return liveTopText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_top_text
	 * @param liveTopText  the value for ccp_live_activity.live_top_text
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveTopText(String liveTopText) {
		this.liveTopText = liveTopText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_cover_img
	 * @return  the value of ccp_live_activity.live_cover_img
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public String getLiveCoverImg() {
		return liveCoverImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_cover_img
	 * @param liveCoverImg  the value for ccp_live_activity.live_cover_img
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveCoverImg(String liveCoverImg) {
		this.liveCoverImg = liveCoverImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_start_time
	 * @return  the value of ccp_live_activity.live_start_time
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Date getLiveStartTime() {
		return liveStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_start_time
	 * @param liveStartTime  the value for ccp_live_activity.live_start_time
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveStartTime(Date liveStartTime) {
		this.liveStartTime = liveStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_create_time
	 * @return  the value of ccp_live_activity.live_create_time
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Date getLiveCreateTime() {
		return liveCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_create_time
	 * @param liveCreateTime  the value for ccp_live_activity.live_create_time
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveCreateTime(Date liveCreateTime) {
		this.liveCreateTime = liveCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_create_user
	 * @return  the value of ccp_live_activity.live_create_user
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public String getLiveCreateUser() {
		return liveCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_create_user
	 * @param liveCreateUser  the value for ccp_live_activity.live_create_user
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveCreateUser(String liveCreateUser) {
		this.liveCreateUser = liveCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_status
	 * @return  the value of ccp_live_activity.live_status
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Integer getLiveStatus() {
		return liveStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_status
	 * @param liveStatus  the value for ccp_live_activity.live_status
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveStatus(Integer liveStatus) {
		this.liveStatus = liveStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_is_del
	 * @return  the value of ccp_live_activity.live_is_del
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Integer getLiveIsDel() {
		return liveIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_is_del
	 * @param liveIsDel  the value for ccp_live_activity.live_is_del
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveIsDel(Integer liveIsDel) {
		this.liveIsDel = liveIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_end_time
	 * @return  the value of ccp_live_activity.live_end_time
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Date getLiveEndTime() {
		return liveEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_end_time
	 * @param liveEndTime  the value for ccp_live_activity.live_end_time
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveEndTime(Date liveEndTime) {
		this.liveEndTime = liveEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_type
	 * @return  the value of ccp_live_activity.live_type
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Integer getLiveType() {
		return liveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_type
	 * @param liveType  the value for ccp_live_activity.live_type
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveType(Integer liveType) {
		this.liveType = liveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_check
	 * @return  the value of ccp_live_activity.live_check
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Integer getLiveCheck() {
		return liveCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_check
	 * @param liveCheck  the value for ccp_live_activity.live_check
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveCheck(Integer liveCheck) {
		this.liveCheck = liveCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_check_time
	 * @return  the value of ccp_live_activity.live_check_time
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Date getLiveCheckTime() {
		return liveCheckTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_check_time
	 * @param liveCheckTime  the value for ccp_live_activity.live_check_time
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveCheckTime(Date liveCheckTime) {
		this.liveCheckTime = liveCheckTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_watermark_text
	 * @return  the value of ccp_live_activity.live_watermark_text
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public String getLiveWatermarkText() {
		return liveWatermarkText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_watermark_text
	 * @param liveWatermarkText  the value for ccp_live_activity.live_watermark_text
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveWatermarkText(String liveWatermarkText) {
		this.liveWatermarkText = liveWatermarkText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_watermark_img
	 * @return  the value of ccp_live_activity.live_watermark_img
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public String getLiveWatermarkImg() {
		return liveWatermarkImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_watermark_img
	 * @param liveWatermarkImg  the value for ccp_live_activity.live_watermark_img
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveWatermarkImg(String liveWatermarkImg) {
		this.liveWatermarkImg = liveWatermarkImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_watermark_img_position
	 * @return  the value of ccp_live_activity.live_watermark_img_position
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Integer getLiveWatermarkImgPosition() {
		return liveWatermarkImgPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_watermark_img_position
	 * @param liveWatermarkImgPosition  the value for ccp_live_activity.live_watermark_img_position
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveWatermarkImgPosition(Integer liveWatermarkImgPosition) {
		this.liveWatermarkImgPosition = liveWatermarkImgPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_backgroud_music
	 * @return  the value of ccp_live_activity.live_backgroud_music
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public String getLiveBackgroudMusic() {
		return liveBackgroudMusic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_backgroud_music
	 * @param liveBackgroudMusic  the value for ccp_live_activity.live_backgroud_music
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveBackgroudMusic(String liveBackgroudMusic) {
		this.liveBackgroudMusic = liveBackgroudMusic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_backgroud_cover
	 * @return  the value of ccp_live_activity.live_backgroud_cover
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public String getLiveBackgroudCover() {
		return liveBackgroudCover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_backgroud_cover
	 * @param liveBackgroudCover  the value for ccp_live_activity.live_backgroud_cover
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveBackgroudCover(String liveBackgroudCover) {
		this.liveBackgroudCover = liveBackgroudCover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_live_activity.live_hot
	 * @return  the value of ccp_live_activity.live_hot
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public Integer getLiveHot() {
		return liveHot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_live_activity.live_hot
	 * @param liveHot  the value for ccp_live_activity.live_hot
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	public void setLiveHot(Integer liveHot) {
		this.liveHot = liveHot;
	}

}