package com.culturecloud.dao.common;

import java.util.List;

import com.culturecloud.dao.dto.common.OrderByPhoneDto;
import com.culturecloud.model.bean.common.CmsTagSubRelate;

public interface CmsTagSubRelateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag_sub_relate
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    int insert(CmsTagSubRelate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_tag_sub_relate
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    int insertSelective(CmsTagSubRelate record);
    
    List<OrderByPhoneDto> queryOrderTagSubList(String phoneNo,String subId);
}