package com.culturecloud.dao.common;

import com.culturecloud.dao.dto.common.SysUserIntegralDto;
import com.culturecloud.model.bean.common.SysUserIntegral;

public interface SysUserIntegralMapper {
	
	/** 根据用户id获取用户积分相关数据*/
	SysUserIntegralDto selectUserIntegralByUserId(String userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_integral
     *
     * @mbggenerated Tue Aug 16 16:26:42 CST 2016
     */
    int deleteByPrimaryKey(String integralId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_integral
     *
     * @mbggenerated Tue Aug 16 16:26:42 CST 2016
     */
    int insert(SysUserIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_integral
     *
     * @mbggenerated Tue Aug 16 16:26:42 CST 2016
     */
    int insertSelective(SysUserIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_integral
     *
     * @mbggenerated Tue Aug 16 16:26:42 CST 2016
     */
    SysUserIntegral selectByPrimaryKey(String integralId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_integral
     *
     * @mbggenerated Tue Aug 16 16:26:42 CST 2016
     */
    int updateByPrimaryKeySelective(SysUserIntegral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_integral
     *
     * @mbggenerated Tue Aug 16 16:26:42 CST 2016
     */
    int updateByPrimaryKey(SysUserIntegral record);
}