package com.culturecloud.model.bean.brandact;

import java.util.Date;

public class CmsActivityBrand {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.id
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.act_name
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private String actName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.act_tag
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private String actTag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.img_src
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private String imgSrc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.act_url
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private String actUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.act_type
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private Integer actType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.create_time
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private Date createTime;
	
	
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.act_flag
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private Integer actFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.order_index
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private Integer orderIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.operator
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cms_activity_brand.act_text
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	private String actText;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.id
	 * @return  the value of cms_activity_brand.id
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.id
	 * @param id  the value for cms_activity_brand.id
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.act_name
	 * @return  the value of cms_activity_brand.act_name
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public String getActName() {
		return actName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.act_name
	 * @param actName  the value for cms_activity_brand.act_name
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setActName(String actName) {
		this.actName = actName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.act_tag
	 * @return  the value of cms_activity_brand.act_tag
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public String getActTag() {
		return actTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.act_tag
	 * @param actTag  the value for cms_activity_brand.act_tag
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setActTag(String actTag) {
		this.actTag = actTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.img_src
	 * @return  the value of cms_activity_brand.img_src
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public String getImgSrc() {
		return imgSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.img_src
	 * @param imgSrc  the value for cms_activity_brand.img_src
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setImgSrc(String imgSrc) {
		this.imgSrc = imgSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.act_url
	 * @return  the value of cms_activity_brand.act_url
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public String getActUrl() {
		return actUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.act_url
	 * @param actUrl  the value for cms_activity_brand.act_url
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setActUrl(String actUrl) {
		this.actUrl = actUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.act_type
	 * @return  the value of cms_activity_brand.act_type
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public Integer getActType() {
		return actType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.act_type
	 * @param actType  the value for cms_activity_brand.act_type
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setActType(Integer actType) {
		this.actType = actType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.create_time
	 * @return  the value of cms_activity_brand.create_time
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.create_time
	 * @param createTime  the value for cms_activity_brand.create_time
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.act_flag
	 * @return  the value of cms_activity_brand.act_flag
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public Integer getActFlag() {
		return actFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.act_flag
	 * @param actFlag  the value for cms_activity_brand.act_flag
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setActFlag(Integer actFlag) {
		this.actFlag = actFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.order_index
	 * @return  the value of cms_activity_brand.order_index
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public Integer getOrderIndex() {
		return orderIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.order_index
	 * @param orderIndex  the value for cms_activity_brand.order_index
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setOrderIndex(Integer orderIndex) {
		this.orderIndex = orderIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.operator
	 * @return  the value of cms_activity_brand.operator
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.operator
	 * @param operator  the value for cms_activity_brand.operator
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cms_activity_brand.act_text
	 * @return  the value of cms_activity_brand.act_text
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public String getActText() {
		return actText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cms_activity_brand.act_text
	 * @param actText  the value for cms_activity_brand.act_text
	 * @mbggenerated  Mon Jun 19 11:19:10 CST 2017
	 */
	public void setActText(String actText) {
		this.actText = actText;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}