package com.culturecloud.dao.vote;

import com.culturecloud.model.bean.vote.CcpVoteTicket;

public interface CcpVoteTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_vote_ticket
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    int deleteByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_vote_ticket
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    int insert(CcpVoteTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_vote_ticket
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    int insertSelective(CcpVoteTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_vote_ticket
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    CcpVoteTicket selectByPrimaryKey(String ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_vote_ticket
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    int updateByPrimaryKeySelective(CcpVoteTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_vote_ticket
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    int updateByPrimaryKey(CcpVoteTicket record);
}