package com.culturecloud.dao.vote;

import java.util.List;
import java.util.Map;

import com.culturecloud.dao.dto.vote.CcpVoteItemDto;
import com.culturecloud.model.bean.vote.CcpVoteItem;

public interface CcpVoteItemMapper {
	
	int queryVoteItemCount(Map<String,Object> data);
	
	List<CcpVoteItemDto>queryVoteItemList(Map<String,Object> data);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote_item
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	int deleteByPrimaryKey(String voteItemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote_item
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	int insert(CcpVoteItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote_item
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	int insertSelective(CcpVoteItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote_item
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	CcpVoteItem selectByPrimaryKey(String voteItemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote_item
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	int updateByPrimaryKeySelective(CcpVoteItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote_item
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	int updateByPrimaryKey(CcpVoteItem record);
}