package com.culturecloud.dao.room;

import com.culturecloud.model.bean.room.CmsRoomTime;

public interface CmsRoomTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_room_time
     *
     * @mbggenerated Mon Jul 25 16:34:21 CST 2016
     */
    int deleteByPrimaryKey(String roomTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_room_time
     *
     * @mbggenerated Mon Jul 25 16:34:21 CST 2016
     */
    int insert(CmsRoomTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_room_time
     *
     * @mbggenerated Mon Jul 25 16:34:21 CST 2016
     */
    int insertSelective(CmsRoomTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_room_time
     *
     * @mbggenerated Mon Jul 25 16:34:21 CST 2016
     */
    CmsRoomTime selectByPrimaryKey(String roomTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_room_time
     *
     * @mbggenerated Mon Jul 25 16:34:21 CST 2016
     */
    int updateByPrimaryKeySelective(CmsRoomTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_room_time
     *
     * @mbggenerated Mon Jul 25 16:34:21 CST 2016
     */
    int updateByPrimaryKey(CmsRoomTime record);
}