package com.culturecloud.model.bean.musicessay;

import java.util.Date;

public class CcpMusicessayUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_musicessay_user.user_id
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_musicessay_user.user_real_name
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    private String userRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_musicessay_user.user_moblie_no
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    private String userMoblieNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_musicessay_user.user_mail
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_musicessay_user.user_qq
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    private String userQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_musicessay_user.user_create_time
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    private Date userCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_musicessay_user.user_id
     *
     * @return the value of ccp_musicessay_user.user_id
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_musicessay_user.user_id
     *
     * @param userId the value for ccp_musicessay_user.user_id
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_musicessay_user.user_real_name
     *
     * @return the value of ccp_musicessay_user.user_real_name
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public String getUserRealName() {
        return userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_musicessay_user.user_real_name
     *
     * @param userRealName the value for ccp_musicessay_user.user_real_name
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_musicessay_user.user_moblie_no
     *
     * @return the value of ccp_musicessay_user.user_moblie_no
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public String getUserMoblieNo() {
        return userMoblieNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_musicessay_user.user_moblie_no
     *
     * @param userMoblieNo the value for ccp_musicessay_user.user_moblie_no
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public void setUserMoblieNo(String userMoblieNo) {
        this.userMoblieNo = userMoblieNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_musicessay_user.user_mail
     *
     * @return the value of ccp_musicessay_user.user_mail
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_musicessay_user.user_mail
     *
     * @param userMail the value for ccp_musicessay_user.user_mail
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_musicessay_user.user_qq
     *
     * @return the value of ccp_musicessay_user.user_qq
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public String getUserQq() {
        return userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_musicessay_user.user_qq
     *
     * @param userQq the value for ccp_musicessay_user.user_qq
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public void setUserQq(String userQq) {
        this.userQq = userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_musicessay_user.user_create_time
     *
     * @return the value of ccp_musicessay_user.user_create_time
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_musicessay_user.user_create_time
     *
     * @param userCreateTime the value for ccp_musicessay_user.user_create_time
     *
     * @mbggenerated Tue Apr 25 20:03:54 CST 2017
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }
}