package com.culturecloud.model.bean.contest;


import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table(value="ccp_contest_topic_pass")
public class CcpContestTopicPass implements BaseEntity{
	
	private static final long serialVersionUID = 4893097324008032327L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_contest_topic_pass.topic_pass_id
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	@Id
	@Column(name="topic_pass_id")
	private String topicPassId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_contest_topic_pass.pass_number
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	@Column(name="pass_number")
	private Integer passNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_contest_topic_pass.pass_name
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	@Column(name="pass_name")
	private String passName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_contest_topic_pass.topic_id
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	@Column(name="topic_id")
	private String topicId;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_contest_topic_pass.topic_pass_id
	 * @return  the value of ccp_contest_topic_pass.topic_pass_id
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	public String getTopicPassId() {
		return topicPassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_contest_topic_pass.topic_pass_id
	 * @param topicPassId  the value for ccp_contest_topic_pass.topic_pass_id
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	public void setTopicPassId(String topicPassId) {
		this.topicPassId = topicPassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_contest_topic_pass.pass_number
	 * @return  the value of ccp_contest_topic_pass.pass_number
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	public Integer getPassNumber() {
		return passNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_contest_topic_pass.pass_number
	 * @param passNumber  the value for ccp_contest_topic_pass.pass_number
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	public void setPassNumber(Integer passNumber) {
		this.passNumber = passNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_contest_topic_pass.pass_name
	 * @return  the value of ccp_contest_topic_pass.pass_name
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	public String getPassName() {
		return passName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_contest_topic_pass.pass_name
	 * @param passName  the value for ccp_contest_topic_pass.pass_name
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	public void setPassName(String passName) {
		this.passName = passName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_contest_topic_pass.topic_id
	 * @return  the value of ccp_contest_topic_pass.topic_id
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	public String getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_contest_topic_pass.topic_id
	 * @param topicId  the value for ccp_contest_topic_pass.topic_id
	 * @mbggenerated  Fri Jul 08 17:34:50 CST 2016
	 */
	public void setTopicId(String topicId) {
		this.topicId = topicId;
	}

	
}