package com.culturecloud.model.bean.contest;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table(value="ccp_contest_question")
public class CcpContestQuestion implements BaseEntity{
	
	private static final long serialVersionUID = -5960188322709181113L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_question.question_id
     *
     * @mbggenerated Fri Jul 08 09:23:09 CST 2016
     */
	@Id
	@Column(name="question_id")
    private String questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_question.question_title
     *
     * @mbggenerated Fri Jul 08 09:23:09 CST 2016
     */
	@Column(name="question_title")
    private String questionTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_question.question_id
     *
     * @return the value of ccp_contest_question.question_id
     *
     * @mbggenerated Fri Jul 08 09:23:09 CST 2016
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_question.question_id
     *
     * @param questionId the value for ccp_contest_question.question_id
     *
     * @mbggenerated Fri Jul 08 09:23:09 CST 2016
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_question.question_title
     *
     * @return the value of ccp_contest_question.question_title
     *
     * @mbggenerated Fri Jul 08 09:23:09 CST 2016
     */
    public String getQuestionTitle() {
        return questionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_question.question_title
     *
     * @param questionTitle the value for ccp_contest_question.question_title
     *
     * @mbggenerated Fri Jul 08 09:23:09 CST 2016
     */
    public void setQuestionTitle(String questionTitle) {
        this.questionTitle = questionTitle;
    }
}