package com.culturecloud.model.bean.contest;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;

public class CcpContestTopicQuestionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_topic_question.question_id
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
	@Id
	@Column(name="question_id")
    private String questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_topic_question.topic_id
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
	@Id
	@Column(name="topic_id")
    private String topicId;
	
	
	public CcpContestTopicQuestionKey() {
		super();
	}

    public CcpContestTopicQuestionKey(String questionId, String topicId) {
		this.questionId = questionId;
		this.topicId = topicId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_topic_question.question_id
     *
     * @return the value of ccp_contest_topic_question.question_id
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_topic_question.question_id
     *
     * @param questionId the value for ccp_contest_topic_question.question_id
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_topic_question.topic_id
     *
     * @return the value of ccp_contest_topic_question.topic_id
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    public String getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_topic_question.topic_id
     *
     * @param topicId the value for ccp_contest_topic_question.topic_id
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    public void setTopicId(String topicId) {
        this.topicId = topicId;
    }
}