package com.culturecloud.model.bean.contest;

import javax.persistence.Column;

import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table(value="ccp_contest_topic_question")
public class CcpContestTopicQuestion extends CcpContestTopicQuestionKey implements BaseEntity{
    
	private static final long serialVersionUID = -174864128490845426L;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_topic_question.question_number
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
	@Column(name="question_number")
    private Integer questionNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_topic_question.question_number
     *
     * @return the value of ccp_contest_topic_question.question_number
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    public Integer getQuestionNumber() {
        return questionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_topic_question.question_number
     *
     * @param questionNumber the value for ccp_contest_topic_question.question_number
     *
     * @mbggenerated Thu Jul 07 13:37:16 CST 2016
     */
    public void setQuestionNumber(Integer questionNumber) {
        this.questionNumber = questionNumber;
    }
}