package com.culturecloud.model.bean.contest;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table(value="ccp_contest_answer")
public class CcpContestAnswer implements BaseEntity{
	
	private static final long serialVersionUID = -4288999106396494320L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_answer.answer_id
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
	@Id
	@Column(name="answer_id")
    private String answerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_answer.answer_text
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
	@Column(name="answer_text")
    private String answerText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_answer.answer_pic_url
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
	@Column(name="answer_pic_url")
    private String answerPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_answer.question_id
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
	@Column(name="question_id")
    private String questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_contest_answer.is_true
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
	@Column(name="is_true")
    private Integer isTrue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_answer.answer_id
     *
     * @return the value of ccp_contest_answer.answer_id
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public String getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_answer.answer_id
     *
     * @param answerId the value for ccp_contest_answer.answer_id
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public void setAnswerId(String answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_answer.answer_text
     *
     * @return the value of ccp_contest_answer.answer_text
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public String getAnswerText() {
        return answerText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_answer.answer_text
     *
     * @param answerText the value for ccp_contest_answer.answer_text
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public void setAnswerText(String answerText) {
        this.answerText = answerText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_answer.answer_pic_url
     *
     * @return the value of ccp_contest_answer.answer_pic_url
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public String getAnswerPicUrl() {
        return answerPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_answer.answer_pic_url
     *
     * @param answerPicUrl the value for ccp_contest_answer.answer_pic_url
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public void setAnswerPicUrl(String answerPicUrl) {
        this.answerPicUrl = answerPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_answer.question_id
     *
     * @return the value of ccp_contest_answer.question_id
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_answer.question_id
     *
     * @param questionId the value for ccp_contest_answer.question_id
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public void setQuestionId(String questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_contest_answer.is_true
     *
     * @return the value of ccp_contest_answer.is_true
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public Integer getIsTrue() {
        return isTrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_contest_answer.is_true
     *
     * @param isTrue the value for ccp_contest_answer.is_true
     *
     * @mbggenerated Fri Jul 08 09:27:20 CST 2016
     */
    public void setIsTrue(Integer isTrue) {
        this.isTrue = isTrue;
    }
}