package com.culturecloud.dao.live;

import java.util.List;

import com.culturecloud.dao.dto.live.CcpLiveMessageDto;
import com.culturecloud.model.bean.live.CcpLiveMessage;
import com.culturecloud.model.request.live.CcpLiveMessagePageVO;

public interface CcpLiveMessageMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_message
	 * @mbggenerated  Sat Feb 04 14:19:07 CST 2017
	 */
	int deleteByPrimaryKey(String messageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_message
	 * @mbggenerated  Sat Feb 04 14:19:07 CST 2017
	 */
	int insert(CcpLiveMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_message
	 * @mbggenerated  Sat Feb 04 14:19:07 CST 2017
	 */
	int insertSelective(CcpLiveMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_message
	 * @mbggenerated  Sat Feb 04 14:19:07 CST 2017
	 */
	CcpLiveMessage selectByPrimaryKey(String messageId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_message
	 * @mbggenerated  Sat Feb 04 14:19:07 CST 2017
	 */
	int updateByPrimaryKeySelective(CcpLiveMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_message
	 * @mbggenerated  Sat Feb 04 14:19:07 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(CcpLiveMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_message
	 * @mbggenerated  Sat Feb 04 14:19:07 CST 2017
	 */
	int updateByPrimaryKey(CcpLiveMessage record);

	List<CcpLiveMessageDto> selectLiveMessageList(CcpLiveMessagePageVO liveMessagePageVO);
	
	int selectLiveMessageCount(CcpLiveMessagePageVO liveMessagePageVO);
	
	List<CcpLiveMessageDto> getLiveHistoryVideoList(String liveActivityId);
}