package com.culturecloud.dao.live;

import java.util.List;

import com.culturecloud.dao.dto.live.CcpLiveActivityDto;
import com.culturecloud.dao.dto.live.CmsCulturalSquareLiveImgDTO;
import com.culturecloud.model.bean.live.CcpLiveActivity;
import com.culturecloud.model.request.common.SysUserDetailVO;
import com.culturecloud.model.request.live.CcpLiveActivityPageVO;
import com.culturecloud.model.request.live.CcpRecommendLiveListVO;

public interface CcpLiveActivityMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_activity
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	int deleteByPrimaryKey(String liveActivityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_activity
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	int insert(CcpLiveActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_activity
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	int insertSelective(CcpLiveActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_activity
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	CcpLiveActivityDto selectByPrimaryKey(String liveActivityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_activity
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	int updateByPrimaryKeySelective(CcpLiveActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_live_activity
	 * @mbggenerated  Tue Mar 28 15:50:54 CST 2017
	 */
	int updateByPrimaryKey(CcpLiveActivity record);

	int selectLiveActivityCount(CcpLiveActivityPageVO liveActivityPageVO);
	
	List<CcpLiveActivityDto> selectLiveActivityList(CcpLiveActivityPageVO liveActivityPageVO);
	
	Integer selectIndexNum(CcpLiveActivityPageVO liveActivityPageVO);
	
	CcpLiveActivityDto queryUserInfo(SysUserDetailVO request);
	
	List<CmsCulturalSquareLiveImgDTO> getLive(String liveActivityId);
	
	List<CcpLiveActivityDto> selectLiveActivityHotList();
	
	// 用户累计发布直播数
	Integer userTotalLive(String userId);
	
	// 用户累计获赞数
	Integer userTotalLiveLike(String userId);
	
	// 用户累计评论数
	Integer userTotalLiveMessage(String userId);
	
	// 查询推荐直播
	List<CcpLiveActivityDto> selectLiveActivityRecommendList( CcpRecommendLiveListVO ccpRecommendLiveListVO);
}