package com.culturecloud.dao.activity;

import com.culturecloud.model.bean.activity.CmsActivityOrderDetail;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CmsActivityOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_order_detail
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    int deleteByPrimaryKey(@Param("activityOrderId") String activityOrderId, @Param("orderLine") Integer orderLine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_order_detail
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    int insert(CmsActivityOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_order_detail
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    int insertSelective(CmsActivityOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_order_detail
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    CmsActivityOrderDetail selectByPrimaryKey(@Param("activityOrderId") String activityOrderId, @Param("orderLine") Integer orderLine);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_order_detail
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    int updateByPrimaryKeySelective(CmsActivityOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_order_detail
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    int updateByPrimaryKey(CmsActivityOrderDetail record);

    Integer queryOrderCountByEvent(String eventId);
    
    List<CmsActivityOrderDetail> queryActivityOrderDetailById(@Param("activityOrderId") String activityOrderId);
}