package com.culturecloud.dao.activity;

import java.util.List;
import java.util.Map;

import com.culturecloud.dao.dto.activity.CmsActivityEventDto;
import com.culturecloud.model.bean.activity.CmsActivityEvent;

public interface CmsActivityEventMapper {
	
	
	List<CmsActivityEventDto> queryActivityEventById( Map<String, Object> map );
	 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_event
     *
     * @mbggenerated Mon Jul 25 14:37:37 CST 2016
     */
    int deleteByPrimaryKey(String eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_event
     *
     * @mbggenerated Mon Jul 25 14:37:37 CST 2016
     */
    int insert(CmsActivityEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_event
     *
     * @mbggenerated Mon Jul 25 14:37:37 CST 2016
     */
    int insertSelective(CmsActivityEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_event
     *
     * @mbggenerated Mon Jul 25 14:37:37 CST 2016
     */
    CmsActivityEvent selectByPrimaryKey(String eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_event
     *
     * @mbggenerated Mon Jul 25 14:37:37 CST 2016
     */
    int updateByPrimaryKeySelective(CmsActivityEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_event
     *
     * @mbggenerated Mon Jul 25 14:37:37 CST 2016
     */
    int updateByPrimaryKey(CmsActivityEvent record);
}