package com.culturecloud.dao.activity;

import com.culturecloud.model.bean.activity.CmsActivitySeat;

import java.util.Map;

public interface CmsActivitySeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_seat
     *
     * @mbggenerated Mon Jul 25 14:56:35 CST 2016
     */
    int deleteByPrimaryKey(String activitySeatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_seat
     *
     * @mbggenerated Mon Jul 25 14:56:35 CST 2016
     */
    int insert(CmsActivitySeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_seat
     *
     * @mbggenerated Mon Jul 25 14:56:35 CST 2016
     */
    int insertSelective(CmsActivitySeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_seat
     *
     * @mbggenerated Mon Jul 25 14:56:35 CST 2016
     */
    CmsActivitySeat selectByPrimaryKey(String activitySeatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_seat
     *
     * @mbggenerated Mon Jul 25 14:56:35 CST 2016
     */
    int updateByPrimaryKeySelective(CmsActivitySeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_seat
     *
     * @mbggenerated Mon Jul 25 14:56:35 CST 2016
     */
    int updateByPrimaryKey(CmsActivitySeat record);

    /**
     * 根据活动id  和 seatCode  查询seatVal;
     * @param map
     * @return
     */
    CmsActivitySeat querySeatValByMap(Map map);
}