package com.culturecloud.dao.activity;

import com.culturecloud.model.bean.activity.CmsActivityVenueRelevance;

public interface CmsActivityVenueRelevanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_venue_relevance
     *
     * @mbggenerated Mon Jul 25 14:59:52 CST 2016
     */
    int insert(CmsActivityVenueRelevance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_activity_venue_relevance
     *
     * @mbggenerated Mon Jul 25 14:59:52 CST 2016
     */
    int insertSelective(CmsActivityVenueRelevance record);
}