package com.culturecloud.dao.activity;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.culturecloud.dao.dto.activity.ActivityVO;
import com.culturecloud.dao.dto.activity.CmsActivityDto;
import com.culturecloud.model.bean.activity.CmsActivity;

public interface CmsActivityMapper {

	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity
	 * @mbggenerated  Fri May 05 16:43:30 CST 2017
	 */
	int deleteByPrimaryKey(String activityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity
	 * @mbggenerated  Fri May 05 16:43:30 CST 2017
	 */
	int insert(CmsActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity
	 * @mbggenerated  Fri May 05 16:43:30 CST 2017
	 */
	int insertSelective(CmsActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity
	 * @mbggenerated  Fri May 05 16:43:30 CST 2017
	 */
	CmsActivity selectByPrimaryKey(String activityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity
	 * @mbggenerated  Fri May 05 16:43:30 CST 2017
	 */
	int updateByPrimaryKeySelective(CmsActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity
	 * @mbggenerated  Fri May 05 16:43:30 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(CmsActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity
	 * @mbggenerated  Fri May 05 16:43:30 CST 2017
	 */
	int updateByPrimaryKey(CmsActivity record);

	/**
	 * 查询社团活动
	 * @param map
	 * @return
	 */
	List<CmsActivityDto> queryAssociationActivity(Map<String,Object>map);
	
	/**
	 * 查询社团历史活动
	 * @param map
	 * @return
	 */
	List<CmsActivityDto> queryAssociationHistoryActivity(Map<String,Object>map);
	
	/**
	 * 查询首页推荐活动
	 * @param map
	 * @return
	 */
	List<CmsActivityDto> queryRecommendActivityList(Map<String, Object> map);
	
	/**
	 * 查询附近活动
	 * @param map
	 * @return
	 */
	List<CmsActivityDto> queryNearActivityList(Map<String, Object> map);
	
	/**
	 * 查询根据用户分数计算后得出的搜索类型活动
	 * @param activityType
	 * @return
	 */
	List<CmsActivityDto> queryUserSoucreActivityList(String activityType);
	
	/**
	 * 搜索名称
	 * @param keyword
	 * @return
	 */
	List<CmsActivityDto> searchByName(@Param("keyword") String keyword,@Param("limit")int limit);
	
	List<CmsActivityDto> searchByType(@Param("keyword")String keyword,@Param("limit")int limit);
	
	List<CmsActivityDto> searchByTag(@Param("keyword")String keyword,@Param("limit")int limit);
	
	List<CmsActivityDto> searchByAddress(@Param("keyword")String keyword,@Param("limit")int limit);
	
	List<CmsActivityDto> searchByVenue(@Param("keyword")String keyword,@Param("limit")int limit);
	
	List<CmsActivityDto> searchByPerformed(@Param("keyword")String keyword,@Param("limit")int limit);
	
	
	/**
	 * 搜索联想名称
	 * @param name
	 * @param limit
	 * @return
	 */
	List<String> searchAutomatedName(@Param("keyword")String keyword,@Param("limit")int limit);
	
	CmsActivityDto queryCmsActivityDetailById(Map<String, Object> map);
	
	int getActiviyInfoCount(Map<String, Object> map);

	List<ActivityVO> getActiviyInfoList(Map<String, Object> map);
	
	List<CmsActivityDto> queryActivityByCidition(Map<String, Object> map);

	int queryAssociationHistoryActivityCount(Map<String, Object> map);

	List<CmsActivityDto> queryAssociationHistoryActivityPC(Map<String,Object> map);
}