package com.culturecloud.dao.activity;

import com.culturecloud.dao.dto.activity.CmsActivityOrderDto;
import com.culturecloud.model.bean.activity.CmsActivityOrder;

import java.util.List;
import java.util.Map;

public interface CmsActivityOrderMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity_order
	 * @mbggenerated  Wed Feb 22 18:42:05 CST 2017
	 */
	int deleteByPrimaryKey(String activityOrderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity_order
	 * @mbggenerated  Wed Feb 22 18:42:05 CST 2017
	 */
	int insert(CmsActivityOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity_order
	 * @mbggenerated  Wed Feb 22 18:42:05 CST 2017
	 */
	int insertSelective(CmsActivityOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity_order
	 * @mbggenerated  Wed Feb 22 18:42:05 CST 2017
	 */
	CmsActivityOrder selectByPrimaryKey(String activityOrderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity_order
	 * @mbggenerated  Wed Feb 22 18:42:05 CST 2017
	 */
	int updateByPrimaryKeySelective(CmsActivityOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity_order
	 * @mbggenerated  Wed Feb 22 18:42:05 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(CmsActivityOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cms_activity_order
	 * @mbggenerated  Wed Feb 22 18:42:05 CST 2017
	 */
	int updateByPrimaryKey(CmsActivityOrder record);

	/**
     * 查询用户已经购买的订单数
     * @param map
     * @return
     */
    Integer queryOrderCountByUser(Map map);

    /**
     * 查询用户已经购买的票
     * @param map
     * @return
     */
    Integer queryOrderDetailCountByUser(Map map);
    
    /**
     * 活动订单信息查询
     * @param map
     * @return
     */
    List<CmsActivityOrderDto> queryActvityOrderByCondition(Map<String, Object> map);
}