package com.culturecloud.model.bean.moviessay;

import java.util.Date;

public class CcpMoviessayLike {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_moviessay_like.article_id
     *
     * @mbggenerated Fri Jun 02 17:20:15 CST 2017
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_moviessay_like.user_id
     *
     * @mbggenerated Fri Jun 02 17:20:15 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_moviessay_like.create_date
     *
     * @mbggenerated Fri Jun 02 17:20:15 CST 2017
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_moviessay_like.article_id
     *
     * @return the value of ccp_moviessay_like.article_id
     *
     * @mbggenerated Fri Jun 02 17:20:15 CST 2017
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_moviessay_like.article_id
     *
     * @param articleId the value for ccp_moviessay_like.article_id
     *
     * @mbggenerated Fri Jun 02 17:20:15 CST 2017
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_moviessay_like.user_id
     *
     * @return the value of ccp_moviessay_like.user_id
     *
     * @mbggenerated Fri Jun 02 17:20:15 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_moviessay_like.user_id
     *
     * @param userId the value for ccp_moviessay_like.user_id
     *
     * @mbggenerated Fri Jun 02 17:20:15 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_moviessay_like.create_date
     *
     * @return the value of ccp_moviessay_like.create_date
     *
     * @mbggenerated Fri Jun 02 17:20:15 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_moviessay_like.create_date
     *
     * @param createDate the value for ccp_moviessay_like.create_date
     *
     * @mbggenerated Fri Jun 02 17:20:15 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}