package com.culturecloud.model.bean.moviessay;

import java.util.Date;

public class CcpMoviessayArticle {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ccp_moviessay_article.article_id
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	private String articleId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ccp_moviessay_article.user_id
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	private String userId;


	private String movieName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ccp_moviessay_article.article_type
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	private Integer articleType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ccp_moviessay_article.theme_type
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	private Integer themeType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ccp_moviessay_article.article_is_del
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	private Integer articleIsDel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ccp_moviessay_article.article_title
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	private String articleTitle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ccp_moviessay_article.article_create_time
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	private Date articleCreateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ccp_moviessay_article.article_like
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	private Integer articleLike;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ccp_moviessay_article.article_text
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	private String articleText;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ccp_moviessay_article.article_id
	 *
	 * @return the value of ccp_moviessay_article.article_id
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public String getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ccp_moviessay_article.article_id
	 *
	 * @param articleId
	 *            the value for ccp_moviessay_article.article_id
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ccp_moviessay_article.user_id
	 *
	 * @return the value of ccp_moviessay_article.user_id
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ccp_moviessay_article.user_id
	 *
	 * @param userId
	 *            the value for ccp_moviessay_article.user_id
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ccp_moviessay_article.article_type
	 *
	 * @return the value of ccp_moviessay_article.article_type
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public Integer getArticleType() {
		return articleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ccp_moviessay_article.article_type
	 *
	 * @param articleType
	 *            the value for ccp_moviessay_article.article_type
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public void setArticleType(Integer articleType) {
		this.articleType = articleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ccp_moviessay_article.theme_type
	 *
	 * @return the value of ccp_moviessay_article.theme_type
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public Integer getThemeType() {
		return themeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ccp_moviessay_article.theme_type
	 *
	 * @param themeType
	 *            the value for ccp_moviessay_article.theme_type
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public void setThemeType(Integer themeType) {
		this.themeType = themeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ccp_moviessay_article.article_is_del
	 *
	 * @return the value of ccp_moviessay_article.article_is_del
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public Integer getArticleIsDel() {
		return articleIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ccp_moviessay_article.article_is_del
	 *
	 * @param articleIsDel
	 *            the value for ccp_moviessay_article.article_is_del
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public void setArticleIsDel(Integer articleIsDel) {
		this.articleIsDel = articleIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ccp_moviessay_article.article_title
	 *
	 * @return the value of ccp_moviessay_article.article_title
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public String getArticleTitle() {
		return articleTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ccp_moviessay_article.article_title
	 *
	 * @param articleTitle
	 *            the value for ccp_moviessay_article.article_title
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ccp_moviessay_article.article_create_time
	 *
	 * @return the value of ccp_moviessay_article.article_create_time
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public Date getArticleCreateTime() {
		return articleCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ccp_moviessay_article.article_create_time
	 *
	 * @param articleCreateTime
	 *            the value for ccp_moviessay_article.article_create_time
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public void setArticleCreateTime(Date articleCreateTime) {
		this.articleCreateTime = articleCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ccp_moviessay_article.article_like
	 *
	 * @return the value of ccp_moviessay_article.article_like
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public Integer getArticleLike() {
		return articleLike;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ccp_moviessay_article.article_like
	 *
	 * @param articleLike
	 *            the value for ccp_moviessay_article.article_like
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public void setArticleLike(Integer articleLike) {
		this.articleLike = articleLike;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ccp_moviessay_article.article_text
	 *
	 * @return the value of ccp_moviessay_article.article_text
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public String getArticleText() {
		return articleText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ccp_moviessay_article.article_text
	 *
	 * @param articleText
	 *            the value for ccp_moviessay_article.article_text
	 *
	 * @mbggenerated Fri Jun 02 17:15:31 CST 2017
	 */
	public void setArticleText(String articleText) {
		this.articleText = articleText;
	}
	
	public String getMovieName() {
		return movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}
}