package com.culturecloud.dao.advert;

import java.util.List;

import com.culturecloud.dao.dto.advert.CcpAdvertRecommendDto;
import com.culturecloud.model.bean.advert.CcpAdvertRecommend;

public interface CcpAdvertRecommendMapper {
	
	 List<CcpAdvertRecommendDto> queryAdvertRecommend(CcpAdvertRecommend advertRecommend);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_advert_recommend
     *
     * @mbggenerated Fri Aug 05 13:00:20 CST 2016
     */
    int deleteByPrimaryKey(String advertId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_advert_recommend
     *
     * @mbggenerated Fri Aug 05 13:00:20 CST 2016
     */
    int insert(CcpAdvertRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_advert_recommend
     *
     * @mbggenerated Fri Aug 05 13:00:20 CST 2016
     */
    int insertSelective(CcpAdvertRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_advert_recommend
     *
     * @mbggenerated Fri Aug 05 13:00:20 CST 2016
     */
    CcpAdvertRecommend selectByPrimaryKey(String advertId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_advert_recommend
     *
     * @mbggenerated Fri Aug 05 13:00:20 CST 2016
     */
    int updateByPrimaryKeySelective(CcpAdvertRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccp_advert_recommend
     *
     * @mbggenerated Fri Aug 05 13:00:20 CST 2016
     */
    int updateByPrimaryKey(CcpAdvertRecommend record);
}