package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.culturecloud.model.bean.culture.CcpCultureContestAnswer;
import com.sun3d.why.dao.dto.CcpCultureContestAnswerDto;

public interface CcpCultureContestAnswerMapper {
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_answer
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	int deleteByPrimaryKey(String cultureAnswerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_answer
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	int insert(CcpCultureContestAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_answer
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	int insertSelective(CcpCultureContestAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_answer
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	CcpCultureContestAnswer selectByPrimaryKey(String cultureAnswerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_answer
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	int updateByPrimaryKeySelective(CcpCultureContestAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_answer
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(CcpCultureContestAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_answer
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	int updateByPrimaryKey(CcpCultureContestAnswer record);

	List<CcpCultureContestAnswer> queryUserContestAnswerList(@Param("userId")String userId,@Param("stageNumber")Integer stageNumber);
	
	List<CcpCultureContestAnswerDto> queryAnswerRanking(Map<String,Object>map);
	
	List<CcpCultureContestAnswerDto> queryAnswerSumRanking(Map<String,Object>map);

	
}