package com.sun3d.why.dao;

import com.culturecloud.model.bean.culture.CcpCultureContestUser;

public interface CcpCultureContestUserMapper {
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_user
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	int deleteByPrimaryKey(String cultureUserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_user
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	int insert(CcpCultureContestUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_user
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	int insertSelective(CcpCultureContestUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_user
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	CcpCultureContestUser selectByPrimaryKey(String cultureUserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_user
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	int updateByPrimaryKeySelective(CcpCultureContestUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_culture_contest_user
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	int updateByPrimaryKey(CcpCultureContestUser record);

	CcpCultureContestUser queryCultureContestUserByUser(String userId);
}