package com.sun3d.why.dao;

import java.util.List;
import java.util.Map;

import com.culturecloud.model.bean.vote.CcpVote;
import com.sun3d.why.dao.dto.CcpVoteDto;

public interface CcpVoteMapper {
	
	public List<CcpVoteDto> queryVoteByCondition(Map<String,Object>map);
	
	public int queryVoteCountByCondition(Map<String,Object>map);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	int deleteByPrimaryKey(String voteId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	int insert(CcpVote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	int insertSelective(CcpVote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	CcpVote selectByPrimaryKey(String voteId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	int updateByPrimaryKeySelective(CcpVote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(CcpVote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_vote
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	int updateByPrimaryKey(CcpVote record);
}