package com.sun3d.why.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.culturecloud.model.bean.ticketmachine.TicketMachineVenue;

public interface TicketMachineVenueMapper {
	
	
	List<TicketMachineVenue> selectTicketMachineVenueByModel(@Param("machineCode") String machineCode, @Param("venueId") String venueId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_venue
	 * @mbggenerated  Mon Jan 09 16:36:10 CST 2017
	 */
	int deleteByPrimaryKey(@Param("machineCode") String machineCode, @Param("venueId") String venueId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_venue
	 * @mbggenerated  Mon Jan 09 16:36:10 CST 2017
	 */
	int insert(TicketMachineVenue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ticket_machine_venue
	 * @mbggenerated  Mon Jan 09 16:36:10 CST 2017
	 */
	int insertSelective(TicketMachineVenue record);
}