package com.culturecloud.bean;

import java.util.Date;

public class UserIntegralDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral_detail.INTEGRAL_DETAIL_ID
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    private String integralDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral_detail.INTEGRAL_ID
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    private String integralId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral_detail.INTEGRAL_CHANGE
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    private Integer integralChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral_detail.CREATE_TIME
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral_detail.CHANGE_TYPE
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    private Integer changeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral_detail.INTEGRAL_FROM
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    private String integralFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_integral_detail.INTEGRAL_TYPE
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    private Integer integralType;
    
    //虚拟字段
    private String userId;
    
    private Integer updateType;		//0：不做唯一判断；1：做唯一判断
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral_detail.INTEGRAL_DETAIL_ID
     *
     * @return the value of sys_user_integral_detail.INTEGRAL_DETAIL_ID
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public String getIntegralDetailId() {
        return integralDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral_detail.INTEGRAL_DETAIL_ID
     *
     * @param integralDetailId the value for sys_user_integral_detail.INTEGRAL_DETAIL_ID
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public void setIntegralDetailId(String integralDetailId) {
        this.integralDetailId = integralDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral_detail.INTEGRAL_ID
     *
     * @return the value of sys_user_integral_detail.INTEGRAL_ID
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public String getIntegralId() {
        return integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral_detail.INTEGRAL_ID
     *
     * @param integralId the value for sys_user_integral_detail.INTEGRAL_ID
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public void setIntegralId(String integralId) {
        this.integralId = integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral_detail.INTEGRAL_CHANGE
     *
     * @return the value of sys_user_integral_detail.INTEGRAL_CHANGE
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public Integer getIntegralChange() {
        return integralChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral_detail.INTEGRAL_CHANGE
     *
     * @param integralChange the value for sys_user_integral_detail.INTEGRAL_CHANGE
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public void setIntegralChange(Integer integralChange) {
        this.integralChange = integralChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral_detail.CREATE_TIME
     *
     * @return the value of sys_user_integral_detail.CREATE_TIME
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral_detail.CREATE_TIME
     *
     * @param createTime the value for sys_user_integral_detail.CREATE_TIME
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral_detail.CHANGE_TYPE
     *
     * @return the value of sys_user_integral_detail.CHANGE_TYPE
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public Integer getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral_detail.CHANGE_TYPE
     *
     * @param changeType the value for sys_user_integral_detail.CHANGE_TYPE
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public void setChangeType(Integer changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral_detail.INTEGRAL_FROM
     *
     * @return the value of sys_user_integral_detail.INTEGRAL_FROM
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public String getIntegralFrom() {
        return integralFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral_detail.INTEGRAL_FROM
     *
     * @param integralFrom the value for sys_user_integral_detail.INTEGRAL_FROM
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public void setIntegralFrom(String integralFrom) {
        this.integralFrom = integralFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_integral_detail.INTEGRAL_TYPE
     *
     * @return the value of sys_user_integral_detail.INTEGRAL_TYPE
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public Integer getIntegralType() {
        return integralType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_integral_detail.INTEGRAL_TYPE
     *
     * @param integralType the value for sys_user_integral_detail.INTEGRAL_TYPE
     *
     * @mbggenerated Wed Jun 01 15:48:50 CST 2016
     */
    public void setIntegralType(Integer integralType) {
        this.integralType = integralType;
    }

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getUpdateType() {
		return updateType;
	}

	public void setUpdateType(Integer updateType) {
		this.updateType = updateType;
	}
}