package com.culturecloud.dao.volunteer;

import com.culturecloud.dao.dto.volunteer.CcpVolunteerRecruitDto;
import com.culturecloud.model.bean.volunteer.CcpVolunteerRecruit;

import java.util.List;

public interface CcpVolunteerRecruitMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_volunteer_recruit
	 * @mbggenerated  Fri Aug 26 17:53:59 CST 2016
	 */
	int deleteByPrimaryKey(String recruitId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_volunteer_recruit
	 * @mbggenerated  Fri Aug 26 17:53:59 CST 2016
	 */
	int insert(CcpVolunteerRecruit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_volunteer_recruit
	 * @mbggenerated  Fri Aug 26 17:53:59 CST 2016
	 */
	int insertSelective(CcpVolunteerRecruit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_volunteer_recruit
	 * @mbggenerated  Fri Aug 26 17:53:59 CST 2016
	 */
	CcpVolunteerRecruit selectByPrimaryKey(String recruitId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_volunteer_recruit
	 * @mbggenerated  Fri Aug 26 17:53:59 CST 2016
	 */
	int updateByPrimaryKeySelective(CcpVolunteerRecruit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_volunteer_recruit
	 * @mbggenerated  Fri Aug 26 17:53:59 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(CcpVolunteerRecruit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ccp_volunteer_recruit
	 * @mbggenerated  Fri Aug 26 17:53:59 CST 2016
	 */
	int updateByPrimaryKey(CcpVolunteerRecruit record);

	List<CcpVolunteerRecruitDto> queryVolunteerRecruitList();
}