package com.culturecloud.model.bean.common;

public class CcpAreaCity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_city.city_id
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	private Integer cityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_city.city_name
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_city.city_code
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	private String cityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_city.city_index
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	private Integer cityIndex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_city.area_id
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	private Integer areaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_city.first_letter
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	private String firstLetter;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_city.city_id
	 * @return  the value of ccp_area_city.city_id
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_city.city_id
	 * @param cityId  the value for ccp_area_city.city_id
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_city.city_name
	 * @return  the value of ccp_area_city.city_name
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_city.city_name
	 * @param cityName  the value for ccp_area_city.city_name
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_city.city_code
	 * @return  the value of ccp_area_city.city_code
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public String getCityCode() {
		return cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_city.city_code
	 * @param cityCode  the value for ccp_area_city.city_code
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_city.city_index
	 * @return  the value of ccp_area_city.city_index
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public Integer getCityIndex() {
		return cityIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_city.city_index
	 * @param cityIndex  the value for ccp_area_city.city_index
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public void setCityIndex(Integer cityIndex) {
		this.cityIndex = cityIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_city.area_id
	 * @return  the value of ccp_area_city.area_id
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public Integer getAreaId() {
		return areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_city.area_id
	 * @param areaId  the value for ccp_area_city.area_id
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_city.first_letter
	 * @return  the value of ccp_area_city.first_letter
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public String getFirstLetter() {
		return firstLetter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_city.first_letter
	 * @param firstLetter  the value for ccp_area_city.first_letter
	 * @mbggenerated  Mon Nov 21 20:58:58 CST 2016
	 */
	public void setFirstLetter(String firstLetter) {
		this.firstLetter = firstLetter;
	}
}