package com.culturecloud.model.bean.common;

public class CcpAreaPage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_page.city_id
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	private Integer cityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_page.page_path
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	private String pagePath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_page.platform_path
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	private String platformPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_page.city_status
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	private Integer cityStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_area_page.is_quick_search
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	private Integer isQuickSearch;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_page.city_id
	 * @return  the value of ccp_area_page.city_id
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_page.city_id
	 * @param cityId  the value for ccp_area_page.city_id
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_page.page_path
	 * @return  the value of ccp_area_page.page_path
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public String getPagePath() {
		return pagePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_page.page_path
	 * @param pagePath  the value for ccp_area_page.page_path
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public void setPagePath(String pagePath) {
		this.pagePath = pagePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_page.platform_path
	 * @return  the value of ccp_area_page.platform_path
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public String getPlatformPath() {
		return platformPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_page.platform_path
	 * @param platformPath  the value for ccp_area_page.platform_path
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public void setPlatformPath(String platformPath) {
		this.platformPath = platformPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_page.city_status
	 * @return  the value of ccp_area_page.city_status
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public Integer getCityStatus() {
		return cityStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_page.city_status
	 * @param cityStatus  the value for ccp_area_page.city_status
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public void setCityStatus(Integer cityStatus) {
		this.cityStatus = cityStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_area_page.is_quick_search
	 * @return  the value of ccp_area_page.is_quick_search
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public Integer getIsQuickSearch() {
		return isQuickSearch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_area_page.is_quick_search
	 * @param isQuickSearch  the value for ccp_area_page.is_quick_search
	 * @mbggenerated  Mon Nov 21 18:44:05 CST 2016
	 */
	public void setIsQuickSearch(Integer isQuickSearch) {
		this.isQuickSearch = isQuickSearch;
	}
}