package com.culturecloud.model.bean.common;

import java.util.Date;

public class CcpInformation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_ID
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String informationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_TITLE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String informationTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.AUTHOR_NAME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String authorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.PUBLISHER_NAME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String publisherName;

	public String getBrief() {
		return brief;
	}

	public void setBrief(String brief) {
		this.brief = brief;
	}

	private String brief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_SORT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private Integer informationSort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_TAGS
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String informationTags;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.SHARE_TITLE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String shareTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.SHARE_SUMMARY
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String shareSummary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_ICON_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String informationIconUrl;
	//点击图片跳转出去的链接
	private String toOtherUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.SHARE_ICON_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String shareIconUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_CREATE_TIME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private Date informationCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_UPDATE_TIME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private Date informationUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.BROWSE_COUNT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private Integer browseCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.SHARE_COUNT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private Integer shareCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_CREATE_USER
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String informationCreateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_UPDATE_USER
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String informationUpdateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.VIDEO_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String videoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.VIDEO_TITLE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String videoTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.VIDEO_ICON_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String videoIconUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_TYPE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String informationType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_STATUS
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private Integer informationStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_IS_RECOMMEND
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private Integer informationIsRecommend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.INFORMATION_CONTENT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String informationContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.BIG_IMAGE_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String bigImageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information.BIG_IMAGE_CONTEXT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	private String bigImageContext;

	/**
	 * 资讯模块ID
	 */
	private String informationModuleId;

	public String getInformationModuleId() {
		return informationModuleId;
	}

	public void setInformationModuleId(String informationModuleId) {
		this.informationModuleId = informationModuleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_ID
	 * @return  the value of ccp_information.INFORMATION_ID
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getInformationId() {
		return informationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_ID
	 * @param informationId  the value for ccp_information.INFORMATION_ID
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationId(String informationId) {
		this.informationId = informationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_TITLE
	 * @return  the value of ccp_information.INFORMATION_TITLE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getInformationTitle() {
		return informationTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_TITLE
	 * @param informationTitle  the value for ccp_information.INFORMATION_TITLE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationTitle(String informationTitle) {
		this.informationTitle = informationTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.AUTHOR_NAME
	 * @return  the value of ccp_information.AUTHOR_NAME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getAuthorName() {
		return authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.AUTHOR_NAME
	 * @param authorName  the value for ccp_information.AUTHOR_NAME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.PUBLISHER_NAME
	 * @return  the value of ccp_information.PUBLISHER_NAME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getPublisherName() {
		return publisherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.PUBLISHER_NAME
	 * @param publisherName  the value for ccp_information.PUBLISHER_NAME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_SORT
	 * @return  the value of ccp_information.INFORMATION_SORT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public Integer getInformationSort() {
		return informationSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_SORT
	 * @param informationSort  the value for ccp_information.INFORMATION_SORT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationSort(Integer informationSort) {
		this.informationSort = informationSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_TAGS
	 * @return  the value of ccp_information.INFORMATION_TAGS
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getInformationTags() {
		return informationTags;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_TAGS
	 * @param informationTags  the value for ccp_information.INFORMATION_TAGS
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationTags(String informationTags) {
		this.informationTags = informationTags;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.SHARE_TITLE
	 * @return  the value of ccp_information.SHARE_TITLE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getShareTitle() {
		return shareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.SHARE_TITLE
	 * @param shareTitle  the value for ccp_information.SHARE_TITLE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setShareTitle(String shareTitle) {
		this.shareTitle = shareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.SHARE_SUMMARY
	 * @return  the value of ccp_information.SHARE_SUMMARY
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getShareSummary() {
		return shareSummary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.SHARE_SUMMARY
	 * @param shareSummary  the value for ccp_information.SHARE_SUMMARY
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setShareSummary(String shareSummary) {
		this.shareSummary = shareSummary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_ICON_URL
	 * @return  the value of ccp_information.INFORMATION_ICON_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getInformationIconUrl() {
		return informationIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_ICON_URL
	 * @param informationIconUrl  the value for ccp_information.INFORMATION_ICON_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationIconUrl(String informationIconUrl) {
		this.informationIconUrl = informationIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.SHARE_ICON_URL
	 * @return  the value of ccp_information.SHARE_ICON_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getShareIconUrl() {
		return shareIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.SHARE_ICON_URL
	 * @param shareIconUrl  the value for ccp_information.SHARE_ICON_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setShareIconUrl(String shareIconUrl) {
		this.shareIconUrl = shareIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_CREATE_TIME
	 * @return  the value of ccp_information.INFORMATION_CREATE_TIME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public Date getInformationCreateTime() {
		return informationCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_CREATE_TIME
	 * @param informationCreateTime  the value for ccp_information.INFORMATION_CREATE_TIME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationCreateTime(Date informationCreateTime) {
		this.informationCreateTime = informationCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_UPDATE_TIME
	 * @return  the value of ccp_information.INFORMATION_UPDATE_TIME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public Date getInformationUpdateTime() {
		return informationUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_UPDATE_TIME
	 * @param informationUpdateTime  the value for ccp_information.INFORMATION_UPDATE_TIME
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationUpdateTime(Date informationUpdateTime) {
		this.informationUpdateTime = informationUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.BROWSE_COUNT
	 * @return  the value of ccp_information.BROWSE_COUNT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public Integer getBrowseCount() {
		return browseCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.BROWSE_COUNT
	 * @param browseCount  the value for ccp_information.BROWSE_COUNT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setBrowseCount(Integer browseCount) {
		this.browseCount = browseCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.SHARE_COUNT
	 * @return  the value of ccp_information.SHARE_COUNT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public Integer getShareCount() {
		return shareCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.SHARE_COUNT
	 * @param shareCount  the value for ccp_information.SHARE_COUNT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setShareCount(Integer shareCount) {
		this.shareCount = shareCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_CREATE_USER
	 * @return  the value of ccp_information.INFORMATION_CREATE_USER
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getInformationCreateUser() {
		return informationCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_CREATE_USER
	 * @param informationCreateUser  the value for ccp_information.INFORMATION_CREATE_USER
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationCreateUser(String informationCreateUser) {
		this.informationCreateUser = informationCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_UPDATE_USER
	 * @return  the value of ccp_information.INFORMATION_UPDATE_USER
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getInformationUpdateUser() {
		return informationUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_UPDATE_USER
	 * @param informationUpdateUser  the value for ccp_information.INFORMATION_UPDATE_USER
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationUpdateUser(String informationUpdateUser) {
		this.informationUpdateUser = informationUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.VIDEO_URL
	 * @return  the value of ccp_information.VIDEO_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getVideoUrl() {
		return videoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.VIDEO_URL
	 * @param videoUrl  the value for ccp_information.VIDEO_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.VIDEO_TITLE
	 * @return  the value of ccp_information.VIDEO_TITLE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getVideoTitle() {
		return videoTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.VIDEO_TITLE
	 * @param videoTitle  the value for ccp_information.VIDEO_TITLE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setVideoTitle(String videoTitle) {
		this.videoTitle = videoTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.VIDEO_ICON_URL
	 * @return  the value of ccp_information.VIDEO_ICON_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getVideoIconUrl() {
		return videoIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.VIDEO_ICON_URL
	 * @param videoIconUrl  the value for ccp_information.VIDEO_ICON_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setVideoIconUrl(String videoIconUrl) {
		this.videoIconUrl = videoIconUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_TYPE
	 * @return  the value of ccp_information.INFORMATION_TYPE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getInformationType() {
		return informationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_TYPE
	 * @param informationType  the value for ccp_information.INFORMATION_TYPE
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationType(String informationType) {
		this.informationType = informationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_STATUS
	 * @return  the value of ccp_information.INFORMATION_STATUS
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public Integer getInformationStatus() {
		return informationStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_STATUS
	 * @param informationStatus  the value for ccp_information.INFORMATION_STATUS
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationStatus(Integer informationStatus) {
		this.informationStatus = informationStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_IS_RECOMMEND
	 * @return  the value of ccp_information.INFORMATION_IS_RECOMMEND
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public Integer getInformationIsRecommend() {
		return informationIsRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_IS_RECOMMEND
	 * @param informationIsRecommend  the value for ccp_information.INFORMATION_IS_RECOMMEND
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationIsRecommend(Integer informationIsRecommend) {
		this.informationIsRecommend = informationIsRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.INFORMATION_CONTENT
	 * @return  the value of ccp_information.INFORMATION_CONTENT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getInformationContent() {
		return informationContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.INFORMATION_CONTENT
	 * @param informationContent  the value for ccp_information.INFORMATION_CONTENT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setInformationContent(String informationContent) {
		this.informationContent = informationContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.BIG_IMAGE_URL
	 * @return  the value of ccp_information.BIG_IMAGE_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getBigImageUrl() {
		return bigImageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.BIG_IMAGE_URL
	 * @param bigImageUrl  the value for ccp_information.BIG_IMAGE_URL
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setBigImageUrl(String bigImageUrl) {
		this.bigImageUrl = bigImageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information.BIG_IMAGE_CONTEXT
	 * @return  the value of ccp_information.BIG_IMAGE_CONTEXT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public String getBigImageContext() {
		return bigImageContext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information.BIG_IMAGE_CONTEXT
	 * @param bigImageContext  the value for ccp_information.BIG_IMAGE_CONTEXT
	 * @mbggenerated  Thu Aug 03 21:10:53 CST 2017
	 */
	public void setBigImageContext(String bigImageContext) {
		this.bigImageContext = bigImageContext;
	}

	public String getToOtherUrl() {
		return toOtherUrl;
	}

	public void setToOtherUrl(String toOtherUrl) {
		this.toOtherUrl = toOtherUrl;
	}
}