package com.culturecloud.model.bean.common;

import java.util.Date;

public class CcpInformationType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information_type.INFORMATION_TYPE_ID
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	private String informationTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information_type.TYPE_NAME
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information_type.TYPE_CREATE_USER
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	private String typeCreateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information_type.TYPE_UPDATE_USER
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	private String typeUpdateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information_type.TYPE_CREATE_TIME
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	private Date typeCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_information_type.TYPE_UPDATE_TIME
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	private Date typeUpdateTime;

	/**
	 * 资讯模块ID
	 */
	private String informationModuleId;
	
	private String typeParentId;
	
	private String typeRelateId;

	public String getInformationModuleId() {
		return informationModuleId;
	}

	public void setInformationModuleId(String informationModuleId) {
		this.informationModuleId = informationModuleId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information_type.INFORMATION_TYPE_ID
	 * @return  the value of ccp_information_type.INFORMATION_TYPE_ID
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public String getInformationTypeId() {
		return informationTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information_type.INFORMATION_TYPE_ID
	 * @param informationTypeId  the value for ccp_information_type.INFORMATION_TYPE_ID
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public void setInformationTypeId(String informationTypeId) {
		this.informationTypeId = informationTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information_type.TYPE_NAME
	 * @return  the value of ccp_information_type.TYPE_NAME
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information_type.TYPE_NAME
	 * @param typeName  the value for ccp_information_type.TYPE_NAME
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information_type.TYPE_CREATE_USER
	 * @return  the value of ccp_information_type.TYPE_CREATE_USER
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public String getTypeCreateUser() {
		return typeCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information_type.TYPE_CREATE_USER
	 * @param typeCreateUser  the value for ccp_information_type.TYPE_CREATE_USER
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public void setTypeCreateUser(String typeCreateUser) {
		this.typeCreateUser = typeCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information_type.TYPE_UPDATE_USER
	 * @return  the value of ccp_information_type.TYPE_UPDATE_USER
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public String getTypeUpdateUser() {
		return typeUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information_type.TYPE_UPDATE_USER
	 * @param typeUpdateUser  the value for ccp_information_type.TYPE_UPDATE_USER
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public void setTypeUpdateUser(String typeUpdateUser) {
		this.typeUpdateUser = typeUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information_type.TYPE_CREATE_TIME
	 * @return  the value of ccp_information_type.TYPE_CREATE_TIME
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public Date getTypeCreateTime() {
		return typeCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information_type.TYPE_CREATE_TIME
	 * @param typeCreateTime  the value for ccp_information_type.TYPE_CREATE_TIME
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public void setTypeCreateTime(Date typeCreateTime) {
		this.typeCreateTime = typeCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_information_type.TYPE_UPDATE_TIME
	 * @return  the value of ccp_information_type.TYPE_UPDATE_TIME
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public Date getTypeUpdateTime() {
		return typeUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_information_type.TYPE_UPDATE_TIME
	 * @param typeUpdateTime  the value for ccp_information_type.TYPE_UPDATE_TIME
	 * @mbggenerated  Tue Aug 01 19:49:51 CST 2017
	 */
	public void setTypeUpdateTime(Date typeUpdateTime) {
		this.typeUpdateTime = typeUpdateTime;
	}

	public String getTypeParentId() {
		return typeParentId;
	}

	public void setTypeParentId(String typeParentId) {
		this.typeParentId = typeParentId;
	}

	public String getTypeRelateId() {
		return typeRelateId;
	}

	public void setTypeRelateId(String typeRelateId) {
		this.typeRelateId = typeRelateId;
	}
	
}