package com.culturecloud.model.bean.common;

public class CmsTagSubRelate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag_sub_relate.TAG_SUB_ID
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    private String tagSubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag_sub_relate.RELATE_ID
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    private String relateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag_sub_relate.TYPE
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag_sub_relate.RELATE_TYPE
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    private String relateType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub_relate.TAG_SUB_ID
     *
     * @return the value of cms_tag_sub_relate.TAG_SUB_ID
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    public String getTagSubId() {
        return tagSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub_relate.TAG_SUB_ID
     *
     * @param tagSubId the value for cms_tag_sub_relate.TAG_SUB_ID
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    public void setTagSubId(String tagSubId) {
        this.tagSubId = tagSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub_relate.RELATE_ID
     *
     * @return the value of cms_tag_sub_relate.RELATE_ID
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    public String getRelateId() {
        return relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub_relate.RELATE_ID
     *
     * @param relateId the value for cms_tag_sub_relate.RELATE_ID
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    public void setRelateId(String relateId) {
        this.relateId = relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub_relate.TYPE
     *
     * @return the value of cms_tag_sub_relate.TYPE
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub_relate.TYPE
     *
     * @param type the value for cms_tag_sub_relate.TYPE
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub_relate.RELATE_TYPE
     *
     * @return the value of cms_tag_sub_relate.RELATE_TYPE
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    public String getRelateType() {
        return relateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub_relate.RELATE_TYPE
     *
     * @param relateType the value for cms_tag_sub_relate.RELATE_TYPE
     *
     * @mbggenerated Wed Aug 10 14:56:58 CST 2016
     */
    public void setRelateType(String relateType) {
        this.relateType = relateType;
    }
}