package com.culturecloud.model.bean.common;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

import javax.persistence.Column;
import java.util.Date;
@Table(value="cms_tag")
public class CmsTag implements BaseEntity {

    private static final long serialVersionUID = -3586841585989510841L;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_ID
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Id
    @Column(name="TAG_ID")
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_NAME
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_NAME")
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_TYPE
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_TYPE")
    private String tagType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_SEARCH_STR
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_SEARCH_STR")
    private String tagSearchStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_CREATE_USER
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_CREATE_USER")
    private String tagCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_CREATE_TIME")
    private Date tagCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_UPDATE_USER")
    private String tagUpdateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_UPDATE_TIME")
    private Date tagUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_DEPT
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_DEPT")
    private String tagDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_IS_DELETE
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_IS_DELETE")
    private Integer tagIsDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_IMAGE_URL
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_IMAGE_URL")
    private String tagImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_RECOMMEND
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_RECOMMEND")
    private Integer tagRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_COLOR
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_COLOR")
    private String tagColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_tag.TAG_INITIAL
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    @Column(name="TAG_INITIAL")
    private String tagInitial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_ID
     *
     * @return the value of cms_tag.TAG_ID
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_ID
     *
     * @param tagId the value for cms_tag.TAG_ID
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagId(String tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_NAME
     *
     * @return the value of cms_tag.TAG_NAME
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_NAME
     *
     * @param tagName the value for cms_tag.TAG_NAME
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_TYPE
     *
     * @return the value of cms_tag.TAG_TYPE
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagType() {
        return tagType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_TYPE
     *
     * @param tagType the value for cms_tag.TAG_TYPE
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagType(String tagType) {
        this.tagType = tagType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_SEARCH_STR
     *
     * @return the value of cms_tag.TAG_SEARCH_STR
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagSearchStr() {
        return tagSearchStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_SEARCH_STR
     *
     * @param tagSearchStr the value for cms_tag.TAG_SEARCH_STR
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagSearchStr(String tagSearchStr) {
        this.tagSearchStr = tagSearchStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_CREATE_USER
     *
     * @return the value of cms_tag.TAG_CREATE_USER
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagCreateUser() {
        return tagCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_CREATE_USER
     *
     * @param tagCreateUser the value for cms_tag.TAG_CREATE_USER
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagCreateUser(String tagCreateUser) {
        this.tagCreateUser = tagCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_CREATE_TIME
     *
     * @return the value of cms_tag.TAG_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public Date getTagCreateTime() {
        return tagCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_CREATE_TIME
     *
     * @param tagCreateTime the value for cms_tag.TAG_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagCreateTime(Date tagCreateTime) {
        this.tagCreateTime = tagCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_UPDATE_USER
     *
     * @return the value of cms_tag.TAG_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagUpdateUser() {
        return tagUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_UPDATE_USER
     *
     * @param tagUpdateUser the value for cms_tag.TAG_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagUpdateUser(String tagUpdateUser) {
        this.tagUpdateUser = tagUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_UPDATE_TIME
     *
     * @return the value of cms_tag.TAG_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public Date getTagUpdateTime() {
        return tagUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_UPDATE_TIME
     *
     * @param tagUpdateTime the value for cms_tag.TAG_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagUpdateTime(Date tagUpdateTime) {
        this.tagUpdateTime = tagUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_DEPT
     *
     * @return the value of cms_tag.TAG_DEPT
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagDept() {
        return tagDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_DEPT
     *
     * @param tagDept the value for cms_tag.TAG_DEPT
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagDept(String tagDept) {
        this.tagDept = tagDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_IS_DELETE
     *
     * @return the value of cms_tag.TAG_IS_DELETE
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public Integer getTagIsDelete() {
        return tagIsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_IS_DELETE
     *
     * @param tagIsDelete the value for cms_tag.TAG_IS_DELETE
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagIsDelete(Integer tagIsDelete) {
        this.tagIsDelete = tagIsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_IMAGE_URL
     *
     * @return the value of cms_tag.TAG_IMAGE_URL
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagImageUrl() {
        return tagImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_IMAGE_URL
     *
     * @param tagImageUrl the value for cms_tag.TAG_IMAGE_URL
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagImageUrl(String tagImageUrl) {
        this.tagImageUrl = tagImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_RECOMMEND
     *
     * @return the value of cms_tag.TAG_RECOMMEND
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public Integer getTagRecommend() {
        return tagRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_RECOMMEND
     *
     * @param tagRecommend the value for cms_tag.TAG_RECOMMEND
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagRecommend(Integer tagRecommend) {
        this.tagRecommend = tagRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_COLOR
     *
     * @return the value of cms_tag.TAG_COLOR
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagColor() {
        return tagColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_COLOR
     *
     * @param tagColor the value for cms_tag.TAG_COLOR
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagColor(String tagColor) {
        this.tagColor = tagColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag.TAG_INITIAL
     *
     * @return the value of cms_tag.TAG_INITIAL
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public String getTagInitial() {
        return tagInitial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag.TAG_INITIAL
     *
     * @param tagInitial the value for cms_tag.TAG_INITIAL
     *
     * @mbggenerated Mon Jul 25 16:42:06 CST 2016
     */
    public void setTagInitial(String tagInitial) {
        this.tagInitial = tagInitial;
    }
}