package com.culturecloud.model.bean.common;

import java.util.Date;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table(value="cms_tag_sub")
public class CmsTagSub implements BaseEntity{
	
	private static final long serialVersionUID = -760404506082664115L;

	@Id
	@Column(name="TAG_SUB_ID")
    private String tagSubId;

	@Column(name="TAG_NAME")
    private String tagName;

	@Column(name="TAG_CREATE_USER")
    private String tagCreateUser;

	@Column(name="TAG_CREATE_TIME")
    private Date tagCreateTime;

	@Column(name="TAG_UPDATE_USER")
    private String tagUpdateUser;

    @Column(name="TAG_UPDATE_TIME")
    private Date tagUpdateTime;

   @Column(name="TAG_IS_DELETE")
    private Integer tagIsDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub.TAG_SUB_ID
     *
     * @return the value of cms_tag_sub.TAG_SUB_ID
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public String getTagSubId() {
        return tagSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub.TAG_SUB_ID
     *
     * @param tagSubId the value for cms_tag_sub.TAG_SUB_ID
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public void setTagSubId(String tagSubId) {
        this.tagSubId = tagSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub.TAG_NAME
     *
     * @return the value of cms_tag_sub.TAG_NAME
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub.TAG_NAME
     *
     * @param tagName the value for cms_tag_sub.TAG_NAME
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub.TAG_CREATE_USER
     *
     * @return the value of cms_tag_sub.TAG_CREATE_USER
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public String getTagCreateUser() {
        return tagCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub.TAG_CREATE_USER
     *
     * @param tagCreateUser the value for cms_tag_sub.TAG_CREATE_USER
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public void setTagCreateUser(String tagCreateUser) {
        this.tagCreateUser = tagCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub.TAG_CREATE_TIME
     *
     * @return the value of cms_tag_sub.TAG_CREATE_TIME
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public Date getTagCreateTime() {
        return tagCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub.TAG_CREATE_TIME
     *
     * @param tagCreateTime the value for cms_tag_sub.TAG_CREATE_TIME
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public void setTagCreateTime(Date tagCreateTime) {
        this.tagCreateTime = tagCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub.TAG_UPDATE_USER
     *
     * @return the value of cms_tag_sub.TAG_UPDATE_USER
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public String getTagUpdateUser() {
        return tagUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub.TAG_UPDATE_USER
     *
     * @param tagUpdateUser the value for cms_tag_sub.TAG_UPDATE_USER
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public void setTagUpdateUser(String tagUpdateUser) {
        this.tagUpdateUser = tagUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub.TAG_UPDATE_TIME
     *
     * @return the value of cms_tag_sub.TAG_UPDATE_TIME
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public Date getTagUpdateTime() {
        return tagUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub.TAG_UPDATE_TIME
     *
     * @param tagUpdateTime the value for cms_tag_sub.TAG_UPDATE_TIME
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public void setTagUpdateTime(Date tagUpdateTime) {
        this.tagUpdateTime = tagUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_tag_sub.TAG_IS_DELETE
     *
     * @return the value of cms_tag_sub.TAG_IS_DELETE
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public Integer getTagIsDelete() {
        return tagIsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_tag_sub.TAG_IS_DELETE
     *
     * @param tagIsDelete the value for cms_tag_sub.TAG_IS_DELETE
     *
     * @mbggenerated Wed Aug 10 15:00:19 CST 2016
     */
    public void setTagIsDelete(Integer tagIsDelete) {
        this.tagIsDelete = tagIsDelete;
    }
}