package com.culturecloud.model.bean.common;

import java.util.Date;

public class SysSmsStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sms_statistics.sms_id
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    private String smsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sms_statistics.statistics_day
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    private Date statisticsDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sms_statistics.send_num
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    private Integer sendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_sms_statistics.threshold_num
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    private Integer thresholdNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sms_statistics.sms_id
     *
     * @return the value of sys_sms_statistics.sms_id
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    public String getSmsId() {
        return smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sms_statistics.sms_id
     *
     * @param smsId the value for sys_sms_statistics.sms_id
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    public void setSmsId(String smsId) {
        this.smsId = smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sms_statistics.statistics_day
     *
     * @return the value of sys_sms_statistics.statistics_day
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    public Date getStatisticsDay() {
        return statisticsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sms_statistics.statistics_day
     *
     * @param statisticsDay the value for sys_sms_statistics.statistics_day
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    public void setStatisticsDay(Date statisticsDay) {
        this.statisticsDay = statisticsDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sms_statistics.send_num
     *
     * @return the value of sys_sms_statistics.send_num
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    public Integer getSendNum() {
        return sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sms_statistics.send_num
     *
     * @param sendNum the value for sys_sms_statistics.send_num
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    public void setSendNum(Integer sendNum) {
        this.sendNum = sendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_sms_statistics.threshold_num
     *
     * @return the value of sys_sms_statistics.threshold_num
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    public Integer getThresholdNum() {
        return thresholdNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_sms_statistics.threshold_num
     *
     * @param thresholdNum the value for sys_sms_statistics.threshold_num
     *
     * @mbggenerated Thu May 04 16:54:35 CST 2017
     */
    public void setThresholdNum(Integer thresholdNum) {
        this.thresholdNum = thresholdNum;
    }
}