package com.sun3d.why.model.qyg;

import java.io.Serializable;
import java.util.Date;


public class QygProjectEntry implements Serializable{
	private static final long serialVersionUID = 2457243226198785250L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_id
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String entryId;
	
	private String projectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.project_type
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer projectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.company_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.linkman
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String linkman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.telephone
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.email
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_subject
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String entrySubject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.project_profile
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String projectProfile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.primary_performer
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer primaryPerformer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.secondary_performer
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer secondaryPerformer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.staff
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer staff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.is_band
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer isBand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.is_color_sing
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer isColorSing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.is_beauty_dance
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer isBeautyDance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.is_large_prop
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer isLargeProp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_index
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer entryIndex;
	
	private String lectureTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.scheme_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String schemeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.video_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String videoName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.video_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String videoTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_create_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Date entryCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_create_user
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String entryCreateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_update_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Date entryUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_update_user
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String entryUpdateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_complete_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Date entryCompleteTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_is_complete
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer entryIsComplete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.entry_is_delete
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer entryIsDelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.technical_check
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer technicalCheck;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.content_check
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer contentCheck;
	
	private String speakerName;

	private String suitableCrowd;
	
	private String supportingActivityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.arrange_exhibitions_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String arrangeExhibitionsTime;
	
	private String supportingActivityTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.minimum_unfold_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String minimumUnfoldNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.max_unfold_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String maxUnfoldNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.exhibit_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer exhibitNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.panel_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer panelNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.routine_maintenance
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer routineMaintenance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.auction_calendar_copy
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private Integer auctionCalendarCopy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.declaration_category
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String declarationCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.fixed_telephone
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String fixedTelephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.company_detail
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String companyDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.company_performance
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String companyPerformance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.copyright
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String copyright;
	
	private String entryDescription;
	
	private String stageSize;
	
	
	private String lighting;
	
	
	private String sound;


	private String projection;

	
	private String rest;

	private String voiceTube;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.design_scheme
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String designScheme;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.stage_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String stageImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.stage_img_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String stageImgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.poster_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String posterImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.poster_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String posterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.video_url
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String videoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.video_cover_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String videoCoverImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.video_introduction
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String videoIntroduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.speaker_identity
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String speakerIdentity;
	
	private String topicPurport;
	
	private String exhibitionOutline;
	
	private String exhibitionIntroduction;
	
	private String supportingActivity;

	private String activityTarget;
	
	private String interactiveMode;
	
	private String teachingExperience;

	private String learningBackground;
	
	private String teachingMaterial;

	private String supplie;
	
	private String supportingActivityContent;
	
	private String specialDesign;
	
	private String texture;

	private String measure;
	
	private String stageClassroom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.community_recommend
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String communityRecommend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.business_license
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String businessLicense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.performance_license
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String performanceLicense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.activity_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String activityImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.loading_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String loadingTime;
	
	private String logisticsScale;

	private String showSchedule;
	
	private String otherInstruction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.exhibition_impression_drawing
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String exhibitionImpressionDrawing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.exhibition_impression_drawing_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String exhibitionImpressionDrawingName;
	
    private String quality;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column qyg_project_entry.supplie_num
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	private String supplieNum;
	
	private String derrick;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_id
	 * @return  the value of qyg_project_entry.entry_id
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getEntryId() {
		return entryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_id
	 * @param entryId  the value for qyg_project_entry.entry_id
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryId(String entryId) {
		this.entryId = entryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.project_name
	 * @return  the value of qyg_project_entry.project_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.project_name
	 * @param projectName  the value for qyg_project_entry.project_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.project_type
	 * @return  the value of qyg_project_entry.project_type
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getProjectType() {
		return projectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.project_type
	 * @param projectType  the value for qyg_project_entry.project_type
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setProjectType(Integer projectType) {
		this.projectType = projectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.company_name
	 * @return  the value of qyg_project_entry.company_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.company_name
	 * @param companyName  the value for qyg_project_entry.company_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.linkman
	 * @return  the value of qyg_project_entry.linkman
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.linkman
	 * @param linkman  the value for qyg_project_entry.linkman
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.telephone
	 * @return  the value of qyg_project_entry.telephone
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.telephone
	 * @param telephone  the value for qyg_project_entry.telephone
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.email
	 * @return  the value of qyg_project_entry.email
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.email
	 * @param email  the value for qyg_project_entry.email
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_subject
	 * @return  the value of qyg_project_entry.entry_subject
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getEntrySubject() {
		return entrySubject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_subject
	 * @param entrySubject  the value for qyg_project_entry.entry_subject
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntrySubject(String entrySubject) {
		this.entrySubject = entrySubject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.project_profile
	 * @return  the value of qyg_project_entry.project_profile
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getProjectProfile() {
		return projectProfile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.project_profile
	 * @param projectProfile  the value for qyg_project_entry.project_profile
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setProjectProfile(String projectProfile) {
		this.projectProfile = projectProfile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.primary_performer
	 * @return  the value of qyg_project_entry.primary_performer
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getPrimaryPerformer() {
		return primaryPerformer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.primary_performer
	 * @param primaryPerformer  the value for qyg_project_entry.primary_performer
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setPrimaryPerformer(Integer primaryPerformer) {
		this.primaryPerformer = primaryPerformer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.secondary_performer
	 * @return  the value of qyg_project_entry.secondary_performer
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getSecondaryPerformer() {
		return secondaryPerformer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.secondary_performer
	 * @param secondaryPerformer  the value for qyg_project_entry.secondary_performer
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSecondaryPerformer(Integer secondaryPerformer) {
		this.secondaryPerformer = secondaryPerformer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.staff
	 * @return  the value of qyg_project_entry.staff
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getStaff() {
		return staff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.staff
	 * @param staff  the value for qyg_project_entry.staff
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setStaff(Integer staff) {
		this.staff = staff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.is_band
	 * @return  the value of qyg_project_entry.is_band
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getIsBand() {
		return isBand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.is_band
	 * @param isBand  the value for qyg_project_entry.is_band
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setIsBand(Integer isBand) {
		this.isBand = isBand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.is_color_sing
	 * @return  the value of qyg_project_entry.is_color_sing
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getIsColorSing() {
		return isColorSing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.is_color_sing
	 * @param isColorSing  the value for qyg_project_entry.is_color_sing
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setIsColorSing(Integer isColorSing) {
		this.isColorSing = isColorSing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.is_beauty_dance
	 * @return  the value of qyg_project_entry.is_beauty_dance
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getIsBeautyDance() {
		return isBeautyDance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.is_beauty_dance
	 * @param isBeautyDance  the value for qyg_project_entry.is_beauty_dance
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setIsBeautyDance(Integer isBeautyDance) {
		this.isBeautyDance = isBeautyDance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.is_large_prop
	 * @return  the value of qyg_project_entry.is_large_prop
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getIsLargeProp() {
		return isLargeProp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.is_large_prop
	 * @param isLargeProp  the value for qyg_project_entry.is_large_prop
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setIsLargeProp(Integer isLargeProp) {
		this.isLargeProp = isLargeProp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_index
	 * @return  the value of qyg_project_entry.entry_index
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getEntryIndex() {
		return entryIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_index
	 * @param entryIndex  the value for qyg_project_entry.entry_index
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryIndex(Integer entryIndex) {
		this.entryIndex = entryIndex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.lecture_time
	 * @return  the value of qyg_project_entry.lecture_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getLectureTime() {
		return lectureTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.lecture_time
	 * @param lectureTime  the value for qyg_project_entry.lecture_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setLectureTime(String lectureTime) {
		this.lectureTime = lectureTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.scheme_name
	 * @return  the value of qyg_project_entry.scheme_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSchemeName() {
		return schemeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.scheme_name
	 * @param schemeName  the value for qyg_project_entry.scheme_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSchemeName(String schemeName) {
		this.schemeName = schemeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.video_name
	 * @return  the value of qyg_project_entry.video_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getVideoName() {
		return videoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.video_name
	 * @param videoName  the value for qyg_project_entry.video_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setVideoName(String videoName) {
		this.videoName = videoName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.video_time
	 * @return  the value of qyg_project_entry.video_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getVideoTime() {
		return videoTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.video_time
	 * @param videoTime  the value for qyg_project_entry.video_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setVideoTime(String videoTime) {
		this.videoTime = videoTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_create_time
	 * @return  the value of qyg_project_entry.entry_create_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Date getEntryCreateTime() {
		return entryCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_create_time
	 * @param entryCreateTime  the value for qyg_project_entry.entry_create_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryCreateTime(Date entryCreateTime) {
		this.entryCreateTime = entryCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_create_user
	 * @return  the value of qyg_project_entry.entry_create_user
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getEntryCreateUser() {
		return entryCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_create_user
	 * @param entryCreateUser  the value for qyg_project_entry.entry_create_user
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryCreateUser(String entryCreateUser) {
		this.entryCreateUser = entryCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_update_time
	 * @return  the value of qyg_project_entry.entry_update_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Date getEntryUpdateTime() {
		return entryUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_update_time
	 * @param entryUpdateTime  the value for qyg_project_entry.entry_update_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryUpdateTime(Date entryUpdateTime) {
		this.entryUpdateTime = entryUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_update_user
	 * @return  the value of qyg_project_entry.entry_update_user
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getEntryUpdateUser() {
		return entryUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_update_user
	 * @param entryUpdateUser  the value for qyg_project_entry.entry_update_user
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryUpdateUser(String entryUpdateUser) {
		this.entryUpdateUser = entryUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_complete_time
	 * @return  the value of qyg_project_entry.entry_complete_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Date getEntryCompleteTime() {
		return entryCompleteTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_complete_time
	 * @param entryCompleteTime  the value for qyg_project_entry.entry_complete_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryCompleteTime(Date entryCompleteTime) {
		this.entryCompleteTime = entryCompleteTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_is_complete
	 * @return  the value of qyg_project_entry.entry_is_complete
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getEntryIsComplete() {
		return entryIsComplete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_is_complete
	 * @param entryIsComplete  the value for qyg_project_entry.entry_is_complete
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryIsComplete(Integer entryIsComplete) {
		this.entryIsComplete = entryIsComplete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_is_delete
	 * @return  the value of qyg_project_entry.entry_is_delete
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getEntryIsDelete() {
		return entryIsDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_is_delete
	 * @param entryIsDelete  the value for qyg_project_entry.entry_is_delete
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryIsDelete(Integer entryIsDelete) {
		this.entryIsDelete = entryIsDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.technical_check
	 * @return  the value of qyg_project_entry.technical_check
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getTechnicalCheck() {
		return technicalCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.technical_check
	 * @param technicalCheck  the value for qyg_project_entry.technical_check
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setTechnicalCheck(Integer technicalCheck) {
		this.technicalCheck = technicalCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.content_check
	 * @return  the value of qyg_project_entry.content_check
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getContentCheck() {
		return contentCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.content_check
	 * @param contentCheck  the value for qyg_project_entry.content_check
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setContentCheck(Integer contentCheck) {
		this.contentCheck = contentCheck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.speaker_name
	 * @return  the value of qyg_project_entry.speaker_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSpeakerName() {
		return speakerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.speaker_name
	 * @param speakerName  the value for qyg_project_entry.speaker_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSpeakerName(String speakerName) {
		this.speakerName = speakerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.suitable_crowd
	 * @return  the value of qyg_project_entry.suitable_crowd
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSuitableCrowd() {
		return suitableCrowd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.suitable_crowd
	 * @param suitableCrowd  the value for qyg_project_entry.suitable_crowd
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSuitableCrowd(String suitableCrowd) {
		this.suitableCrowd = suitableCrowd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.supporting_activity_name
	 * @return  the value of qyg_project_entry.supporting_activity_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSupportingActivityName() {
		return supportingActivityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.supporting_activity_name
	 * @param supportingActivityName  the value for qyg_project_entry.supporting_activity_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSupportingActivityName(String supportingActivityName) {
		this.supportingActivityName = supportingActivityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.arrange_exhibitions_time
	 * @return  the value of qyg_project_entry.arrange_exhibitions_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getArrangeExhibitionsTime() {
		return arrangeExhibitionsTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.arrange_exhibitions_time
	 * @param arrangeExhibitionsTime  the value for qyg_project_entry.arrange_exhibitions_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setArrangeExhibitionsTime(String arrangeExhibitionsTime) {
		this.arrangeExhibitionsTime = arrangeExhibitionsTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.supporting_activity_time
	 * @return  the value of qyg_project_entry.supporting_activity_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSupportingActivityTime() {
		return supportingActivityTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.supporting_activity_time
	 * @param supportingActivityTime  the value for qyg_project_entry.supporting_activity_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSupportingActivityTime(String supportingActivityTime) {
		this.supportingActivityTime = supportingActivityTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.minimum_unfold_number
	 * @return  the value of qyg_project_entry.minimum_unfold_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getMinimumUnfoldNumber() {
		return minimumUnfoldNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.minimum_unfold_number
	 * @param minimumUnfoldNumber  the value for qyg_project_entry.minimum_unfold_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setMinimumUnfoldNumber(String minimumUnfoldNumber) {
		this.minimumUnfoldNumber = minimumUnfoldNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.max_unfold_number
	 * @return  the value of qyg_project_entry.max_unfold_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getMaxUnfoldNumber() {
		return maxUnfoldNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.max_unfold_number
	 * @param maxUnfoldNumber  the value for qyg_project_entry.max_unfold_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setMaxUnfoldNumber(String maxUnfoldNumber) {
		this.maxUnfoldNumber = maxUnfoldNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.exhibit_number
	 * @return  the value of qyg_project_entry.exhibit_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getExhibitNumber() {
		return exhibitNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.exhibit_number
	 * @param exhibitNumber  the value for qyg_project_entry.exhibit_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setExhibitNumber(Integer exhibitNumber) {
		this.exhibitNumber = exhibitNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.panel_number
	 * @return  the value of qyg_project_entry.panel_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getPanelNumber() {
		return panelNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.panel_number
	 * @param panelNumber  the value for qyg_project_entry.panel_number
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setPanelNumber(Integer panelNumber) {
		this.panelNumber = panelNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.routine_maintenance
	 * @return  the value of qyg_project_entry.routine_maintenance
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getRoutineMaintenance() {
		return routineMaintenance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.routine_maintenance
	 * @param routineMaintenance  the value for qyg_project_entry.routine_maintenance
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setRoutineMaintenance(Integer routineMaintenance) {
		this.routineMaintenance = routineMaintenance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.auction_calendar_copy
	 * @return  the value of qyg_project_entry.auction_calendar_copy
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public Integer getAuctionCalendarCopy() {
		return auctionCalendarCopy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.auction_calendar_copy
	 * @param auctionCalendarCopy  the value for qyg_project_entry.auction_calendar_copy
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setAuctionCalendarCopy(Integer auctionCalendarCopy) {
		this.auctionCalendarCopy = auctionCalendarCopy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.declaration_category
	 * @return  the value of qyg_project_entry.declaration_category
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getDeclarationCategory() {
		return declarationCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.declaration_category
	 * @param declarationCategory  the value for qyg_project_entry.declaration_category
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setDeclarationCategory(String declarationCategory) {
		this.declarationCategory = declarationCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.fixed_telephone
	 * @return  the value of qyg_project_entry.fixed_telephone
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getFixedTelephone() {
		return fixedTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.fixed_telephone
	 * @param fixedTelephone  the value for qyg_project_entry.fixed_telephone
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setFixedTelephone(String fixedTelephone) {
		this.fixedTelephone = fixedTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.company_detail
	 * @return  the value of qyg_project_entry.company_detail
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getCompanyDetail() {
		return companyDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.company_detail
	 * @param companyDetail  the value for qyg_project_entry.company_detail
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setCompanyDetail(String companyDetail) {
		this.companyDetail = companyDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.company_performance
	 * @return  the value of qyg_project_entry.company_performance
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getCompanyPerformance() {
		return companyPerformance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.company_performance
	 * @param companyPerformance  the value for qyg_project_entry.company_performance
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setCompanyPerformance(String companyPerformance) {
		this.companyPerformance = companyPerformance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.copyright
	 * @return  the value of qyg_project_entry.copyright
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getCopyright() {
		return copyright;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.copyright
	 * @param copyright  the value for qyg_project_entry.copyright
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setCopyright(String copyright) {
		this.copyright = copyright;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.entry_description
	 * @return  the value of qyg_project_entry.entry_description
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getEntryDescription() {
		return entryDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.entry_description
	 * @param entryDescription  the value for qyg_project_entry.entry_description
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setEntryDescription(String entryDescription) {
		this.entryDescription = entryDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.stage_size
	 * @return  the value of qyg_project_entry.stage_size
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getStageSize() {
		return stageSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.stage_size
	 * @param stageSize  the value for qyg_project_entry.stage_size
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setStageSize(String stageSize) {
		this.stageSize = stageSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.lighting
	 * @return  the value of qyg_project_entry.lighting
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getLighting() {
		return lighting;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.lighting
	 * @param lighting  the value for qyg_project_entry.lighting
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setLighting(String lighting) {
		this.lighting = lighting;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.sound
	 * @return  the value of qyg_project_entry.sound
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSound() {
		return sound;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.sound
	 * @param sound  the value for qyg_project_entry.sound
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSound(String sound) {
		this.sound = sound;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.projection
	 * @return  the value of qyg_project_entry.projection
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getProjection() {
		return projection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.projection
	 * @param projection  the value for qyg_project_entry.projection
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setProjection(String projection) {
		this.projection = projection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.rest
	 * @return  the value of qyg_project_entry.rest
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getRest() {
		return rest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.rest
	 * @param rest  the value for qyg_project_entry.rest
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setRest(String rest) {
		this.rest = rest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.voice_tube
	 * @return  the value of qyg_project_entry.voice_tube
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getVoiceTube() {
		return voiceTube;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.voice_tube
	 * @param voiceTube  the value for qyg_project_entry.voice_tube
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setVoiceTube(String voiceTube) {
		this.voiceTube = voiceTube;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.design_scheme
	 * @return  the value of qyg_project_entry.design_scheme
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getDesignScheme() {
		return designScheme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.design_scheme
	 * @param designScheme  the value for qyg_project_entry.design_scheme
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setDesignScheme(String designScheme) {
		this.designScheme = designScheme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.stage_img
	 * @return  the value of qyg_project_entry.stage_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getStageImg() {
		return stageImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.stage_img
	 * @param stageImg  the value for qyg_project_entry.stage_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setStageImg(String stageImg) {
		this.stageImg = stageImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.stage_img_name
	 * @return  the value of qyg_project_entry.stage_img_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getStageImgName() {
		return stageImgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.stage_img_name
	 * @param stageImgName  the value for qyg_project_entry.stage_img_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setStageImgName(String stageImgName) {
		this.stageImgName = stageImgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.poster_img
	 * @return  the value of qyg_project_entry.poster_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getPosterImg() {
		return posterImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.poster_img
	 * @param posterImg  the value for qyg_project_entry.poster_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setPosterImg(String posterImg) {
		this.posterImg = posterImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.poster_name
	 * @return  the value of qyg_project_entry.poster_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getPosterName() {
		return posterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.poster_name
	 * @param posterName  the value for qyg_project_entry.poster_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setPosterName(String posterName) {
		this.posterName = posterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.video_url
	 * @return  the value of qyg_project_entry.video_url
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getVideoUrl() {
		return videoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.video_url
	 * @param videoUrl  the value for qyg_project_entry.video_url
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.video_cover_img
	 * @return  the value of qyg_project_entry.video_cover_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getVideoCoverImg() {
		return videoCoverImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.video_cover_img
	 * @param videoCoverImg  the value for qyg_project_entry.video_cover_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setVideoCoverImg(String videoCoverImg) {
		this.videoCoverImg = videoCoverImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.video_introduction
	 * @return  the value of qyg_project_entry.video_introduction
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getVideoIntroduction() {
		return videoIntroduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.video_introduction
	 * @param videoIntroduction  the value for qyg_project_entry.video_introduction
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setVideoIntroduction(String videoIntroduction) {
		this.videoIntroduction = videoIntroduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.speaker_identity
	 * @return  the value of qyg_project_entry.speaker_identity
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSpeakerIdentity() {
		return speakerIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.speaker_identity
	 * @param speakerIdentity  the value for qyg_project_entry.speaker_identity
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSpeakerIdentity(String speakerIdentity) {
		this.speakerIdentity = speakerIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.topic_purport
	 * @return  the value of qyg_project_entry.topic_purport
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getTopicPurport() {
		return topicPurport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.topic_purport
	 * @param topicPurport  the value for qyg_project_entry.topic_purport
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setTopicPurport(String topicPurport) {
		this.topicPurport = topicPurport;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.exhibition_outline
	 * @return  the value of qyg_project_entry.exhibition_outline
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getExhibitionOutline() {
		return exhibitionOutline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.exhibition_outline
	 * @param exhibitionOutline  the value for qyg_project_entry.exhibition_outline
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setExhibitionOutline(String exhibitionOutline) {
		this.exhibitionOutline = exhibitionOutline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.exhibition_introduction
	 * @return  the value of qyg_project_entry.exhibition_introduction
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getExhibitionIntroduction() {
		return exhibitionIntroduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.exhibition_introduction
	 * @param exhibitionIntroduction  the value for qyg_project_entry.exhibition_introduction
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setExhibitionIntroduction(String exhibitionIntroduction) {
		this.exhibitionIntroduction = exhibitionIntroduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.supporting_activity
	 * @return  the value of qyg_project_entry.supporting_activity
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSupportingActivity() {
		return supportingActivity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.supporting_activity
	 * @param supportingActivity  the value for qyg_project_entry.supporting_activity
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSupportingActivity(String supportingActivity) {
		this.supportingActivity = supportingActivity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.activity_target
	 * @return  the value of qyg_project_entry.activity_target
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getActivityTarget() {
		return activityTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.activity_target
	 * @param activityTarget  the value for qyg_project_entry.activity_target
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setActivityTarget(String activityTarget) {
		this.activityTarget = activityTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.interactive_mode
	 * @return  the value of qyg_project_entry.interactive_mode
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getInteractiveMode() {
		return interactiveMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.interactive_mode
	 * @param interactiveMode  the value for qyg_project_entry.interactive_mode
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setInteractiveMode(String interactiveMode) {
		this.interactiveMode = interactiveMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.teaching_experience
	 * @return  the value of qyg_project_entry.teaching_experience
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getTeachingExperience() {
		return teachingExperience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.teaching_experience
	 * @param teachingExperience  the value for qyg_project_entry.teaching_experience
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setTeachingExperience(String teachingExperience) {
		this.teachingExperience = teachingExperience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.learning_background
	 * @return  the value of qyg_project_entry.learning_background
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getLearningBackground() {
		return learningBackground;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.learning_background
	 * @param learningBackground  the value for qyg_project_entry.learning_background
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setLearningBackground(String learningBackground) {
		this.learningBackground = learningBackground;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.teaching_material
	 * @return  the value of qyg_project_entry.teaching_material
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getTeachingMaterial() {
		return teachingMaterial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.teaching_material
	 * @param teachingMaterial  the value for qyg_project_entry.teaching_material
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setTeachingMaterial(String teachingMaterial) {
		this.teachingMaterial = teachingMaterial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.supplie
	 * @return  the value of qyg_project_entry.supplie
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSupplie() {
		return supplie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.supplie
	 * @param supplie  the value for qyg_project_entry.supplie
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSupplie(String supplie) {
		this.supplie = supplie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.supporting_activity_content
	 * @return  the value of qyg_project_entry.supporting_activity_content
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSupportingActivityContent() {
		return supportingActivityContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.supporting_activity_content
	 * @param supportingActivityContent  the value for qyg_project_entry.supporting_activity_content
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSupportingActivityContent(String supportingActivityContent) {
		this.supportingActivityContent = supportingActivityContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.special_design
	 * @return  the value of qyg_project_entry.special_design
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSpecialDesign() {
		return specialDesign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.special_design
	 * @param specialDesign  the value for qyg_project_entry.special_design
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSpecialDesign(String specialDesign) {
		this.specialDesign = specialDesign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.texture
	 * @return  the value of qyg_project_entry.texture
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getTexture() {
		return texture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.texture
	 * @param texture  the value for qyg_project_entry.texture
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setTexture(String texture) {
		this.texture = texture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.measure
	 * @return  the value of qyg_project_entry.measure
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getMeasure() {
		return measure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.measure
	 * @param measure  the value for qyg_project_entry.measure
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setMeasure(String measure) {
		this.measure = measure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.stage_classroom
	 * @return  the value of qyg_project_entry.stage_classroom
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getStageClassroom() {
		return stageClassroom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.stage_classroom
	 * @param stageClassroom  the value for qyg_project_entry.stage_classroom
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setStageClassroom(String stageClassroom) {
		this.stageClassroom = stageClassroom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.community_recommend
	 * @return  the value of qyg_project_entry.community_recommend
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getCommunityRecommend() {
		return communityRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.community_recommend
	 * @param communityRecommend  the value for qyg_project_entry.community_recommend
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setCommunityRecommend(String communityRecommend) {
		this.communityRecommend = communityRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.business_license
	 * @return  the value of qyg_project_entry.business_license
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getBusinessLicense() {
		return businessLicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.business_license
	 * @param businessLicense  the value for qyg_project_entry.business_license
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setBusinessLicense(String businessLicense) {
		this.businessLicense = businessLicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.performance_license
	 * @return  the value of qyg_project_entry.performance_license
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getPerformanceLicense() {
		return performanceLicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.performance_license
	 * @param performanceLicense  the value for qyg_project_entry.performance_license
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setPerformanceLicense(String performanceLicense) {
		this.performanceLicense = performanceLicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.activity_img
	 * @return  the value of qyg_project_entry.activity_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getActivityImg() {
		return activityImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.activity_img
	 * @param activityImg  the value for qyg_project_entry.activity_img
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setActivityImg(String activityImg) {
		this.activityImg = activityImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.loading_time
	 * @return  the value of qyg_project_entry.loading_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getLoadingTime() {
		return loadingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.loading_time
	 * @param loadingTime  the value for qyg_project_entry.loading_time
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setLoadingTime(String loadingTime) {
		this.loadingTime = loadingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.logistics_scale
	 * @return  the value of qyg_project_entry.logistics_scale
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getLogisticsScale() {
		return logisticsScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.logistics_scale
	 * @param logisticsScale  the value for qyg_project_entry.logistics_scale
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setLogisticsScale(String logisticsScale) {
		this.logisticsScale = logisticsScale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.show_schedule
	 * @return  the value of qyg_project_entry.show_schedule
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getShowSchedule() {
		return showSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.show_schedule
	 * @param showSchedule  the value for qyg_project_entry.show_schedule
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setShowSchedule(String showSchedule) {
		this.showSchedule = showSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.other_instruction
	 * @return  the value of qyg_project_entry.other_instruction
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getOtherInstruction() {
		return otherInstruction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.other_instruction
	 * @param otherInstruction  the value for qyg_project_entry.other_instruction
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setOtherInstruction(String otherInstruction) {
		this.otherInstruction = otherInstruction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.exhibition_impression_drawing
	 * @return  the value of qyg_project_entry.exhibition_impression_drawing
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getExhibitionImpressionDrawing() {
		return exhibitionImpressionDrawing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.exhibition_impression_drawing
	 * @param exhibitionImpressionDrawing  the value for qyg_project_entry.exhibition_impression_drawing
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setExhibitionImpressionDrawing(String exhibitionImpressionDrawing) {
		this.exhibitionImpressionDrawing = exhibitionImpressionDrawing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.exhibition_impression_drawing_name
	 * @return  the value of qyg_project_entry.exhibition_impression_drawing_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getExhibitionImpressionDrawingName() {
		return exhibitionImpressionDrawingName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.exhibition_impression_drawing_name
	 * @param exhibitionImpressionDrawingName  the value for qyg_project_entry.exhibition_impression_drawing_name
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setExhibitionImpressionDrawingName(String exhibitionImpressionDrawingName) {
		this.exhibitionImpressionDrawingName = exhibitionImpressionDrawingName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.quality
	 * @return  the value of qyg_project_entry.quality
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getQuality() {
		return quality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.quality
	 * @param quality  the value for qyg_project_entry.quality
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setQuality(String quality) {
		this.quality = quality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column qyg_project_entry.supplie_num
	 * @return  the value of qyg_project_entry.supplie_num
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public String getSupplieNum() {
		return supplieNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column qyg_project_entry.supplie_num
	 * @param supplieNum  the value for qyg_project_entry.supplie_num
	 * @mbggenerated  Sun Dec 18 20:21:53 CST 2016
	 */
	public void setSupplieNum(String supplieNum) {
		this.supplieNum = supplieNum;
	}

	public String getDerrick() {
		return derrick;
	}

	public void setDerrick(String derrick) {
		this.derrick = derrick;
	}

	
}