package com.culturecloud.model.bean.culture;

import java.util.Date;

public class CcpCultureContestUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.culture_user_id
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private String cultureUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.user_real_name
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private String userRealName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.user_telephone
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private String userTelephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.user_sex
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private Integer userSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.user_birthday
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private Date userBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.user_id
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.user_group_type
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private Integer userGroupType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.user_create_time
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private Date userCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.user_answer_time
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private Date userAnswerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_user.user_area
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	private String userArea;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.culture_user_id
	 * @return  the value of ccp_culture_contest_user.culture_user_id
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public String getCultureUserId() {
		return cultureUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.culture_user_id
	 * @param cultureUserId  the value for ccp_culture_contest_user.culture_user_id
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setCultureUserId(String cultureUserId) {
		this.cultureUserId = cultureUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.user_real_name
	 * @return  the value of ccp_culture_contest_user.user_real_name
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public String getUserRealName() {
		return userRealName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.user_real_name
	 * @param userRealName  the value for ccp_culture_contest_user.user_real_name
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setUserRealName(String userRealName) {
		this.userRealName = userRealName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.user_telephone
	 * @return  the value of ccp_culture_contest_user.user_telephone
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public String getUserTelephone() {
		return userTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.user_telephone
	 * @param userTelephone  the value for ccp_culture_contest_user.user_telephone
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setUserTelephone(String userTelephone) {
		this.userTelephone = userTelephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.user_sex
	 * @return  the value of ccp_culture_contest_user.user_sex
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public Integer getUserSex() {
		return userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.user_sex
	 * @param userSex  the value for ccp_culture_contest_user.user_sex
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setUserSex(Integer userSex) {
		this.userSex = userSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.user_birthday
	 * @return  the value of ccp_culture_contest_user.user_birthday
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public Date getUserBirthday() {
		return userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.user_birthday
	 * @param userBirthday  the value for ccp_culture_contest_user.user_birthday
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setUserBirthday(Date userBirthday) {
		this.userBirthday = userBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.user_id
	 * @return  the value of ccp_culture_contest_user.user_id
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.user_id
	 * @param userId  the value for ccp_culture_contest_user.user_id
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.user_group_type
	 * @return  the value of ccp_culture_contest_user.user_group_type
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public Integer getUserGroupType() {
		return userGroupType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.user_group_type
	 * @param userGroupType  the value for ccp_culture_contest_user.user_group_type
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setUserGroupType(Integer userGroupType) {
		this.userGroupType = userGroupType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.user_create_time
	 * @return  the value of ccp_culture_contest_user.user_create_time
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public Date getUserCreateTime() {
		return userCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.user_create_time
	 * @param userCreateTime  the value for ccp_culture_contest_user.user_create_time
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setUserCreateTime(Date userCreateTime) {
		this.userCreateTime = userCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.user_answer_time
	 * @return  the value of ccp_culture_contest_user.user_answer_time
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public Date getUserAnswerTime() {
		return userAnswerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.user_answer_time
	 * @param userAnswerTime  the value for ccp_culture_contest_user.user_answer_time
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setUserAnswerTime(Date userAnswerTime) {
		this.userAnswerTime = userAnswerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_user.user_area
	 * @return  the value of ccp_culture_contest_user.user_area
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public String getUserArea() {
		return userArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_user.user_area
	 * @param userArea  the value for ccp_culture_contest_user.user_area
	 * @mbggenerated  Fri Jun 02 11:26:05 CST 2017
	 */
	public void setUserArea(String userArea) {
		this.userArea = userArea;
	}
}