package com.culturecloud.model.bean.culture;

public class CcpCultureContestOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_culture_contest_option.culture_option_id
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    private String cultureOptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_culture_contest_option.question_id
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_culture_contest_option.option_content
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    private String optionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_culture_contest_option.option_index
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    private Integer optionIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccp_culture_contest_option.option_is_right
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    private Integer optionIsRight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_culture_contest_option.culture_option_id
     *
     * @return the value of ccp_culture_contest_option.culture_option_id
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public String getCultureOptionId() {
        return cultureOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_culture_contest_option.culture_option_id
     *
     * @param cultureOptionId the value for ccp_culture_contest_option.culture_option_id
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public void setCultureOptionId(String cultureOptionId) {
        this.cultureOptionId = cultureOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_culture_contest_option.question_id
     *
     * @return the value of ccp_culture_contest_option.question_id
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_culture_contest_option.question_id
     *
     * @param questionId the value for ccp_culture_contest_option.question_id
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_culture_contest_option.option_content
     *
     * @return the value of ccp_culture_contest_option.option_content
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public String getOptionContent() {
        return optionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_culture_contest_option.option_content
     *
     * @param optionContent the value for ccp_culture_contest_option.option_content
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public void setOptionContent(String optionContent) {
        this.optionContent = optionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_culture_contest_option.option_index
     *
     * @return the value of ccp_culture_contest_option.option_index
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public Integer getOptionIndex() {
        return optionIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_culture_contest_option.option_index
     *
     * @param optionIndex the value for ccp_culture_contest_option.option_index
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public void setOptionIndex(Integer optionIndex) {
        this.optionIndex = optionIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_culture_contest_option.option_is_right
     *
     * @return the value of ccp_culture_contest_option.option_is_right
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public Integer getOptionIsRight() {
        return optionIsRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_culture_contest_option.option_is_right
     *
     * @param optionIsRight the value for ccp_culture_contest_option.option_is_right
     *
     * @mbggenerated Wed May 17 16:25:17 CST 2017
     */
    public void setOptionIsRight(Integer optionIsRight) {
        this.optionIsRight = optionIsRight;
    }
}