package com.culturecloud.model.bean.culture;

import java.util.Date;

public class CcpCultureContestAnswer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.culture_answer_id
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private String cultureAnswerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.culture_user_id
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private String cultureUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.stage_number
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private Integer stageNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.answer_create_time
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private Date answerCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.answer_status
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private Integer answerStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.answer_time
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private Integer answerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.user_group_type
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private Integer userGroupType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.answer_use_time
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private Date answerUseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.answer_right_number
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private Integer answerRightNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.answer_right_question
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private String answerRightQuestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ccp_culture_contest_answer.answer_number
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	private String answerNumber;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.culture_answer_id
	 * @return  the value of ccp_culture_contest_answer.culture_answer_id
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public String getCultureAnswerId() {
		return cultureAnswerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.culture_answer_id
	 * @param cultureAnswerId  the value for ccp_culture_contest_answer.culture_answer_id
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setCultureAnswerId(String cultureAnswerId) {
		this.cultureAnswerId = cultureAnswerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.culture_user_id
	 * @return  the value of ccp_culture_contest_answer.culture_user_id
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public String getCultureUserId() {
		return cultureUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.culture_user_id
	 * @param cultureUserId  the value for ccp_culture_contest_answer.culture_user_id
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setCultureUserId(String cultureUserId) {
		this.cultureUserId = cultureUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.stage_number
	 * @return  the value of ccp_culture_contest_answer.stage_number
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public Integer getStageNumber() {
		return stageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.stage_number
	 * @param stageNumber  the value for ccp_culture_contest_answer.stage_number
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setStageNumber(Integer stageNumber) {
		this.stageNumber = stageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.answer_create_time
	 * @return  the value of ccp_culture_contest_answer.answer_create_time
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public Date getAnswerCreateTime() {
		return answerCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.answer_create_time
	 * @param answerCreateTime  the value for ccp_culture_contest_answer.answer_create_time
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setAnswerCreateTime(Date answerCreateTime) {
		this.answerCreateTime = answerCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.answer_status
	 * @return  the value of ccp_culture_contest_answer.answer_status
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public Integer getAnswerStatus() {
		return answerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.answer_status
	 * @param answerStatus  the value for ccp_culture_contest_answer.answer_status
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setAnswerStatus(Integer answerStatus) {
		this.answerStatus = answerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.answer_time
	 * @return  the value of ccp_culture_contest_answer.answer_time
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public Integer getAnswerTime() {
		return answerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.answer_time
	 * @param answerTime  the value for ccp_culture_contest_answer.answer_time
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setAnswerTime(Integer answerTime) {
		this.answerTime = answerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.user_group_type
	 * @return  the value of ccp_culture_contest_answer.user_group_type
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public Integer getUserGroupType() {
		return userGroupType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.user_group_type
	 * @param userGroupType  the value for ccp_culture_contest_answer.user_group_type
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setUserGroupType(Integer userGroupType) {
		this.userGroupType = userGroupType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.answer_use_time
	 * @return  the value of ccp_culture_contest_answer.answer_use_time
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public Date getAnswerUseTime() {
		return answerUseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.answer_use_time
	 * @param answerUseTime  the value for ccp_culture_contest_answer.answer_use_time
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setAnswerUseTime(Date answerUseTime) {
		this.answerUseTime = answerUseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.answer_right_number
	 * @return  the value of ccp_culture_contest_answer.answer_right_number
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public Integer getAnswerRightNumber() {
		return answerRightNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.answer_right_number
	 * @param answerRightNumber  the value for ccp_culture_contest_answer.answer_right_number
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setAnswerRightNumber(Integer answerRightNumber) {
		this.answerRightNumber = answerRightNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.answer_right_question
	 * @return  the value of ccp_culture_contest_answer.answer_right_question
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public String getAnswerRightQuestion() {
		return answerRightQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.answer_right_question
	 * @param answerRightQuestion  the value for ccp_culture_contest_answer.answer_right_question
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setAnswerRightQuestion(String answerRightQuestion) {
		this.answerRightQuestion = answerRightQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_culture_contest_answer.answer_number
	 * @return  the value of ccp_culture_contest_answer.answer_number
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public String getAnswerNumber() {
		return answerNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_culture_contest_answer.answer_number
	 * @param answerNumber  the value for ccp_culture_contest_answer.answer_number
	 * @mbggenerated  Fri May 26 09:41:20 CST 2017
	 */
	public void setAnswerNumber(String answerNumber) {
		this.answerNumber = answerNumber;
	}
}