package com.culturecloud.model.bean.activity;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;
import com.culturecloud.bean.BaseRequest;

import javax.persistence.Column;
import java.math.BigDecimal;
import java.util.Date;

@Table(value="cms_activity_order")
public class CmsActivityOrder extends BaseRequest implements BaseEntity {

    private static final long serialVersionUID = -3586841584989517881L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ACTIVITY_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Id
    @Column(name="ACTIVITY_ORDER_ID")
    private String activityOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ACTIVITY_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ACTIVITY_ID")
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.USER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="USER_ID")
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_NUMBER
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_NUMBER")
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_PRICE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_PRICE")
    private BigDecimal orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_NAME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_NAME")
    private String orderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_IDENTITY_CARD
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_IDENTITY_CARD")
    private String orderIdentityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_PHONE_NO
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_PHONE_NO")
    private String orderPhoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_SUMMARY
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_SUMMARY")
    private String orderSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_IS_VALID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_IS_VALID")
    private Short orderIsValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_CREATE_TIME")
    private Date orderCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_PAY_STATUS
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_PAY_STATUS")
    private Short orderPayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_PAY_TYPE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_PAY_TYPE")
    private Short orderPayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_PAY_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_PAY_TIME")
    private Date orderPayTime;
    
    
    @Column(name="ORDER_PAYMENT_STATUS")
    private Short orderPaymentStatus;
    
    @Column(name="ORDER_PAY_PREPAR_ID")
	private String orderPayPreparId;

    @Column(name="ORDER_APPLY_REFUND_TIME")
	private Date orderApplyRefundTime;

    @Column(name="ORDER_REFUND_TIME")
	private Date orderRefundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_VOTES
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_VOTES")
    private Integer orderVotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_VALIDATE_CODE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_VALIDATE_CODE")
    private String orderValidateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_TYPE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_TYPE")
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_TYPE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_TYPE")
    private Integer orderSmsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_SMS_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_SMS_TIME")
    private Date orderSmsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_SMS_STATE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_SMS_STATE")
    private Integer orderSmsState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.SYS_USER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="SYS_USER_ID")
    private String sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.SYS_NO
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="SYS_NO")
    private String sysNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.SYS_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="SYS_ID")
    private String sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="VENUE_ID")
    private String venueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.PRINT_TICKET_TIMES
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="PRINT_TICKET_TIMES")
    private Integer printTicketTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.EVENT_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="EVENT_ID")
    private String eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_UPDATE_TIME")
    private Date orderUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_CHECK_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_CHECK_TIME")
    private Date orderCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.COST_TOTAL_CREDIT
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="COST_TOTAL_CREDIT")
    private String costTotalCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order.ORDER_SMS
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    @Column(name="ORDER_SMS")
    private String orderSms;


    @Column(name="SURPLUS_COUNT")
    private Integer surplusCount;
    
    @Column(name="ORDER_CUSTOM_INFO")
    private String orderCustomInfo;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ACTIVITY_ORDER_ID
     *
     * @return the value of cms_activity_order.ACTIVITY_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getActivityOrderId() {
        return activityOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ACTIVITY_ORDER_ID
     *
     * @param activityOrderId the value for cms_activity_order.ACTIVITY_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setActivityOrderId(String activityOrderId) {
        this.activityOrderId = activityOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ACTIVITY_ID
     *
     * @return the value of cms_activity_order.ACTIVITY_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ACTIVITY_ID
     *
     * @param activityId the value for cms_activity_order.ACTIVITY_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.USER_ID
     *
     * @return the value of cms_activity_order.USER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.USER_ID
     *
     * @param userId the value for cms_activity_order.USER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_NUMBER
     *
     * @return the value of cms_activity_order.ORDER_NUMBER
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_NUMBER
     *
     * @param orderNumber the value for cms_activity_order.ORDER_NUMBER
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_PRICE
     *
     * @return the value of cms_activity_order.ORDER_PRICE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_PRICE
     *
     * @param orderPrice the value for cms_activity_order.ORDER_PRICE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_NAME
     *
     * @return the value of cms_activity_order.ORDER_NAME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_NAME
     *
     * @param orderName the value for cms_activity_order.ORDER_NAME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_IDENTITY_CARD
     *
     * @return the value of cms_activity_order.ORDER_IDENTITY_CARD
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getOrderIdentityCard() {
        return orderIdentityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_IDENTITY_CARD
     *
     * @param orderIdentityCard the value for cms_activity_order.ORDER_IDENTITY_CARD
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderIdentityCard(String orderIdentityCard) {
        this.orderIdentityCard = orderIdentityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_PHONE_NO
     *
     * @return the value of cms_activity_order.ORDER_PHONE_NO
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getOrderPhoneNo() {
        return orderPhoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_PHONE_NO
     *
     * @param orderPhoneNo the value for cms_activity_order.ORDER_PHONE_NO
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderPhoneNo(String orderPhoneNo) {
        this.orderPhoneNo = orderPhoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_SUMMARY
     *
     * @return the value of cms_activity_order.ORDER_SUMMARY
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getOrderSummary() {
        return orderSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_SUMMARY
     *
     * @param orderSummary the value for cms_activity_order.ORDER_SUMMARY
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderSummary(String orderSummary) {
        this.orderSummary = orderSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_IS_VALID
     *
     * @return the value of cms_activity_order.ORDER_IS_VALID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Short getOrderIsValid() {
        return orderIsValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_IS_VALID
     *
     * @param orderIsValid the value for cms_activity_order.ORDER_IS_VALID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderIsValid(Short orderIsValid) {
        this.orderIsValid = orderIsValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_CREATE_TIME
     *
     * @return the value of cms_activity_order.ORDER_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Date getOrderCreateTime() {
        return orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_CREATE_TIME
     *
     * @param orderCreateTime the value for cms_activity_order.ORDER_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderCreateTime(Date orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_PAY_STATUS
     *
     * @return the value of cms_activity_order.ORDER_PAY_STATUS
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Short getOrderPayStatus() {
        return orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_PAY_STATUS
     *
     * @param orderPayStatus the value for cms_activity_order.ORDER_PAY_STATUS
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderPayStatus(Short orderPayStatus) {
        this.orderPayStatus = orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_PAY_TYPE
     *
     * @return the value of cms_activity_order.ORDER_PAY_TYPE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Short getOrderPayType() {
        return orderPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_PAY_TYPE
     *
     * @param orderPayType the value for cms_activity_order.ORDER_PAY_TYPE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderPayType(Short orderPayType) {
        this.orderPayType = orderPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_PAY_TIME
     *
     * @return the value of cms_activity_order.ORDER_PAY_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Date getOrderPayTime() {
        return orderPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_PAY_TIME
     *
     * @param orderPayTime the value for cms_activity_order.ORDER_PAY_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderPayTime(Date orderPayTime) {
        this.orderPayTime = orderPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_VOTES
     *
     * @return the value of cms_activity_order.ORDER_VOTES
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Integer getOrderVotes() {
        return orderVotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_VOTES
     *
     * @param orderVotes the value for cms_activity_order.ORDER_VOTES
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderVotes(Integer orderVotes) {
        this.orderVotes = orderVotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_VALIDATE_CODE
     *
     * @return the value of cms_activity_order.ORDER_VALIDATE_CODE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getOrderValidateCode() {
        return orderValidateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_VALIDATE_CODE
     *
     * @param orderValidateCode the value for cms_activity_order.ORDER_VALIDATE_CODE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderValidateCode(String orderValidateCode) {
        this.orderValidateCode = orderValidateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_TYPE
     *
     * @return the value of cms_activity_order.ORDER_TYPE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_TYPE
     *
     * @param orderType the value for cms_activity_order.ORDER_TYPE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_SMS_COUNT
     *
     * @return the value of cms_activity_order.ORDER_SMS_COUNT
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Integer getOrderSmsCount() {
        return orderSmsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_SMS_COUNT
     *
     * @param orderSmsCount the value for cms_activity_order.ORDER_SMS_COUNT
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderSmsCount(Integer orderSmsCount) {
        this.orderSmsCount = orderSmsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_SMS_TIME
     *
     * @return the value of cms_activity_order.ORDER_SMS_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Date getOrderSmsTime() {
        return orderSmsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_SMS_TIME
     *
     * @param orderSmsTime the value for cms_activity_order.ORDER_SMS_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderSmsTime(Date orderSmsTime) {
        this.orderSmsTime = orderSmsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_SMS_STATE
     *
     * @return the value of cms_activity_order.ORDER_SMS_STATE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Integer getOrderSmsState() {
        return orderSmsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_SMS_STATE
     *
     * @param orderSmsState the value for cms_activity_order.ORDER_SMS_STATE
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderSmsState(Integer orderSmsState) {
        this.orderSmsState = orderSmsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.SYS_USER_ID
     *
     * @return the value of cms_activity_order.SYS_USER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.SYS_USER_ID
     *
     * @param sysUserId the value for cms_activity_order.SYS_USER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.SYS_NO
     *
     * @return the value of cms_activity_order.SYS_NO
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getSysNo() {
        return sysNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.SYS_NO
     *
     * @param sysNo the value for cms_activity_order.SYS_NO
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setSysNo(String sysNo) {
        this.sysNo = sysNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.SYS_ID
     *
     * @return the value of cms_activity_order.SYS_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.SYS_ID
     *
     * @param sysId the value for cms_activity_order.SYS_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.VENUE_ID
     *
     * @return the value of cms_activity_order.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getVenueId() {
        return venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.VENUE_ID
     *
     * @param venueId the value for cms_activity_order.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setVenueId(String venueId) {
        this.venueId = venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.PRINT_TICKET_TIMES
     *
     * @return the value of cms_activity_order.PRINT_TICKET_TIMES
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Integer getPrintTicketTimes() {
        return printTicketTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.PRINT_TICKET_TIMES
     *
     * @param printTicketTimes the value for cms_activity_order.PRINT_TICKET_TIMES
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setPrintTicketTimes(Integer printTicketTimes) {
        this.printTicketTimes = printTicketTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.EVENT_ID
     *
     * @return the value of cms_activity_order.EVENT_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.EVENT_ID
     *
     * @param eventId the value for cms_activity_order.EVENT_ID
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_UPDATE_TIME
     *
     * @return the value of cms_activity_order.ORDER_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Date getOrderUpdateTime() {
        return orderUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_UPDATE_TIME
     *
     * @param orderUpdateTime the value for cms_activity_order.ORDER_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderUpdateTime(Date orderUpdateTime) {
        this.orderUpdateTime = orderUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_CHECK_TIME
     *
     * @return the value of cms_activity_order.ORDER_CHECK_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public Date getOrderCheckTime() {
        return orderCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_CHECK_TIME
     *
     * @param orderCheckTime the value for cms_activity_order.ORDER_CHECK_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderCheckTime(Date orderCheckTime) {
        this.orderCheckTime = orderCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.COST_TOTAL_CREDIT
     *
     * @return the value of cms_activity_order.COST_TOTAL_CREDIT
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getCostTotalCredit() {
        return costTotalCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.COST_TOTAL_CREDIT
     *
     * @param costTotalCredit the value for cms_activity_order.COST_TOTAL_CREDIT
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setCostTotalCredit(String costTotalCredit) {
        this.costTotalCredit = costTotalCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order.ORDER_SMS
     *
     * @return the value of cms_activity_order.ORDER_SMS
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public String getOrderSms() {
        return orderSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order.ORDER_SMS
     *
     * @param orderSms the value for cms_activity_order.ORDER_SMS
     *
     * @mbggenerated Mon Jul 25 14:39:03 CST 2016
     */
    public void setOrderSms(String orderSms) {
        this.orderSms = orderSms;
    }

    public Integer getSurplusCount() {
        return surplusCount;
    }

    public void setSurplusCount(Integer surplusCount) {
        this.surplusCount = surplusCount;
    }

	public Short getOrderPaymentStatus() {
		return orderPaymentStatus;
	}

	public void setOrderPaymentStatus(Short orderPaymentStatus) {
		this.orderPaymentStatus = orderPaymentStatus;
	}

	public String getOrderPayPreparId() {
		return orderPayPreparId;
	}

	public void setOrderPayPreparId(String orderPayPreparId) {
		this.orderPayPreparId = orderPayPreparId;
	}

	public Date getOrderApplyRefundTime() {
		return orderApplyRefundTime;
	}

	public void setOrderApplyRefundTime(Date orderApplyRefundTime) {
		this.orderApplyRefundTime = orderApplyRefundTime;
	}

	public Date getOrderRefundTime() {
		return orderRefundTime;
	}

	public void setOrderRefundTime(Date orderRefundTime) {
		this.orderRefundTime = orderRefundTime;
	}

	public String getOrderCustomInfo() {
		return orderCustomInfo;
	}

	public void setOrderCustomInfo(String orderCustomInfo) {
		this.orderCustomInfo = orderCustomInfo;
	}
    
}