package com.culturecloud.model.bean.activity;

import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

import javax.persistence.Column;

@Table(value="cms_activity_venue_relevance")
public class CmsActivityVenueRelevance implements BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_venue_relevance.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 14:59:52 CST 2016
     */
    @Column(name="VENUE_ID")
    private String venueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_venue_relevance.ACTIVITY_ID
     *
     * @mbggenerated Mon Jul 25 14:59:52 CST 2016
     */
    @Column(name="ACTIVITY_ID")
    private String activityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_venue_relevance.VENUE_ID
     *
     * @return the value of cms_activity_venue_relevance.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 14:59:52 CST 2016
     */
    public String getVenueId() {
        return venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_venue_relevance.VENUE_ID
     *
     * @param venueId the value for cms_activity_venue_relevance.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 14:59:52 CST 2016
     */
    public void setVenueId(String venueId) {
        this.venueId = venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_venue_relevance.ACTIVITY_ID
     *
     * @return the value of cms_activity_venue_relevance.ACTIVITY_ID
     *
     * @mbggenerated Mon Jul 25 14:59:52 CST 2016
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_venue_relevance.ACTIVITY_ID
     *
     * @param activityId the value for cms_activity_venue_relevance.ACTIVITY_ID
     *
     * @mbggenerated Mon Jul 25 14:59:52 CST 2016
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }
}