package com.culturecloud.model.bean.activity;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

import javax.persistence.Column;
import java.util.Date;
@Table(value="cms_activity_order_detail")
public class CmsActivityOrderDetail implements BaseEntity {
    private static final long serialVersionUID = -3586841584989510881L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order_detail.ACTIVITY_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    @Id
    @Column(name="ACTIVITY_ORDER_ID")
    private String activityOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order_detail.ORDER_LINE
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    @Column(name="ORDER_LINE")
    private Integer orderLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order_detail.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    @Column(name="UPDATE_TIME")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order_detail.UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    @Column(name="UPDATE_USER")
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order_detail.SEAT_CODE
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    @Column(name="SEAT_CODE")
    private String seatCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order_detail.SEAT_VAL
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    @Column(name="SEAT_VAL")
    private String seatVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_activity_order_detail.SEAT_STATUS
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    @Column(name="SEAT_STATUS")
    private Integer seatStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order_detail.ACTIVITY_ORDER_ID
     *
     * @return the value of cms_activity_order_detail.ACTIVITY_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public String getActivityOrderId() {
        return activityOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order_detail.ACTIVITY_ORDER_ID
     *
     * @param activityOrderId the value for cms_activity_order_detail.ACTIVITY_ORDER_ID
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public void setActivityOrderId(String activityOrderId) {
        this.activityOrderId = activityOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order_detail.ORDER_LINE
     *
     * @return the value of cms_activity_order_detail.ORDER_LINE
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public Integer getOrderLine() {
        return orderLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order_detail.ORDER_LINE
     *
     * @param orderLine the value for cms_activity_order_detail.ORDER_LINE
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public void setOrderLine(Integer orderLine) {
        this.orderLine = orderLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order_detail.UPDATE_TIME
     *
     * @return the value of cms_activity_order_detail.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order_detail.UPDATE_TIME
     *
     * @param updateTime the value for cms_activity_order_detail.UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order_detail.UPDATE_USER
     *
     * @return the value of cms_activity_order_detail.UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order_detail.UPDATE_USER
     *
     * @param updateUser the value for cms_activity_order_detail.UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order_detail.SEAT_CODE
     *
     * @return the value of cms_activity_order_detail.SEAT_CODE
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public String getSeatCode() {
        return seatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order_detail.SEAT_CODE
     *
     * @param seatCode the value for cms_activity_order_detail.SEAT_CODE
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public void setSeatCode(String seatCode) {
        this.seatCode = seatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order_detail.SEAT_VAL
     *
     * @return the value of cms_activity_order_detail.SEAT_VAL
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public String getSeatVal() {
        return seatVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order_detail.SEAT_VAL
     *
     * @param seatVal the value for cms_activity_order_detail.SEAT_VAL
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public void setSeatVal(String seatVal) {
        this.seatVal = seatVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_activity_order_detail.SEAT_STATUS
     *
     * @return the value of cms_activity_order_detail.SEAT_STATUS
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public Integer getSeatStatus() {
        return seatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_activity_order_detail.SEAT_STATUS
     *
     * @param seatStatus the value for cms_activity_order_detail.SEAT_STATUS
     *
     * @mbggenerated Mon Jul 25 14:39:20 CST 2016
     */
    public void setSeatStatus(Integer seatStatus) {
        this.seatStatus = seatStatus;
    }
}