package com.sun3d.why.model;

import java.util.Date;

public class DcSuggestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_suggestion.suggestion_id
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    private String suggestionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_suggestion.content
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_suggestion.telephone
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_suggestion.create_time
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_suggestion.suggestion_id
     *
     * @return the value of dc_suggestion.suggestion_id
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    public String getSuggestionId() {
        return suggestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_suggestion.suggestion_id
     *
     * @param suggestionId the value for dc_suggestion.suggestion_id
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    public void setSuggestionId(String suggestionId) {
        this.suggestionId = suggestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_suggestion.content
     *
     * @return the value of dc_suggestion.content
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_suggestion.content
     *
     * @param content the value for dc_suggestion.content
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_suggestion.telephone
     *
     * @return the value of dc_suggestion.telephone
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_suggestion.telephone
     *
     * @param telephone the value for dc_suggestion.telephone
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_suggestion.create_time
     *
     * @return the value of dc_suggestion.create_time
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_suggestion.create_time
     *
     * @param createTime the value for dc_suggestion.create_time
     *
     * @mbggenerated Tue Nov 15 18:09:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}