package com.culturecloud.model.bean.vote;

import java.util.Date;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table("ccp_vote_item")
public class CcpVoteItem implements BaseEntity{
	private static final long serialVersionUID = -3596496851299485372L;

	@Id
	@Column(name="vote_item_id")
	private String voteItemId;
	
	@Column(name="item_name")
	private String itemName;

	@Column(name="item_img_url")
	private String itemImgUrl;
	
	@Column(name="author_name")
	private String authorName;


	@Column(name="author_head_img_url")
	private String authorHeadImgUrl;


	@Column(name="item_create_time")
	private Date itemCreateTime;


	@Column(name="item_create_user")
	private String itemCreateUser;


	@Column(name="vote_id")
	private String voteId;


	@Column(name="item_update_time")
	private Date itemUpdateTime;


	@Column(name="item_update_user")
	private String itemUpdateUser;


	@Column(name="item_is_del")
	private Integer itemIsDel;
	
	@Column(name="item_link")
	private String itemLink;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.vote_item_id
	 * @return  the value of ccp_vote_item.vote_item_id
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public String getVoteItemId() {
		return voteItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.vote_item_id
	 * @param voteItemId  the value for ccp_vote_item.vote_item_id
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setVoteItemId(String voteItemId) {
		this.voteItemId = voteItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.item_name
	 * @return  the value of ccp_vote_item.item_name
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public String getItemName() {
		return itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.item_name
	 * @param itemName  the value for ccp_vote_item.item_name
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.item_img_url
	 * @return  the value of ccp_vote_item.item_img_url
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public String getItemImgUrl() {
		return itemImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.item_img_url
	 * @param itemImgUrl  the value for ccp_vote_item.item_img_url
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setItemImgUrl(String itemImgUrl) {
		this.itemImgUrl = itemImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.author_name
	 * @return  the value of ccp_vote_item.author_name
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public String getAuthorName() {
		return authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.author_name
	 * @param authorName  the value for ccp_vote_item.author_name
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.author_head_img_url
	 * @return  the value of ccp_vote_item.author_head_img_url
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public String getAuthorHeadImgUrl() {
		return authorHeadImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.author_head_img_url
	 * @param authorHeadImgUrl  the value for ccp_vote_item.author_head_img_url
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setAuthorHeadImgUrl(String authorHeadImgUrl) {
		this.authorHeadImgUrl = authorHeadImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.item_create_time
	 * @return  the value of ccp_vote_item.item_create_time
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public Date getItemCreateTime() {
		return itemCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.item_create_time
	 * @param itemCreateTime  the value for ccp_vote_item.item_create_time
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setItemCreateTime(Date itemCreateTime) {
		this.itemCreateTime = itemCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.item_create_user
	 * @return  the value of ccp_vote_item.item_create_user
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public String getItemCreateUser() {
		return itemCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.item_create_user
	 * @param itemCreateUser  the value for ccp_vote_item.item_create_user
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setItemCreateUser(String itemCreateUser) {
		this.itemCreateUser = itemCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.vote_id
	 * @return  the value of ccp_vote_item.vote_id
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public String getVoteId() {
		return voteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.vote_id
	 * @param voteId  the value for ccp_vote_item.vote_id
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setVoteId(String voteId) {
		this.voteId = voteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.item_update_time
	 * @return  the value of ccp_vote_item.item_update_time
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public Date getItemUpdateTime() {
		return itemUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.item_update_time
	 * @param itemUpdateTime  the value for ccp_vote_item.item_update_time
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setItemUpdateTime(Date itemUpdateTime) {
		this.itemUpdateTime = itemUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.item_update_user
	 * @return  the value of ccp_vote_item.item_update_user
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public String getItemUpdateUser() {
		return itemUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.item_update_user
	 * @param itemUpdateUser  the value for ccp_vote_item.item_update_user
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setItemUpdateUser(String itemUpdateUser) {
		this.itemUpdateUser = itemUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote_item.item_is_del
	 * @return  the value of ccp_vote_item.item_is_del
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public Integer getItemIsDel() {
		return itemIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote_item.item_is_del
	 * @param itemIsDel  the value for ccp_vote_item.item_is_del
	 * @mbggenerated  Mon Nov 07 23:27:16 CST 2016
	 */
	public void setItemIsDel(Integer itemIsDel) {
		this.itemIsDel = itemIsDel;
	}

	public String getItemLink() {
		return itemLink;
	}

	public void setItemLink(String itemLink) {
		this.itemLink = itemLink;
	}
	
	
}