package com.culturecloud.model.bean.vote;

import java.util.Date;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table("ccp_vote")
public class CcpVote implements BaseEntity{

	private static final long serialVersionUID = 5341060202070788210L;

	@Id
	@Column(name="vote_id")
	private String voteId;

	@Column(name="vote_name")
	private String voteName;

	@Column(name="vote_title")
	private String voteTitle;

	@Column(name="vote_second_title")
	private String voteSecondTitle;
	
	@Column(name="cover_img_url")
	private String coverImgUrl;

	@Column(name="vote_introduction")
	private String voteIntroduction;
	
	@Column(name="vote_type")
	private Integer voteType;
	
	@Column(name="is_user_info")
	private Integer isUserInfo;
	
	@Column(name="is_author_info")
	private Integer isAuthorInfo;
	
	@Column(name="share_logo_img")
	private String shareLogoImg;

	@Column(name="share_title")
	private String shareTitle;
	
	@Column(name="share_describe")
	private String shareDescribe;
	
	@Column(name="vote_create_time")
	private Date voteCreateTime;
	
	@Column(name="vote_update_time")
	private Date voteUpdateTime;
	
	@Column(name="vote_create_user")
	private String voteCreateUser;
	
	@Column(name="vote_update_user")
	private String voteUpdateUser;
	
	@Column(name="vote_is_del")
	private Integer voteIsDel;

	@Column(name="vote_rule")
	private String voteRule;

	@Column(name="index_logo")
	private String indexLogo;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_id
	 * @return  the value of ccp_vote.vote_id
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getVoteId() {
		return voteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_id
	 * @param voteId  the value for ccp_vote.vote_id
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteId(String voteId) {
		this.voteId = voteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_name
	 * @return  the value of ccp_vote.vote_name
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getVoteName() {
		return voteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_name
	 * @param voteName  the value for ccp_vote.vote_name
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteName(String voteName) {
		this.voteName = voteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_title
	 * @return  the value of ccp_vote.vote_title
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getVoteTitle() {
		return voteTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_title
	 * @param voteTitle  the value for ccp_vote.vote_title
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteTitle(String voteTitle) {
		this.voteTitle = voteTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_second_title
	 * @return  the value of ccp_vote.vote_second_title
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getVoteSecondTitle() {
		return voteSecondTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_second_title
	 * @param voteSecondTitle  the value for ccp_vote.vote_second_title
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteSecondTitle(String voteSecondTitle) {
		this.voteSecondTitle = voteSecondTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.cover_img_url
	 * @return  the value of ccp_vote.cover_img_url
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getCoverImgUrl() {
		return coverImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.cover_img_url
	 * @param coverImgUrl  the value for ccp_vote.cover_img_url
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setCoverImgUrl(String coverImgUrl) {
		this.coverImgUrl = coverImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_introduction
	 * @return  the value of ccp_vote.vote_introduction
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getVoteIntroduction() {
		return voteIntroduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_introduction
	 * @param voteIntroduction  the value for ccp_vote.vote_introduction
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteIntroduction(String voteIntroduction) {
		this.voteIntroduction = voteIntroduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_type
	 * @return  the value of ccp_vote.vote_type
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public Integer getVoteType() {
		return voteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_type
	 * @param voteType  the value for ccp_vote.vote_type
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteType(Integer voteType) {
		this.voteType = voteType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.is_user_info
	 * @return  the value of ccp_vote.is_user_info
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public Integer getIsUserInfo() {
		return isUserInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.is_user_info
	 * @param isUserInfo  the value for ccp_vote.is_user_info
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setIsUserInfo(Integer isUserInfo) {
		this.isUserInfo = isUserInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.is_author_info
	 * @return  the value of ccp_vote.is_author_info
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public Integer getIsAuthorInfo() {
		return isAuthorInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.is_author_info
	 * @param isAuthorInfo  the value for ccp_vote.is_author_info
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setIsAuthorInfo(Integer isAuthorInfo) {
		this.isAuthorInfo = isAuthorInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.share_logo_img
	 * @return  the value of ccp_vote.share_logo_img
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getShareLogoImg() {
		return shareLogoImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.share_logo_img
	 * @param shareLogoImg  the value for ccp_vote.share_logo_img
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setShareLogoImg(String shareLogoImg) {
		this.shareLogoImg = shareLogoImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.share_title
	 * @return  the value of ccp_vote.share_title
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getShareTitle() {
		return shareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.share_title
	 * @param shareTitle  the value for ccp_vote.share_title
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setShareTitle(String shareTitle) {
		this.shareTitle = shareTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.share_describe
	 * @return  the value of ccp_vote.share_describe
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getShareDescribe() {
		return shareDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.share_describe
	 * @param shareDescribe  the value for ccp_vote.share_describe
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setShareDescribe(String shareDescribe) {
		this.shareDescribe = shareDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_create_time
	 * @return  the value of ccp_vote.vote_create_time
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public Date getVoteCreateTime() {
		return voteCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_create_time
	 * @param voteCreateTime  the value for ccp_vote.vote_create_time
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteCreateTime(Date voteCreateTime) {
		this.voteCreateTime = voteCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_update_time
	 * @return  the value of ccp_vote.vote_update_time
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public Date getVoteUpdateTime() {
		return voteUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_update_time
	 * @param voteUpdateTime  the value for ccp_vote.vote_update_time
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteUpdateTime(Date voteUpdateTime) {
		this.voteUpdateTime = voteUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_create_user
	 * @return  the value of ccp_vote.vote_create_user
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getVoteCreateUser() {
		return voteCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_create_user
	 * @param voteCreateUser  the value for ccp_vote.vote_create_user
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteCreateUser(String voteCreateUser) {
		this.voteCreateUser = voteCreateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_update_user
	 * @return  the value of ccp_vote.vote_update_user
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getVoteUpdateUser() {
		return voteUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_update_user
	 * @param voteUpdateUser  the value for ccp_vote.vote_update_user
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteUpdateUser(String voteUpdateUser) {
		this.voteUpdateUser = voteUpdateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_is_del
	 * @return  the value of ccp_vote.vote_is_del
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public Integer getVoteIsDel() {
		return voteIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_is_del
	 * @param voteIsDel  the value for ccp_vote.vote_is_del
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteIsDel(Integer voteIsDel) {
		this.voteIsDel = voteIsDel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ccp_vote.vote_rule
	 * @return  the value of ccp_vote.vote_rule
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public String getVoteRule() {
		return voteRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ccp_vote.vote_rule
	 * @param voteRule  the value for ccp_vote.vote_rule
	 * @mbggenerated  Mon Nov 07 10:18:02 CST 2016
	 */
	public void setVoteRule(String voteRule) {
		this.voteRule = voteRule;
	}

	public String getIndexLogo() {
		return indexLogo;
	}

	public void setIndexLogo(String indexLogo) {
		this.indexLogo = indexLogo;
	}
	
	
}