package com.culturecloud.model.bean.vote;

import java.util.Date;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table("ccp_vote_ticket")
public class CcpVoteTicket implements BaseEntity{
  
	private static final long serialVersionUID = -3911559901526400162L;

	@Id
	@Column(name="TICKET_ID")
    private String ticketId;

	@Column(name="VOTE_ID")
    private String voteId;

	@Column(name="USER_ID")
    private String userId;

	@Column(name="VOTE_ITEM_ID")
    private String voteItemId;

	@Column(name="VOTE_TIME")
    private Date voteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_vote_ticket.TICKET_ID
     *
     * @return the value of ccp_vote_ticket.TICKET_ID
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public String getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_vote_ticket.TICKET_ID
     *
     * @param ticketId the value for ccp_vote_ticket.TICKET_ID
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_vote_ticket.VOTE_ID
     *
     * @return the value of ccp_vote_ticket.VOTE_ID
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public String getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_vote_ticket.VOTE_ID
     *
     * @param voteId the value for ccp_vote_ticket.VOTE_ID
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public void setVoteId(String voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_vote_ticket.USER_ID
     *
     * @return the value of ccp_vote_ticket.USER_ID
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_vote_ticket.USER_ID
     *
     * @param userId the value for ccp_vote_ticket.USER_ID
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_vote_ticket.VOTE_ITEM_ID
     *
     * @return the value of ccp_vote_ticket.VOTE_ITEM_ID
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public String getVoteItemId() {
        return voteItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_vote_ticket.VOTE_ITEM_ID
     *
     * @param voteItemId the value for ccp_vote_ticket.VOTE_ITEM_ID
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public void setVoteItemId(String voteItemId) {
        this.voteItemId = voteItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_vote_ticket.VOTE_TIME
     *
     * @return the value of ccp_vote_ticket.VOTE_TIME
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public Date getVoteTime() {
        return voteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_vote_ticket.VOTE_TIME
     *
     * @param voteTime the value for ccp_vote_ticket.VOTE_TIME
     *
     * @mbggenerated Wed Nov 09 17:40:06 CST 2016
     */
    public void setVoteTime(Date voteTime) {
        this.voteTime = voteTime;
    }
}