package com.culturecloud.model.bean.vote;

import java.util.Date;

import javax.persistence.Column;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

@Table("ccp_vote_user")
public class CcpVoteUser implements BaseEntity {
	
	private static final long serialVersionUID = -70648914156924629L;

	@Id
	@Column(name="USER_ID")
    private String userId;

	@Column(name="USER_NAME")
    private String userName;

	@Column(name="USER_MOBILE")
    private String userMobile;

	@Column(name="CREATE_TIME")
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_vote_user.USER_ID
     *
     * @return the value of ccp_vote_user.USER_ID
     *
     * @mbggenerated Wed Nov 16 15:06:39 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_vote_user.USER_ID
     *
     * @param userId the value for ccp_vote_user.USER_ID
     *
     * @mbggenerated Wed Nov 16 15:06:39 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_vote_user.USER_NAME
     *
     * @return the value of ccp_vote_user.USER_NAME
     *
     * @mbggenerated Wed Nov 16 15:06:39 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_vote_user.USER_NAME
     *
     * @param userName the value for ccp_vote_user.USER_NAME
     *
     * @mbggenerated Wed Nov 16 15:06:39 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_vote_user.USER_MOBILE
     *
     * @return the value of ccp_vote_user.USER_MOBILE
     *
     * @mbggenerated Wed Nov 16 15:06:39 CST 2016
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_vote_user.USER_MOBILE
     *
     * @param userMobile the value for ccp_vote_user.USER_MOBILE
     *
     * @mbggenerated Wed Nov 16 15:06:39 CST 2016
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccp_vote_user.CREATE_TIME
     *
     * @return the value of ccp_vote_user.CREATE_TIME
     *
     * @mbggenerated Wed Nov 16 15:06:39 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccp_vote_user.CREATE_TIME
     *
     * @param createTime the value for ccp_vote_user.CREATE_TIME
     *
     * @mbggenerated Wed Nov 16 15:06:39 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}