package com.culturecloud.model.bean.venue;

import com.culturecloud.annotations.Id;
import com.culturecloud.annotations.Table;
import com.culturecloud.bean.BaseEntity;

import javax.persistence.Column;
import java.util.Date;
@Table(value="cms_venue")
public class CmsVenue implements BaseEntity {

    private static final long serialVersionUID = -3586841584457510841L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Id
    @Column(name="VENUE_ID")
    private String venueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_NAME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_NAME")
    private String venueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_ICON_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_ICON_URL")
    private String venueIconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_LON
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_LON")
    private Double venueLon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_LAT
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_LAT")
    private Double venueLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_PROVINCE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_PROVINCE")
    private String venueProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_CITY
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_CITY")
    private String venueCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_AREA
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_AREA")
    private String venueArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_ADDRESS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_ADDRESS")
    private String venueAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_OPEN_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_OPEN_TIME")
    private String venueOpenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_TYPE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_TYPE")
    private String venueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_LINKMAN
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_LINKMAN")
    private String venueLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_SITES
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_SITES")
    private String venueSites;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_MAIL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_MAIL")
    private String venueMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_TEL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_TEL")
    private String venueTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_MOBILE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_MOBILE")
    private String venueMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_IS_FREE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_IS_FREE")
    private Integer venueIsFree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_PRICE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_PRICE")
    private String venuePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_BUSINESS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_BUSINESS")
    private String venueBusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_IS_VOICE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_IS_VOICE")
    private Integer venueIsVoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_VOICE_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_VOICE_URL")
    private String venueVoiceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_IS_VIDEO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_IS_VIDEO")
    private Integer venueIsVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_VIDEO_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_VIDEO_URL")
    private String venueVideoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_IS_ROAM
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_IS_ROAM")
    private Integer venueIsRoam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_ROAM_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_ROAM_URL")
    private String venueRoamUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_IS_DEL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_IS_DEL")
    private Integer venueIsDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_STATE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_STATE")
    private Integer venueState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_CREATE_TIME")
    private Date venueCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_UPDATE_TIME")
    private Date venueUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_CREATE_USER
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_CREATE_USER")
    private String venueCreateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_UPDATE_USER")
    private String venueUpdateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_IS_RESERVE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_IS_RESERVE")
    private Integer venueIsReserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_END_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_END_TIME")
    private String venueEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_MON
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_MON")
    private String venueMon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_TUE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_TUE")
    private String venueTue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_WED
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_WED")
    private String venueWed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_THU
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_THU")
    private String venueThu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_FRI
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_FRI")
    private String venueFri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_SAT
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_SAT")
    private String venueSat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_SUN
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_SUN")
    private String venueSun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.MANAGER_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="MANAGER_ID")
    private String managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.OPEN_NOTICE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="OPEN_NOTICE")
    private String openNotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_HAS_ROOM
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_HAS_ROOM")
    private Integer venueHasRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_HAS_ANTIQUE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_HAS_ANTIQUE")
    private Integer venueHasAntique;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.SYS_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="SYS_ID")
    private String sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.SYS_NO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="SYS_NO")
    private String sysNo;

    /**
     * 场馆附近有无地铁，根据产品需求已删去。
     */
    @Deprecated
    private Integer venueHasMetro;

    /**
     * 场馆附近有无公交，根据产品需求已删去。
     */
    @Deprecated
    private Integer venueHasBus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_STARS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_STARS")
    private String venueStars;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_IS_RECOMMEND
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_IS_RECOMMEND")
    private Integer venueIsRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_RECOMMEND_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_RECOMMEND_TIME")
    private Date venueRecommendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_DEPT_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_DEPT_ID")
    private String venueDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_DEPT_LABEL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_DEPT_LABEL")
    private String venueDeptLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_MEMO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_MEMO")
    private String venueMemo;

    /**
     * 场馆人群标签，产品需求已删掉。
     */
    @Deprecated
    private String venueCrowd;

    /**
     * 场馆心情标签，产品需求已删掉。
     */
    @Deprecated
    private String venueMood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_DEPT
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_DEPT")
    private String venueDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_REMARK
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_REMARK")
    private String venueRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_venue.VENUE_PANORAMA
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    @Column(name="VENUE_PANORAMA")
    private String venuePanorama;

    @Column(name="VENUE_PRICE_NOTICE")
    private String venuePriceNotice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_ID
     *
     * @return the value of cms_venue.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueId() {
        return venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_ID
     *
     * @param venueId the value for cms_venue.VENUE_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueId(String venueId) {
        this.venueId = venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_NAME
     *
     * @return the value of cms_venue.VENUE_NAME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueName() {
        return venueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_NAME
     *
     * @param venueName the value for cms_venue.VENUE_NAME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueName(String venueName) {
        this.venueName = venueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_ICON_URL
     *
     * @return the value of cms_venue.VENUE_ICON_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueIconUrl() {
        return venueIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_ICON_URL
     *
     * @param venueIconUrl the value for cms_venue.VENUE_ICON_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueIconUrl(String venueIconUrl) {
        this.venueIconUrl = venueIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_LON
     *
     * @return the value of cms_venue.VENUE_LON
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Double getVenueLon() {
        return venueLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_LON
     *
     * @param venueLon the value for cms_venue.VENUE_LON
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueLon(Double venueLon) {
        this.venueLon = venueLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_LAT
     *
     * @return the value of cms_venue.VENUE_LAT
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Double getVenueLat() {
        return venueLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_LAT
     *
     * @param venueLat the value for cms_venue.VENUE_LAT
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueLat(Double venueLat) {
        this.venueLat = venueLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_PROVINCE
     *
     * @return the value of cms_venue.VENUE_PROVINCE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueProvince() {
        return venueProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_PROVINCE
     *
     * @param venueProvince the value for cms_venue.VENUE_PROVINCE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueProvince(String venueProvince) {
        this.venueProvince = venueProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_CITY
     *
     * @return the value of cms_venue.VENUE_CITY
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueCity() {
        return venueCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_CITY
     *
     * @param venueCity the value for cms_venue.VENUE_CITY
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueCity(String venueCity) {
        this.venueCity = venueCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_AREA
     *
     * @return the value of cms_venue.VENUE_AREA
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueArea() {
        return venueArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_AREA
     *
     * @param venueArea the value for cms_venue.VENUE_AREA
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueArea(String venueArea) {
        this.venueArea = venueArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_ADDRESS
     *
     * @return the value of cms_venue.VENUE_ADDRESS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueAddress() {
        return venueAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_ADDRESS
     *
     * @param venueAddress the value for cms_venue.VENUE_ADDRESS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueAddress(String venueAddress) {
        this.venueAddress = venueAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_OPEN_TIME
     *
     * @return the value of cms_venue.VENUE_OPEN_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueOpenTime() {
        return venueOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_OPEN_TIME
     *
     * @param venueOpenTime the value for cms_venue.VENUE_OPEN_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueOpenTime(String venueOpenTime) {
        this.venueOpenTime = venueOpenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_TYPE
     *
     * @return the value of cms_venue.VENUE_TYPE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueType() {
        return venueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_TYPE
     *
     * @param venueType the value for cms_venue.VENUE_TYPE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueType(String venueType) {
        this.venueType = venueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_LINKMAN
     *
     * @return the value of cms_venue.VENUE_LINKMAN
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueLinkman() {
        return venueLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_LINKMAN
     *
     * @param venueLinkman the value for cms_venue.VENUE_LINKMAN
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueLinkman(String venueLinkman) {
        this.venueLinkman = venueLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_SITES
     *
     * @return the value of cms_venue.VENUE_SITES
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueSites() {
        return venueSites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_SITES
     *
     * @param venueSites the value for cms_venue.VENUE_SITES
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueSites(String venueSites) {
        this.venueSites = venueSites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_MAIL
     *
     * @return the value of cms_venue.VENUE_MAIL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueMail() {
        return venueMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_MAIL
     *
     * @param venueMail the value for cms_venue.VENUE_MAIL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueMail(String venueMail) {
        this.venueMail = venueMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_TEL
     *
     * @return the value of cms_venue.VENUE_TEL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueTel() {
        return venueTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_TEL
     *
     * @param venueTel the value for cms_venue.VENUE_TEL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueTel(String venueTel) {
        this.venueTel = venueTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_MOBILE
     *
     * @return the value of cms_venue.VENUE_MOBILE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueMobile() {
        return venueMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_MOBILE
     *
     * @param venueMobile the value for cms_venue.VENUE_MOBILE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueMobile(String venueMobile) {
        this.venueMobile = venueMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_IS_FREE
     *
     * @return the value of cms_venue.VENUE_IS_FREE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueIsFree() {
        return venueIsFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_IS_FREE
     *
     * @param venueIsFree the value for cms_venue.VENUE_IS_FREE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueIsFree(Integer venueIsFree) {
        this.venueIsFree = venueIsFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_PRICE
     *
     * @return the value of cms_venue.VENUE_PRICE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenuePrice() {
        return venuePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_PRICE
     *
     * @param venuePrice the value for cms_venue.VENUE_PRICE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenuePrice(String venuePrice) {
        this.venuePrice = venuePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_BUSINESS
     *
     * @return the value of cms_venue.VENUE_BUSINESS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueBusiness() {
        return venueBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_BUSINESS
     *
     * @param venueBusiness the value for cms_venue.VENUE_BUSINESS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueBusiness(String venueBusiness) {
        this.venueBusiness = venueBusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_IS_VOICE
     *
     * @return the value of cms_venue.VENUE_IS_VOICE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueIsVoice() {
        return venueIsVoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_IS_VOICE
     *
     * @param venueIsVoice the value for cms_venue.VENUE_IS_VOICE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueIsVoice(Integer venueIsVoice) {
        this.venueIsVoice = venueIsVoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_VOICE_URL
     *
     * @return the value of cms_venue.VENUE_VOICE_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueVoiceUrl() {
        return venueVoiceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_VOICE_URL
     *
     * @param venueVoiceUrl the value for cms_venue.VENUE_VOICE_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueVoiceUrl(String venueVoiceUrl) {
        this.venueVoiceUrl = venueVoiceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_IS_VIDEO
     *
     * @return the value of cms_venue.VENUE_IS_VIDEO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueIsVideo() {
        return venueIsVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_IS_VIDEO
     *
     * @param venueIsVideo the value for cms_venue.VENUE_IS_VIDEO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueIsVideo(Integer venueIsVideo) {
        this.venueIsVideo = venueIsVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_VIDEO_URL
     *
     * @return the value of cms_venue.VENUE_VIDEO_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueVideoUrl() {
        return venueVideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_VIDEO_URL
     *
     * @param venueVideoUrl the value for cms_venue.VENUE_VIDEO_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueVideoUrl(String venueVideoUrl) {
        this.venueVideoUrl = venueVideoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_IS_ROAM
     *
     * @return the value of cms_venue.VENUE_IS_ROAM
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueIsRoam() {
        return venueIsRoam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_IS_ROAM
     *
     * @param venueIsRoam the value for cms_venue.VENUE_IS_ROAM
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueIsRoam(Integer venueIsRoam) {
        this.venueIsRoam = venueIsRoam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_ROAM_URL
     *
     * @return the value of cms_venue.VENUE_ROAM_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueRoamUrl() {
        return venueRoamUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_ROAM_URL
     *
     * @param venueRoamUrl the value for cms_venue.VENUE_ROAM_URL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueRoamUrl(String venueRoamUrl) {
        this.venueRoamUrl = venueRoamUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_IS_DEL
     *
     * @return the value of cms_venue.VENUE_IS_DEL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueIsDel() {
        return venueIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_IS_DEL
     *
     * @param venueIsDel the value for cms_venue.VENUE_IS_DEL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueIsDel(Integer venueIsDel) {
        this.venueIsDel = venueIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_STATE
     *
     * @return the value of cms_venue.VENUE_STATE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueState() {
        return venueState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_STATE
     *
     * @param venueState the value for cms_venue.VENUE_STATE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueState(Integer venueState) {
        this.venueState = venueState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_CREATE_TIME
     *
     * @return the value of cms_venue.VENUE_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Date getVenueCreateTime() {
        return venueCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_CREATE_TIME
     *
     * @param venueCreateTime the value for cms_venue.VENUE_CREATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueCreateTime(Date venueCreateTime) {
        this.venueCreateTime = venueCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_UPDATE_TIME
     *
     * @return the value of cms_venue.VENUE_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Date getVenueUpdateTime() {
        return venueUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_UPDATE_TIME
     *
     * @param venueUpdateTime the value for cms_venue.VENUE_UPDATE_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueUpdateTime(Date venueUpdateTime) {
        this.venueUpdateTime = venueUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_CREATE_USER
     *
     * @return the value of cms_venue.VENUE_CREATE_USER
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueCreateUser() {
        return venueCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_CREATE_USER
     *
     * @param venueCreateUser the value for cms_venue.VENUE_CREATE_USER
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueCreateUser(String venueCreateUser) {
        this.venueCreateUser = venueCreateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_UPDATE_USER
     *
     * @return the value of cms_venue.VENUE_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueUpdateUser() {
        return venueUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_UPDATE_USER
     *
     * @param venueUpdateUser the value for cms_venue.VENUE_UPDATE_USER
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueUpdateUser(String venueUpdateUser) {
        this.venueUpdateUser = venueUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_IS_RESERVE
     *
     * @return the value of cms_venue.VENUE_IS_RESERVE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueIsReserve() {
        return venueIsReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_IS_RESERVE
     *
     * @param venueIsReserve the value for cms_venue.VENUE_IS_RESERVE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueIsReserve(Integer venueIsReserve) {
        this.venueIsReserve = venueIsReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_END_TIME
     *
     * @return the value of cms_venue.VENUE_END_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueEndTime() {
        return venueEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_END_TIME
     *
     * @param venueEndTime the value for cms_venue.VENUE_END_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueEndTime(String venueEndTime) {
        this.venueEndTime = venueEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_MON
     *
     * @return the value of cms_venue.VENUE_MON
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueMon() {
        return venueMon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_MON
     *
     * @param venueMon the value for cms_venue.VENUE_MON
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueMon(String venueMon) {
        this.venueMon = venueMon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_TUE
     *
     * @return the value of cms_venue.VENUE_TUE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueTue() {
        return venueTue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_TUE
     *
     * @param venueTue the value for cms_venue.VENUE_TUE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueTue(String venueTue) {
        this.venueTue = venueTue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_WED
     *
     * @return the value of cms_venue.VENUE_WED
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueWed() {
        return venueWed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_WED
     *
     * @param venueWed the value for cms_venue.VENUE_WED
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueWed(String venueWed) {
        this.venueWed = venueWed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_THU
     *
     * @return the value of cms_venue.VENUE_THU
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueThu() {
        return venueThu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_THU
     *
     * @param venueThu the value for cms_venue.VENUE_THU
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueThu(String venueThu) {
        this.venueThu = venueThu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_FRI
     *
     * @return the value of cms_venue.VENUE_FRI
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueFri() {
        return venueFri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_FRI
     *
     * @param venueFri the value for cms_venue.VENUE_FRI
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueFri(String venueFri) {
        this.venueFri = venueFri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_SAT
     *
     * @return the value of cms_venue.VENUE_SAT
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueSat() {
        return venueSat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_SAT
     *
     * @param venueSat the value for cms_venue.VENUE_SAT
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueSat(String venueSat) {
        this.venueSat = venueSat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_SUN
     *
     * @return the value of cms_venue.VENUE_SUN
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueSun() {
        return venueSun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_SUN
     *
     * @param venueSun the value for cms_venue.VENUE_SUN
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueSun(String venueSun) {
        this.venueSun = venueSun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.MANAGER_ID
     *
     * @return the value of cms_venue.MANAGER_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.MANAGER_ID
     *
     * @param managerId the value for cms_venue.MANAGER_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.OPEN_NOTICE
     *
     * @return the value of cms_venue.OPEN_NOTICE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getOpenNotice() {
        return openNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.OPEN_NOTICE
     *
     * @param openNotice the value for cms_venue.OPEN_NOTICE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setOpenNotice(String openNotice) {
        this.openNotice = openNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_HAS_ROOM
     *
     * @return the value of cms_venue.VENUE_HAS_ROOM
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueHasRoom() {
        return venueHasRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_HAS_ROOM
     *
     * @param venueHasRoom the value for cms_venue.VENUE_HAS_ROOM
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueHasRoom(Integer venueHasRoom) {
        this.venueHasRoom = venueHasRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_HAS_ANTIQUE
     *
     * @return the value of cms_venue.VENUE_HAS_ANTIQUE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueHasAntique() {
        return venueHasAntique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_HAS_ANTIQUE
     *
     * @param venueHasAntique the value for cms_venue.VENUE_HAS_ANTIQUE
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueHasAntique(Integer venueHasAntique) {
        this.venueHasAntique = venueHasAntique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.SYS_ID
     *
     * @return the value of cms_venue.SYS_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.SYS_ID
     *
     * @param sysId the value for cms_venue.SYS_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.SYS_NO
     *
     * @return the value of cms_venue.SYS_NO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getSysNo() {
        return sysNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.SYS_NO
     *
     * @param sysNo the value for cms_venue.SYS_NO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setSysNo(String sysNo) {
        this.sysNo = sysNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_HAS_METRO
     *
     * @return the value of cms_venue.VENUE_HAS_METRO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueHasMetro() {
        return venueHasMetro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_HAS_METRO
     *
     * @param venueHasMetro the value for cms_venue.VENUE_HAS_METRO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueHasMetro(Integer venueHasMetro) {
        this.venueHasMetro = venueHasMetro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_HAS_BUS
     *
     * @return the value of cms_venue.VENUE_HAS_BUS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueHasBus() {
        return venueHasBus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_HAS_BUS
     *
     * @param venueHasBus the value for cms_venue.VENUE_HAS_BUS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueHasBus(Integer venueHasBus) {
        this.venueHasBus = venueHasBus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_STARS
     *
     * @return the value of cms_venue.VENUE_STARS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueStars() {
        return venueStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_STARS
     *
     * @param venueStars the value for cms_venue.VENUE_STARS
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueStars(String venueStars) {
        this.venueStars = venueStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_IS_RECOMMEND
     *
     * @return the value of cms_venue.VENUE_IS_RECOMMEND
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Integer getVenueIsRecommend() {
        return venueIsRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_IS_RECOMMEND
     *
     * @param venueIsRecommend the value for cms_venue.VENUE_IS_RECOMMEND
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueIsRecommend(Integer venueIsRecommend) {
        this.venueIsRecommend = venueIsRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_RECOMMEND_TIME
     *
     * @return the value of cms_venue.VENUE_RECOMMEND_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public Date getVenueRecommendTime() {
        return venueRecommendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_RECOMMEND_TIME
     *
     * @param venueRecommendTime the value for cms_venue.VENUE_RECOMMEND_TIME
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueRecommendTime(Date venueRecommendTime) {
        this.venueRecommendTime = venueRecommendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_DEPT_ID
     *
     * @return the value of cms_venue.VENUE_DEPT_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueDeptId() {
        return venueDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_DEPT_ID
     *
     * @param venueDeptId the value for cms_venue.VENUE_DEPT_ID
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueDeptId(String venueDeptId) {
        this.venueDeptId = venueDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_DEPT_LABEL
     *
     * @return the value of cms_venue.VENUE_DEPT_LABEL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueDeptLabel() {
        return venueDeptLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_DEPT_LABEL
     *
     * @param venueDeptLabel the value for cms_venue.VENUE_DEPT_LABEL
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueDeptLabel(String venueDeptLabel) {
        this.venueDeptLabel = venueDeptLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_MEMO
     *
     * @return the value of cms_venue.VENUE_MEMO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueMemo() {
        return venueMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_MEMO
     *
     * @param venueMemo the value for cms_venue.VENUE_MEMO
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueMemo(String venueMemo) {
        this.venueMemo = venueMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_CROWD
     *
     * @return the value of cms_venue.VENUE_CROWD
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueCrowd() {
        return venueCrowd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_CROWD
     *
     * @param venueCrowd the value for cms_venue.VENUE_CROWD
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueCrowd(String venueCrowd) {
        this.venueCrowd = venueCrowd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_MOOD
     *
     * @return the value of cms_venue.VENUE_MOOD
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueMood() {
        return venueMood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_MOOD
     *
     * @param venueMood the value for cms_venue.VENUE_MOOD
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueMood(String venueMood) {
        this.venueMood = venueMood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_DEPT
     *
     * @return the value of cms_venue.VENUE_DEPT
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueDept() {
        return venueDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_DEPT
     *
     * @param venueDept the value for cms_venue.VENUE_DEPT
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueDept(String venueDept) {
        this.venueDept = venueDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_REMARK
     *
     * @return the value of cms_venue.VENUE_REMARK
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenueRemark() {
        return venueRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_REMARK
     *
     * @param venueRemark the value for cms_venue.VENUE_REMARK
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenueRemark(String venueRemark) {
        this.venueRemark = venueRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_venue.VENUE_PANORAMA
     *
     * @return the value of cms_venue.VENUE_PANORAMA
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public String getVenuePanorama() {
        return venuePanorama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_venue.VENUE_PANORAMA
     *
     * @param venuePanorama the value for cms_venue.VENUE_PANORAMA
     *
     * @mbggenerated Mon Jul 25 16:03:35 CST 2016
     */
    public void setVenuePanorama(String venuePanorama) {
        this.venuePanorama = venuePanorama;
    }

	public String getVenuePriceNotice() {
		return venuePriceNotice;
	}

	public void setVenuePriceNotice(String venuePriceNotice) {
		this.venuePriceNotice = venuePriceNotice;
	}
    
    
}